### ISSUE TITLE
session.execute alway  loop

### ISSUE THREAD

**Issue by yippeesoft** [NanoHttpd/nanohttpd#102]
very sorry about my eglish.pls pardon me.
thanks you very much about great nanohhtpds.

when I use nanohttpd,i found it goto a alway loop
 while (!finalAccept.isClosed()) {
                                        session.execute();
                                    }

like http://stackoverflow.com/questions/21936394/nanohttpd-leaking-threads

i debug the code
the sender just 
httpPost.setEntity

not setHeader

so at execute()
 if (splitbyte < rlen) {
                    inputStream.unread(buf, splitbyte, rlen - splitbyte);
                }

here :unread

and then 
decodeHeader throw

so it alway loop

i hope maybe explain it. and wait for your replay .thxs again!

sry.forget another:
when i send file use org.apache.http.entity.mime.MultipartEntity;
it apend at bounds like "charset utf-8"

so decodeMultipartData never find it

ps getBoundaryPositions work long time and return new int[0] and  cause timeout
i do not hnow much nio
 
may can found \r\n\r\n ?

sry about my english again

**Comment by ritchieGitHub** [comment]
A lot of fixes where included in the last few days, could you please test iif the bug is still there?

**Comment by ritchieGitHub** [comment]
no response so closed

**Comment by yippeesoft** [comment]
thx,sry too long replay.and a suggest ..you can let nanohttpd quick start support gradle and android?
