### ISSUE TITLE
Way to skip the "temporary folder"

### ISSUE THREAD

**Issue by 4i60r** [NanoHttpd/nanohttpd#111]
Hi, I'm currently developing web file explorer with NanoHttpd. When I'm uploading small files <2MB, upload is smooth, but when I want to upload some bigger file, e.g. 1GB it takes too long to complete the process. After the upload is done it starts copying the temp file into destination (and sometimes the destination is a folder on external sd card). I've tried making my own *TempFileManager* but it didn't seem to work as I've expected. 

How could I skip creating temporary file and upload it directly into destination path without copying/moving?

What I'm trying to achieve is "simply" creating the file in destination and append content sent by client without any temporary files.

**Comment by elonen** [comment]
The performance problems noted here are probably related to #112.
