### ISSUE TITLE
getBoundaryPositions() too slow

### ISSUE THREAD

**Issue by stefanuc111** [NanoHttpd/nanohttpd#112]
When i upload large file >10MB I have notice that is too slow to execute

**Comment by elonen** [comment]
Any ideas why this is? Are memory mapped files very slow on Android?

**Comment by elonen** [comment]
I tried to find some code for a string search operating on a [Mapped]ByteBuffer, that *definitely* wouldn't do a full memory copy, but no luck so far. If anyone knows a good solution, it would be really nice to replace the rather ugly getBoundaryPositions() with a shorter, faster and less convoluted piece of code.

**Comment by voltagex** [comment]
http://stackoverflow.com/questions/13473461/java-mappedbytebuffer-get-surprisingly-slow may explain why it's slow on Android

Is http://stackoverflow.com/a/19616304/229631 a possible solution?

**Comment by elonen** [comment]
Thanks @voltagex , that's definitely a major reason! Making a function call per byte is still a bad idea, though. The `Scanner` class, http://docs.oracle.com/javase/7/docs/api/java/util/Scanner.html might be worth trying out. We'll nee someone to test uploading a big file with an Android phone.

**Comment by elonen** [comment]
Ok, there's now a fix attempt in the `faster-boundary-find` branch. Anyone up to testing with an Android phone?

**Comment by pieterclaerhout** [comment]
I just tested this on an Android tablet, and it seems to make things quite a bit faster. Uploading a 9 MB file now only takes about 6 seconds, which is not too bad if you ask me.

**Comment by elonen** [comment]
Great, thanks for testing @pieterclaerhout ! I trust the uploaded files also didn't get truncated or anything? :)
