### ISSUE TITLE
core build fails on some linux systems because of excessive file handle creation

### ISSUE THREAD

**Issue by witbrock** [NanoHttpd/nanohttpd#113]
Between version 2.0.5 and 2.1.0, test changes seem to have been made that involve opening a large number of sockets.  Testing is great, but this has an unfortunate side effect:  the number of sockets created exceeds the hard file handle limit on some linux systems.

In particular, on my machine, ulimit -Hn returned 4096.
With maven 3.0 and Java 1.7_45,  mvn package in core failed with a JVM crash.
with maven 3.2 and Java 1.7_55  the packaging run threw IOExceptions (better).

However, it would be good to be able to build this package on a limited machine (this problem was quite hard to diagnose - more than a day, and raising the ulimit -Hn isn't something that ordinary users can do (and requires a reboot to propagate after a super user does it).

As part of my investigations, I found this very useful Java code fragment:
https://gist.github.com/jtai/5408684
It gets the OS file count limit. It would be wonderful if you could add this to the test, so that the test doesn't try to make more sockets than the process is allowed.

Thanks!

p.s. Also, NanoHttpd is really useful. PLEASE PLEASE put it (all of its parts (core, server, etc) in packaged form on a public maven repo so that one doesn't have to compile it oneself to use it.  Doing so makes a night and day difference in the ability of people to develop on top of your wonderful code.

**Comment by nullEuro** [comment]
+1, can confirm. Ubuntu 14.04 seems to have a limit of 1024 by default

**Comment by ritchieGitHub** [comment]
It is now in the central repo and due to less parallel tests the ulimit should be enough
