### ISSUE TITLE
Plugin handling

### ISSUE THREAD

**Issue by jbruchanov** [NanoHttpd/nanohttpd#117]
Maybe my plugin understanding is not perfect.

But i guess
SimpleWebServer.java@325 
should check plugin.canServeUri, otherwise it will call plugin based on mimeType which is not exactly what i would expect...

**Comment by voltagex** [comment]
https://github.com/NanoHttpd/nanohttpd/blob/master/webserver/src/main/java/fi/iki/elonen/SimpleWebServer.java#L414 seems to be correct now. Should this be closed?

**Comment by ritchieGitHub** [comment]
not completely there was a second check nessesary
