### ISSUE TITLE
implement if-range and if-none-match

### ISSUE THREAD

**Issue by mitchellsundt** [NanoHttpd/nanohttpd#122]
This is implemented in the change here: 

https://github.com/mitchellsundt/nanohttpd/commit/dde190f4d4326d560e3861b601295add26406576

The Android 4.4.2 webkit uses if-range and if-none-match headers in combination. 

The SimpleWebServer code did not implement if-range and did not correctly handle all the interactions with if-none-match.

**Comment by elonen** [comment]
Looks good. Could you perhaps rebase this on current NanoHttpd/nanohttpd master and provide a pull request?

**Comment by ritchieGitHub** [comment]
done the merge @elonen and or  @mitchellsundt could you test it?
