### ISSUE TITLE
sendAsFixedLength() relies on InputStream.available() to know how much data to send

### ISSUE THREAD

**Issue by dcpomeroy** [NanoHttpd/nanohttpd#127]
This seems to be a bug in the implementation.

The java documentation for InputStream says "Returns an estimate of the number of bytes that can be read (or skipped over) from this input stream without blocking by the next invocation of a method for this input stream."

This indicates that the value shouldn't be relied on when reading an input stream. However, in sendAsFixedLength(), data.available() is used to determine how much data to read. I think the fix would be to use read() until it returns -1, indicating that there is no additional data.

The specific InputStream I'm seeing this error with is org.apache.http.conn.EofSensorInputStream, which is returned when doing Http Requests.

**Comment by nullEuro** [comment]
Welp. Searched hours to find this as the source of a mysterious bug. If the `Response` constructor with an `InputStream` is used, `chunkedTransfer` should be set to *false*. Relying on undocumented hacks and implementation details does not seem like a good idea...

**Comment by ritchieGitHub** [comment]
Same as #94
