### ISSUE TITLE
problem with SOCKET_READ_TIMEOUT in nanohttpd

### ISSUE THREAD

**Issue by ihao** [NanoHttpd/nanohttpd#131]
in nanohttpd.java source, this param is defiend as FINAL. and default timtout is 5 seds.
when run websock, it will always close websocket connection.

but i can't modify timeout because of "static final int" setting.

so i must modify nanohttpd.java source to increase timeout value.

maybe let user can change it when runtime is more better. so they don't need to change lib source file.

**Comment by BlackWolf** [comment]
Just want to add that another (and I guess cleaner) solution is to simply remove the timeout:

**In NanoHTTPD.java**

Change
`public void start() throws IOException {`
to
`public void start(final int readTimeout) throws IOException {`

Change
`finalAccept.setSoTimeout(SOCKET_READ_TIMEOUT);`
to
`finalAccept.setSoTimeout(readTimeout < 0 ? SOCKET_READ_TIMEOUT : readTimeout);`

And add the following as a fallback for your existing code:
`public void start() throws IOException { this.start(-1);}`

**In you code**
Now, you can launch your websocket server using `.start(0);` to disable the timeout and it works great!

**Comment by 452** [comment]
yes, really needed..., for web sockets + http server

**Comment by ritchieGitHub** [comment]
done

**Comment by ihao** [comment]
good job!

**Comment by sajithsachu** [comment]
is it possible to make timeout as zero means connections should close as soon as the server sends the response
