### ISSUE TITLE
Header "Connection: close" not respected

### ISSUE THREAD

**Issue by cruxic** [NanoHttpd/nanohttpd#133]
If client makes a request with the "Connection: close" header, the server response should also say "Connection: close" and the server should close the socket after sending the response (see 8.1.2.1 in the HTTP spec).  NanoHttpd does not do this.  It just keeps the socket open.

Similarly, requests from HTTP/1.0 clients which do not specify "Connection: keep-alive" are implicitly expecting the connection to close.

Also if the response sends a "Connection: close" header then the socket needs to get closed no matter what the client said.

I discovered these issues because my PHP script would oddly hang for many seconds after using  file_get_contents() to my NanoHttpd server.

This issue is similar to https://github.com/NanoHttpd/nanohttpd/issues/46

**Comment by voltagex** [comment]
@elonen / @ritchieGitHub Does this need to be made into a pull request or has it already been fixed?

**Comment by ritchieGitHub** [comment]
No not fixed yet could you create a pull request?

**Comment by voltagex** [comment]
```
File to patch: ./core/src/main/java/fi/iki/elonen/NanoHTTPD.java
patching file ./core/src/main/java/fi/iki/elonen/NanoHTTPD.java
Hunk #1 FAILED at 602.
Hunk #2 FAILED at 629.
Hunk #3 succeeded at 1163 with fuzz 1 (offset 504 lines).
Hunk #4 FAILED at 855.
Hunk #5 FAILED at 939.
Hunk #6 FAILED at 948.
Hunk #7 FAILED at 1085.
patch unexpectedly ends in middle of line
Hunk #8 FAILED at 1098.
7 out of 8 hunks FAILED -- saving rejects to file ./core/src/main/java/fi/iki/el 
```

Unfortunately I don't understand the bug enough to replicate the patch.

**Comment by voltagex** [comment]
https://github.com/Songstack/Songstack/commit/e982c02a50e8ab311fc4486e266839af85adfd6a.patch may work better but it needs the filenames fixed to match this project.

**Comment by elonen** [comment]
@voltagex 's Songstack patch should probably replace the inferior, currently applied commit de2bb1bc9fa3959846741e1fd14076971e17b90c (unless there's more HTTP 1.0 incompatible stuff, but at least nobody has reported any so far).

**Comment by judofyr** [comment]
de2bb1bc9fa3959846741e1fd14076971e17b90c is fine, but that's a separate issue. `Connection: close` is valid in HTTP/1.1.
