### ISSUE TITLE
SSL code, logs, split classes, thread bug

### ISSUE THREAD

**Issue by alexmow** [NanoHttpd/nanohttpd#139]
Hi

I'd like to commit improvements to the SSL code (allow using p12 files, getting rid of the static code, integrating into current version). I'd changed it to not load certificates from the classpath, but from a file, as certificates expire and you don't want to recompile a jar file to replace an expired SSL certificate in your code base.

I'd also like to commit a small wrapper class that optionally allows to log to console or to a professional logging framework (the current printStackTrace()'s are somehow annoying and a missing log of http requests and responses makes it difficult to debug requests.

I furthermore think there is a bug in thread handling that i havent' figured out completely yet, it seems like threads are not created for each request, but once for each session and a thread stays opened much too long. A thread is not created for just a few milliseconds until a request or request batch is finished, but probably minutes (seems to be in the core code is the reason not in the thread class). Therefore the option to inject a custom thread pool class will not bring improvements for this issue.

But before I am investing time into this issue I'd like to know if submitted code gets integrated and if you think it is ok to move subclasses into separate class files, cause this would break the current mantra of having a single java file for everything.
Is there any other reason, why you would want to keep a single java code class?
Splitting the code into several classes would be very useful for easier debugging/maintaining the code, without getting the total lines of code increased.

Also I see there are open issues and pull requests for several month. Is this project still active?

**Comment by ritchieGitHub** [comment]
Yes, it is active (again)! Please create a pull request based on the master. But attention this project is a little different, one constrain is "one class" as far as possible (I would do that in no other project but here it is a precaution to keep it "nano")

**Comment by ritchieGitHub** [comment]
moved to the next release because no response of the requester yet.

**Comment by elfredo** [comment]
Hi, 
is there some sample code to understand how SSL can be enabled in NanoHTTPD?
thanks

**Comment by elonen** [comment]
@eighthave, do you think you could provide an example file (to be added to `samples/`) on how to use HTTPS?

**Comment by elfredo** [comment]
I manage to make it, with this code:
KeyStore ks = KeyStore.getInstance("BKS");
ks.load(new FileInputStream(keystore_fullpath), ksPass);
KeyManagerFactory kmf =  KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());	
kmf.init(ks, ctPass);
SSLContext sc = SSLContext.getInstance("TLS");
sc.init(kmf.getKeyManagers(), null, null);
server.makeSecure(sc.getServerSocketFactory());
		        	 
and force SSLv3 in Chrome. 
But there may be a better way to do it.

**Comment by ritchieGitHub** [comment]
ssl code is now tested and active if the support for p12 is still required than please provide a pull request.
