### ISSUE TITLE
File server not working

### ISSUE THREAD

**Issue by rawnsley** [NanoHttpd/nanohttpd#141]
Unless I'm being dense, I think the default behaviour of serving files is now missing. It used to be provided by the serveFile function, which is still reference in the comments, but that function has gone from the code.

This functionality is still referenced in the README file as well.

I'm not necessarily asking for it to be reinstated as I appreciate it walks the line between out-of-the-box utility and code brevity.

**Comment by elonen** [comment]
It is still exists, but it was split into SimpleWebServer at some point.
