### ISSUE TITLE
nohup with artifacts

### ISSUE THREAD

**Issue by andreibotezatu** [NanoHttpd/nanohttpd#143]
Hi,

Recently I was met with a problem while run NanoHTTPd compiled in jar and started with nohup as background service.

Since it's very interesting why this problem appears, but after 2 days I am so angry because I can't find how to solve this.

When run command: java -jar JavaWebServer.jar  it's works perfect, but with nohup is a big surprise, server listen, and no errors, but when I try to connect with them, the connection is in pending...pending...and nothing, only it's staying connecting... and no any response.

So guys, which of you has met with such problem, or the reason why I brought in such situation?

The project: https://copy.com/cHz6IESArjSygK0y

Regards Andrei.

**Comment by ritchieGitHub** [comment]
as you did not react to the answer I take it solved your problem
