### ISSUE TITLE
range value from GET command not init

### ISSUE THREAD

**Issue by wjjsun** [NanoHttpd/nanohttpd#150]
When user send a GET command with range firstly, then user send another GET command without range field, then the second GET command will still use the same range value from the previous GET command, which is not correct.

If use didn't send range in GET command, it should means range=0.
Below patch works for me:
```patch
diff --git a/core/src/main/java/fi/iki/elonen/NanoHTTPD.java b/core/src/main/java/fi/iki/elonen/NanoHTTPD.java
index ce292a4..aba21c4 100644
--- a/core/src/main/java/fi/iki/elonen/NanoHTTPD.java
+++ b/core/src/main/java/fi/iki/elonen/NanoHTTPD.java
@@ -1039,6 +1039,7 @@ public abstract class NanoHTTPD {
          */
         private void decodeHeader(BufferedReader in, Map<String, String> pre, Map<String, String> parms, Map<String, String> headers)
             throws ResponseException {
+            headers.put("range","bytes=0-");
             try {
                 // Read the request line
                 String inLine = in.readLine();
```
It seems I didn't have permission to push it.

**Comment by ritchieGitHub** [comment]
But the solution will be little more complicated... We will look into this.

**Comment by ritchieGitHub** [comment]
Does somebody know enough of the http protocol to make a deeper analysis of what the real problem is?

**Comment by elonen** [comment]
Sounds like a bug caused be headers not being cleared between requests within a single TCP connection. I believe this was fixed along with #118 .

**Comment by ritchieGitHub** [comment]
@wjjsun or @prhayes  could you test this please?

**Comment by prhayes** [comment]
Still an issue.

**Comment by elonen** [comment]
​Thank you @prhayes. How exactly did you perform the test (the more
detailed the better)?

**Comment by elonen** [comment]
I failed to reproduce this with telnet. First I started the server with `mvn exec:java -pl webserver -Dexec.mainClass="fi.iki.elonen.SimpleWebServer"`and then did:

```
$ telnet localhost 8080
Trying ::1...
Connected to localhost.
Escape character is '^]'.
GET /LICENSE.txt HTTP/1.1
Range: bytes=64-100

HTTP/1.1 206 Partial Content 
Content-Type: text/plain
Date: Sun, 9 Aug 2015 11:30:39 GMT
Accept-Ranges: bytes
Content-Range: bytes 64-100/1474
ETag: 9f31c732
Content-Length: 37
Connection: keep-alive

source and binary forms, with or with
GET /LICENSE.txt HTTP/1.1

HTTP/1.1 200 OK 
Content-Type: text/plain
Date: Sun, 9 Aug 2015 11:30:43 GMT
Accept-Ranges: bytes
ETag: 9f31c732
Content-Length: 1474
Connection: keep-alive

Copyright (c) 2012 - 2015, nanohttpd

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the nanohttpd nor the names of its contributors
   may be used to endorse or promote products derived from this software without
   specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.
Connection closed by foreign host.
```

The server prints, as expected:

```
GET '/LICENSE.txt' 
  HDR: 'remote-addr' = '127.0.0.1'
  HDR: 'http-client-ip' = '127.0.0.1'
  HDR: 'range' = 'bytes=64-100'
GET '/LICENSE.txt' 
  HDR: 'remote-addr' = '127.0.0.1'
  HDR: 'http-client-ip' = '127.0.0.1'
```

Anyway, I'm really puzzled if the patch above (`headers.put("range","bytes=0-");`) works but this is still happens after 0a25aeb. The relevant code from NanoHTTPD.java:

```java
if (null == this.headers) {
    this.headers = new HashMap<String, String>();
} else {
    this.headers.clear();
}

if (null != this.remoteIp) {
    this.headers.put("remote-addr", this.remoteIp);
    this.headers.put("http-client-ip", this.remoteIp);
}

// Create a BufferedReader for parsing the header.
BufferedReader hin = new BufferedReader(new InputStreamReader(new ByteArrayInputStream(buf, 0, this.rlen)));

// Decode the header into parms and header java properties
Map<String, String> pre = new HashMap<String, String>();
decodeHeader(hin, pre, this.parms, this.headers);
```

That's the only place where the private `decodeHeader()` is called, so I can't see any way `this.headers` could contain anything except perhaps remoteIp related stuff.

**Comment by LordFokas** [comment]
I haven't had the time to look too deep into this yet, but here goes:

It seems to me every time a request arrives on the same `HTTPSession` the same header map is being used and overwritten, which means whenever a header is undefined we're getting whatever thrash we had there in the previous calls which can lead to all kinds of issues. Luckily it has been happening with range, it could have been way worse (like caching or upgrade requests).

If that is really it I'd like to propose, instead of hacking over it with a `headers.put(k, v)`, to actually fix it and prevent it from being reborn in the future with another header.
What I mean is, `HTTPSession.headers` should start with a null value when it is constructed, and right the moment before attempting to decode the headers (here: https://github.com/NanoHttpd/nanohttpd/blob/master/core/src/main/java/fi/iki/elonen/NanoHTTPD.java#L821 ) we set the `headers` field to a brand new map.

Also, from the superficial look I gave it, I have a question. What would happen if 2 requests to the same session arrived at virtually the same time? That is, would it be possible for `execute()` to run multiple times simultaneously for the same object?

**Comment by elonen** [comment]
A HTTPSession is used for one TCP connection at a time (it's there to
implement HTTP keepalive), so simultaneous calls through it shouldn't
really be possible.

**Comment by LordFokas** [comment]
Oh, ok thanks :)

**Comment by ritchieGitHub** [comment]
@LordFokas  could you check if this can be closed?

**Comment by LordFokas** [comment]
I'm not sure... the last time I looked at this I couldn't take any substantial conclusions... it all just seemed like witchcraft to me.

**Comment by ritchieGitHub** [comment]
@wjjsun or @prhayes because we have a very hard time reproducing this, could you please provide a unit test?

**Comment by ritchieGitHub** [comment]
@wjjsun or @prhayes please reopen this issue if it persiss
