### ISSUE TITLE
Not all contents are read from input stream when processing POST

### ISSUE THREAD

**Issue by martinrotter** [NanoHttpd/nanohttpd#153]
Problem is here: https://github.com/NanoHttpd/nanohttpd/blob/master/core/src/main/java/fi/iki/elonen/NanoHTTPD.java#L1014

Imagine my file is 600 bytes long AND 511st, 512nd bytes are "\r\n". Then your code reads first 512 bytes chunk (which ends with "\r\n") and then stops at that point because second condition in while cycle is not met, but there still remains 88 bytes in input stream!!

Why do you exactly use second condition in that while cycle?

**Comment by elonen** [comment]
Good question. I think it's a leftover from the time when the only supported HTTP POST encoding type was `application/x-www-form-urlencoded` which is supposed to be just one line.

**Comment by martinrotter** [comment]
Yes, follow-up question. This definitely sounds like a bug. This should be fixed. :)

**Comment by elonen** [comment]
Traced this to ktogias's original file upload implementation, so no record for why it's there.
