### ISSUE TITLE
final Socket finalAccept = myServerSocket.accept(); report socket is closed on Android

### ISSUE THREAD

**Issue by baijianhua** [NanoHttpd/nanohttpd#159]
In original NanoHTTPD.java, start method is like this.  If I run this on Android, an socket is closed Exception will be reported.(Android 5.0, Nexus 4)

```
public void start() throws IOException {
        myServerSocket = new ServerSocket();
        myServerSocket.bind((hostname != null) ? new InetSocketAddress(hostname, myPort) : new InetSocketAddress(myPort));

        myThread = new Thread(new Runnable() {
            @Override
            public void run() {
                do {
                    try {
                        final Socket finalAccept = myServerSocket.accept();
                        registerConnection(finalAccept);
                        finalAccept.setSoTimeout(SOCKET_READ_TIMEOUT);
                        final InputStream inputStream = finalAccept.getInputStream();
                        asyncRunner.exec(new Runnable() {

```

After I change the code to this, it works.
```
public void start() throws IOException {
        myThread = new Thread(new Runnable() {
        	@Override
            public void run() {
        		try {
					myServerSocket = new ServerSocket();
					InetSocketAddress addr = null;
					if(hostname != null){
						addr = new InetSocketAddress(hostname, myPort);
					}else{
						addr = new InetSocketAddress(myPort);
					}
					myServerSocket.bind(addr);
					 
				} catch (IOException e1) {
					e1.printStackTrace();
					return;
				}
               
                
        		
        		do {
                    try {
                        final Socket finalAccept = myServerSocket.accept();
                        registerConnection(finalAccept);
                        finalAccept.setSoTimeout(SOCKET_READ_TIMEOUT);
                        final InputStream inputStream = finalAccept.getInputStream();
                        asyncRunner.exec(new Runnable() {
```

**Comment by gunmetal313** [comment]
Hi :) Can you make Pull Requests to https://github.com/gunmetal313/nanohttpd.core ?

**Comment by ritchieGitHub** [comment]
I do not see a real difference in the code, only the timing could be different so better we integrate it.

**Comment by elonen** [comment]
Looks functionally equivalent to me also, apart from the exception. Is there any reason not to let the IOException terminate the function instead of catching it?

Style-wise I like the ternary operator better (less code lines to read through).

**Comment by AlbinTheander** [comment]
Android has a main thread that is used to update the UI among other things. It has always been recommended not to do any IO related stuff on that thread. I think they enforce this more strictly in later Android version.

This means that doing `bind` outside of the new thread may not succeed if the outer thread is the main thread. We can probably keep the code close to the original, as long as we move the `bind` part to inside the new thread. (Could be that the error handling around the IOException should be different, though.)

**Comment by elonen** [comment]
Ah, I see. If you have some fixed code, could you make a pull request? That
would be a great help.

**Comment by ritchieGitHub** [comment]
the code is above, we only have to find a "beautiful" was to pass the exception to the outside. a small "wait for socket to bind" loop, and store the exception in a variable (no problem anymore because it is now a named inner class). I won't have time to do it till the weekend, so if want to give it a try ;-)

**Comment by ritchieGitHub** [comment]
Ok, an implementation is done that is as backward compatible as possible. Could somebody try it?

**Comment by ritchieGitHub** [comment]
@baijianhua and or @gunmetal313 could one of you try the current implementation?

**Comment by ritchieGitHub** [comment]
assumed fixed, please reopen when it is not
