### ISSUE TITLE
mount/unmount capability for SimpleWebServer

### ISSUE THREAD

**Issue by adrianulbona** [NanoHttpd/nanohttpd#161]
I have an use-case where I want to add files to be served by a SimpleWebServer after I create it. The ```rootDirs``` is not available to be modified: 

```
    private List<File> getRootDirs() {
        return rootDirs;
    }

    private void addWwwRootDir(File wwwroot) {
        rootDirs.add(wwwroot);
    }
```

It will help if these methods are at least protected. 

What do you think? Will it break something?

**Comment by elonen** [comment]
Hmm.. there's really not much point in the getRootDirs() accessor that simply returns a modifiable List.
Ditching the accessors and exposing the rootDirs variable as a protected variable might be a clearer way.

**Comment by adrianulbona** [comment]
I agree. Thanks for fixing it.
