### ISSUE TITLE
project owner does not seem to maintain this project anymore

### ISSUE THREAD

**Issue by ritchieGitHub** [NanoHttpd/nanohttpd#169]
after waiting to for my pull request to be included (adaptations for deployment to central) for a while i noticed that the project owner has not reacted to any request for almost a year.

There are a lot of bug fixes and features waiting, so who is with me to create a new organisation and start a new maintained fork? I do not have the time (i have a lot of other open-source projects I work on more actively) to go into the core of this project but i am willing to help with build issues, unit-tests travis-ci and so.  

But if there are some developers that will take the core part of the job, like checking if a pull request is plausible or would break something (that's not yet in the unit test ;-) ). Than I can take the part of build structure, releasing and central deployment.  
 
anyone?

**Comment by elonen** [comment]
I personally haven't maintained the project since it was imported to Github and converted to Java >1.1.
@psh , looks like your latest Github and Twitter activities are from last November, are you still with  us?

**Comment by hewmeister** [comment]
This product seems too useful to be abandoned.  I can probably help with testing.

**Comment by elonen** [comment]
Just noticed it was private for some reason, but I'm an admin in the project. If @psh turns out to be MIA, I can grant writing rights to people, so no need for a fork just for the sake of getting the project maintainable again.

**Comment by ritchieGitHub** [comment]
Great, that means much better changes to get it going again! How long would you say, should we wait for @psh  to react?

**Comment by ritchieGitHub** [comment]
@elonen I propose to wait till end of the month, if @psh is still MIA then could you include me as project member? Then I will include the central release stuff and prepare a 2.2 release where we can include the most important pull requests. There are so many, so we should probably do a voting.

**Comment by el-mot** [comment]
@ritchieGitHub, @elonen <https://github.com/elonen> I agree

**Comment by elonen** [comment]
That sounds reasonable @ritchieGitHub. Some complications arose with admin settings, but I'm currently trying and sort them out.

**Comment by ritchieGitHub** [comment]
Could you add me as an admin, then I will update the project and when that is finished we can start the voting.

**Comment by elonen** [comment]
Added. There's a problem, however: @psh has apparently forgot to add the main repository to the admin group. Creating a new repository under the NanoHttpd "organization" works though, so one possibility would be to for the current main one into e.g. "NanoHttpd/nanohttpd-dev", and start merging stuff there. I'll keep on trying to reach Paul.

**Comment by ritchieGitHub** [comment]
that would be a solution, but lets try to contact github themself. I send them a request, maybe they will grant us the access rights. I may have found a good project icon 
![c34-c2-5](https://cloud.githubusercontent.com/assets/9456779/7439931/4c896c3c-f096-11e4-998d-53e496f5412f.png) . It is a Carbon molecule extremely small and extremely powerfull ;-)

**Comment by elonen** [comment]
I already contacted Github support: "For security reasons, we are not able
to add you to the Owners Team or transfer the repository to the Admin team
in order to grant you access."
Hope Paul receives one of my messages soon.

The carbon molecule is a nice idea.

**Comment by elonen** [comment]
I've got full access now, so no need for an extra repository anymore. Thank you @psh !

**Comment by ritchieGitHub** [comment]
yes, great thanks @psh
