### ISSUE TITLE
Test Cases

### ISSUE THREAD

**Issue by rnveach** [NanoHttpd/nanohttpd#172]
@elonen
Nice job on taking over, but I hate to be the bringer of bad news but one of the recently merged commits has a syntax error.
See commit 98d6d146214026ab242ce1de320bd7d203d7a5f3:
````
if (headerName.equalsIgnoreCase("content-length") {
````
No ending ')'.

I also noticed alot of the new stuff being merged in have no test cases to make sure they work correctly and don't impact previous functionality. I'm sure not everything needs to be tested, but the project should aim to make sure some percentage of the code is tested and works. This doesn't have to be done right away, but the longer you wait, the more this simple task will become a nightmare depending on how big 'nano' grows. (unintended joke)

**Comment by rnveach** [comment]
All the non-integration tests (I don't have the library to run the integration folder) pass for me, except "testHeadersRemoteIp" in "HttpSessionHeadersTest"
java.lang.AssertionError: expected:<127.0.0.1> but was:<null>
	at org.junit.Assert.assertEquals(Assert.java:144)
	at fi.iki.elonen.HttpSessionHeadersTest.testHeadersRemoteIp(HttpSessionHeadersTest.java:28)

The "session.getHeaders()" is completely empty for me.

**Comment by elonen** [comment]
Would you like to contribute the tests? I haven't really developed the
project for years since @psh moved it to GitHub, and only came back for
necessity, so any help would be much appreciated!

**Comment by rnveach** [comment]
I am stretched too thin right now, and I don't know enough of the inner workings of nanohttpd or HTTP requests in general to write the needed tests.

**Comment by ritchieGitHub** [comment]
@hewmeister you mentioned helping with tests, now we need it more than ever. Including them as unit tests would be perfect bonus!

**Comment by elonen** [comment]
(Ok, fixed the missing paren at least, 1bb6a4bfa98630e5ea2377a8e763c36351e1134d)

**Comment by elonen** [comment]
I've opened a new issue for the failing unit test, #173.
