### ISSUE TITLE
testHeadersRemoteIp unit test fails

### ISSUE THREAD

**Issue by elonen** [NanoHttpd/nanohttpd#173]
@rnveach:
All the non-integration tests (I don't have the library to run the integration folder) pass for me, except "testHeadersRemoteIp" in "HttpSessionHeadersTest"
java.lang.AssertionError: expected:<127.0.0.1> but was:<null>
at org.junit.Assert.assertEquals(Assert.java:144)
at fi.iki.elonen.HttpSessionHeadersTest.testHeadersRemoteIp(HttpSessionHeadersTest.java:28)
The "session.getHeaders()" is completely empty for me.

@elonen:
The problem is really in the tests; the pseudo headers are now only filled just before serve(), not in the constructor, so either the test should be updated or the header clear() and .put() x 2 refactored into a function (e.g. private void clearAndPrefillHeaders()) and called in the constructor AND before serve(). I'm more inclined to changing the test as you shouldn't really need the Session object's headers map for anything before it's passed to serve().

**Comment by ritchieGitHub** [comment]
all working at the same time, just marked it as "Ignored" till resolved
