### ISSUE TITLE
GZIP compression support

### ISSUE THREAD

**Issue by ritchieGitHub** [NanoHttpd/nanohttpd#177]
add GZIP compression support to the server. (from #63)

**Comment by AlbinTheander** [comment]
I wouldn't mind taking a peek at this.

I haven't been following the project for a while. How concerned are we with backwards compatibility? I would like to add this inside of the Response class, but if I add a parameter to the Response constructor (to specify the content-encoding), it would probably break a lot of usages.

**Comment by elonen** [comment]
Great to hear, and much appreciated! We just recently committed a major change to Response, so now would be a perfect time to introduce this. Response is now created with a factory function instead of directly with a constructor.

**Comment by ritchieGitHub** [comment]
Yes, great just take case to keep the factory methods "clean".

**Comment by elonen** [comment]
Maybe a separate toggle function, like `public Deflater setCompression(bool use_gzip)` instead of a boolean in the constructors? (The idea behind returning Deflater was that you can set compression level and some other parameters through it.)

**Comment by AlbinTheander** [comment]
I guess the factory methods in question are the `newFixedLengthResponse` and `newChunkedResponse`.

Fixed length responses may be a problem, since you would need to zip the entire InputStream before knowing the final size.

I'll see what I can do. Let me know if you have any thoughts about this.

**Comment by AlbinTheander** [comment]
I submitted a pull request now. I don't expose the `Deflater` for the simple reason that it was easier to just use the GzipOutputStream directly instead of keeping track of headers and trailers manually.

**Comment by ritchieGitHub** [comment]
Just checked the changes, they sound good thanks. @elonen do you concur that we can merge this?

**Comment by elonen** [comment]
Yes.

**Comment by ritchieGitHub** [comment]
Mer

**Comment by eduard93** [comment]
How can user enable GZIP compression?
My code:

```
   public Response serve(IHTTPSession session) {
        ByteArrayInputStream resBody = new ByteArrayInputStream(new byte[0]);
        try {
            resBody = new ByteArrayInputStream("{\"response\":1}".getBytes("UTF-8"));
        } catch (UnsupportedEncodingException ex) {
        }
        Response res = newChunkedResponse(OK, "application/json", resBody);

        res.setGzipEncoding(true);
        return res;
    }
```

And this request:

```
GET / HTTP/1.1
Host: localhost:8080
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,ru;q=0.8
```

Produces this response:

```
HTTP/1.1 200 OK 
Content-Type: application/json
Date: Tue, 28 Aug 2018 11:39:12 GMT
Connection: keep-alive
Transfer-Encoding: chunked

{"response":1}
```
