### ISSUE TITLE
Make syntax groovy-compatible

### ISSUE THREAD

**Issue by sarnobat** [NanoHttpd/nanohttpd#181]
I'm trying to subclass NanoHTTPD.java in Groovy (using plain java syntax). The Groovy compiler takes issue with a couple of things like mod() arithmetic, do...while loops, and the symbol "in" being a reserved keyword.

I was able to modify the code to get it to work but would rather use NanoHTTPD.java unmodified. 

It would be great if someone can make these changes. I'd volunteer myself to do it but haven't contributed to any open-source projects before and may not follow all etiquette diligently.

**Comment by ritchieGitHub** [comment]
no problem, just fork the repository. make your changes, build to check if the tests still work. and then on github create a "pull request" . No other etiquette to folow ;-)

**Comment by sarnobat** [comment]
Oh great, I'll make these changes some time soon.

**Comment by sarnobat** [comment]
I think the latest version of the code doesn't have the issues I faced in what I forked. So feel free to close this issue.

**Comment by ritchieGitHub** [comment]
thanks!
