### ISSUE TITLE
decodeHeader method fix for streaming to mobile devices

### ISSUE THREAD

**Issue by prhayes** [NanoHttpd/nanohttpd#182]
Adding the following :

    headers.put("range","bytes=0-");

as first line of  method **decodeHeader** allows me to stream to mobile devices, not clued up enough to know ramifications of this change but it works great.

**Comment by ritchieGitHub** [comment]
this solution was already proposed in an other issue: #150 but I think this is just a way around a bug somewhere else. So does somebody know enough of the http protocol to make a deeper analysis of what the real problem is?
