### ISSUE TITLE
jdk 1.6 - backwards compatibilty

### ISSUE THREAD

**Issue by samsonl** [NanoHttpd/nanohttpd#185]
Hi

When I try and compile using JDK 1.6 I see the following errors;

safeClose(java.io.Closeable) in fi.iki.elonen.NanoHTTPD cannot be applied to (java.net.Socket)

Sockets didn't implement Closeable until 1.7.

Is the HEAD version supposed to be compatible with jdk 1.6?

PS. Love this app!

**Comment by samsonl** [comment]
Sorry my bad, just read the website and it says HEAD is 'current' , will look at the JDK 1.1 version source.

**Comment by samsonl** [comment]
Although the readme for 1.1 does mention JDK 1.6 compatiblity?

**Comment by ritchieGitHub** [comment]
sorry but JDK 1.6 was no target anymore, and the 1.1 thread is very old. We coud reacivate 1.6 support when there is a reason. Why are you limmited to 1.6? (JDK 1.7 is running out of oracle support soon...)

**Comment by samsonl** [comment]
I am limited by a restrictive enterprise environment, but as there were only a few errors I patched the code. Thanks for getting back to me, great work!

**Comment by ritchieGitHub** [comment]
@elonen when the changes are so minimal maybe we could make 1.6 the current supported jre?
@samsonl would you create a pull request?

**Comment by AlbinTheander** [comment]
Isn't this pull request already fixing that issue: https://github.com/NanoHttpd/nanohttpd/pull/183?

**Comment by ritchieGitHub** [comment]
could be, I will check it it is that simple ;-)

**Comment by elonen** [comment]
Yes, if it's that simple, let's do it. Can the Maven scripts be configured to enforce 1.6? We can always lift the restriction again when the need arises.

**Comment by ritchieGitHub** [comment]
Ok done i will configure the tests and maven
