### ISSUE TITLE
SSL version or Cipher mismatch

### ISSUE THREAD

**Issue by elfredo** [NanoHttpd/nanohttpd#189]
Hi,

I get a 'SSL version or Cipher mismatch" error when I use Chrome on a running NanoHTTPD HTTPS server. I've created a keystore and a certifcate, and used:
   SSLServerSocketFactory ssf = NanoHTTPD.makeSSLSocketFactory(keystore_file, password);
   server.makeSecure(ssf);
And it seems to load the keystore correctly.

Would you know where could be the issue ?

**Comment by elonen** [comment]
*Related to #139.*
