### ISSUE TITLE
First byte missing when uploading an image

### ISSUE THREAD

**Issue by romsahel** [NanoHttpd/nanohttpd#190]
I'm making a simple webserver that can be used to upload files with an HTML form:
```html
<form method="post" enctype="multipart/form-data" action="uploadfile">
    <input type="file" name="filename">
    <input type="submit" value="Send">
</form>
```
I then serve the GET request and use `session.parseBody(files)`. This works fine with most files however, when I use images (jpeg and bmp - at the very least, there might more format affected), the first byte of the file (at address 0x000000 then) is missing.
Thus, a workaround might be to change line 609 in core/src/main/java/fi/iki/elonen/NanoHTTPD.java from:
```java
int part_header_len = len - (int) in.skip(MAX_HEADER_SIZE);
```
to
```java
int part_header_len = len - (int) in.skip(MAX_HEADER_SIZE) - 1;
```
for these particular formats... but this seems more than hacky.

Is the problem on my end or is it an issue with nanohttpd's core?

My code to save the files is
```java
final File src = new File(files.get("filename"));
final File dst = new File(rootDir, parms.get("filename"));
Files.copy(src.toPath(), dst.toPath(), StandardCopyOption.REPLACE_EXISTING);
```

**Comment by ritchieGitHub** [comment]
This was fixed in context of #240 if not please reopen
