### ISSUE TITLE
Failed to connect  WebSocketServer: A server must not mask any frames that it sends to the client.

### ISSUE THREAD

**Issue by AzenHuang** [NanoHttpd/nanohttpd#191]
I tried to use EchoSocketSample to start a WebSocketServer, then tested connection using http://www.websocket.org/echo.html , but failed! The chrome console showed such error, "WebSocket connection to 'ws://localhost:9090/?encoding=text' failed: A server must not mask any frames that it sends to the client."

**Comment by AzenHuang** [comment]
I traced the code,found the following snippet which caused the error.Maybe GZIPOutputStream caused that.
![error](https://cloud.githubusercontent.com/assets/5846900/7976942/fcda58ec-0ab5-11e5-91f1-09ab3ab4f4d3.png)

**Comment by ritchieGitHub** [comment]
just tested it, you are correct! probably not all websocet implementations accept websocket and gzip together.

**Comment by ritchieGitHub** [comment]
should work now, thanks for the report
