### ISSUE TITLE
File can't decode correctly when I post a file to server

### ISSUE THREAD

**Issue by AzenHuang** [NanoHttpd/nanohttpd#192]
The file saved on server may lose some bytes when  I post a file .I find "part_data_start"  probably miscount  at line 613 .
```java
    int part_data_start = boundary_idxs[bi] + part_header_len;
```
Then I use the previous version of NanoHTTPD code to replace the snippet like following, and it works OK.
```java
        int part_data_start = stripMultipartHeaders(fbuf, boundary_idxs[bi]);
        /**
         * It returns the offset separating multipart file headers from the file's data.
         */
        private int stripMultipartHeaders(ByteBuffer b, int offset) {
            int i;
            for (i = offset; i < b.limit(); i++) {
                if (b.get(i) == '\r' && b.get(++i) == '\n' && b.get(++i) == '\r' && b.get(++i) == '\n') {
                    break;
                }
            }
            return i + 1;
        } 
```

**Comment by elonen** [comment]
Thank you @AzenHuang. Can you post a fix and/or an example file + HTML form (test case) that loses the bytes?

**Comment by toma315** [comment]
I ran into the same problem ... part_header_len ist calculated wrong. Using in.skip() the number of characters not being in the header is counted. However, the number of characters is not necessarily identical to the number of bytes when counting outside of the header (the header itself is usually 7bit Ascii, the data is not).

A quick workaround (use a character encoding with byte count == character count):

--- a/directorNG/director/src/fi/iki/elonen/NanoHTTPD.java	Thu Jun 11 21:16:46 2015 +0200
+++ b/directorNG/director/src/fi/iki/elonen/NanoHTTPD.java	Fri Jun 12 22:31:25 2015 +0200
@@ -573,7 +573,7 @@
                     int len = (fbuf.remaining() < MAX_HEADER_SIZE) ? fbuf.remaining() : MAX_HEADER_SIZE;
                     fbuf.get(part_header_buff, 0, len);
                     ByteArrayInputStream bais = new ByteArrayInputStream(part_header_buff, 0, len);
-                    BufferedReader in = new BufferedReader(new InputStreamReader(bais));
+                    BufferedReader in = new BufferedReader(new InputStreamReader(bais,"latin1"));
 
                     // First line is boundary string
                     String mpline = in.readLine();
