### ISSUE TITLE
Should the constructor of nested class Response close the InputStream "data"?

### ISSUE THREAD

**Issue by moralvolcano** [NanoHttpd/nanohttpd#194]
The constructor of the nested class Response does not close the inputstream. The user code calling this constructor cannot close it.
 
    Response(IStatus status, String mimeType, InputStream data, long totalBytes)

**Comment by elonen** [comment]
It should not; the session may use keepalive and transmit several HTTP requests / responses through the same TCP connection.

**Comment by moralvolcano** [comment]
In that case, could you add an overload with a boolean argument for closing the stream? The memory size of the server keeps increasing if the inputstream is not closed and garbage collection is not quick enough to clear those blobs from memory.

**Comment by elonen** [comment]
You can call `Response.setKeepAlive(false)` to close the connection as soon as the response is sent.
