### ISSUE TITLE
Transmission hangs when using gzip compression

### ISSUE THREAD

**Issue by kustco** [NanoHttpd/nanohttpd#195]
I am quite new to this project and haven't seen the history of this project. I just found the project few days ago and found it useful in my current project... Thank you very much! I am also not yet very confident in Java. So please excuse when this bug report is only a stupid mistake on my side. Did I understand correclty, that support of gzip was introduced only a month ago?

I use a standard web server, as shown in the samples "HelloServer.java". Also that server without modifications shows the problem: A current Firefox or the IE11 Internet Explorer wait for each page they receive several seconds, obviously until some timeout occurs, before they display the result. My guess is that the reason is that NanoHTTPD does not send the "Content-Length:" header field in combination with "gzip" encoding. (At least Firefox sends "gzip, deflate" in the "Accept-Encoding" header, and NanoHTTPD decides to use "gzip"; and does not send any content length anymore.)

When I add an ugly hack to my server class to suppress gzip encoding, everything works as expected:
```java
        String encoding = session.getHeaders().get("accept-encoding");
        encoding = encoding.replaceAll("gzip", "NO_GZIP");
        session.getHeaders().put("accept-encoding", encoding);
```
This tricks NanoHTTPD to not see anymore that the client accepts gzip, and sends the response unzipped, and with a correct content length. The browser knows when the response is finished, and shows it immediately without timeout.

Yes, I saw that todays latest version of NanoHTTPD provides a new method useGzipWhenAccepted() that could be overwritten, instead of modifying the header fields, but this doesn't solve the issue that gzip is not yet working in a good way.

Best regards, and thanks for looking at this issue,
kustco.

P.S.: When you agree that this is a bug and that even for gzip a correct "Content-Length" should be sent in the response, I could try to fix the issue myself and perform a pull request. But I suppose, stability and code quality would be better, when you fix it. I do not even know the HTTP specifications: Is the zipped or the uncompressed content length to be reported in that header? Or possibly even the header field is forbidden for "gzip", NanoHTTPD is right, and Firefox is wrong. Or anything other in my personal environment.

**Comment by kustco** [comment]
I just found that there is a pull request #193 that is supposed to fix this issue. I only searched for issues, and not for fixes, before submitting my issue...

https://github.com/NanoHttpd/nanohttpd/pull/193

**Comment by ritchieGitHub** [comment]
no problem! better an issue to much than missing one, thanks for reporting
