### ISSUE TITLE
discussion should gzip be activated by default?

### ISSUE THREAD

**Issue by ritchieGitHub** [NanoHttpd/nanohttpd#196]
Have been thinking that even if have gzip compression is great, we should not activate it by default?
nanohttpd runs on very small devices with next to no performance needed, gzip changed this... Never forget that in many cases nanohttpd is running on a many times slower machine as the "client" / browser.
Opinions please!

**Comment by elonen** [comment]
Agreed. Android seems especially important platform, including very low end
devices.

**Comment by ritchieGitHub** [comment]
ok, set to false now. 
I leave the issue open for a while to see if there is someone with an other opinion?

**Comment by elonen** [comment]
A sensible but slightly more complicated default policy might be to compress generated status-200 text responses (e.g. JSON) by default, but leave all binary stuff untouched. See the graphs here, the bandwidth savings can be substantial: http://web-resource-optimization.blogspot.fi/2011/06/json-compression-algorithms.html

**Comment by kira1928** [comment]
I think gzip can be default for text files. It can save a lot of bandwidth comparing with its extra CPU usage.

**Comment by ritchieGitHub** [comment]
I am still not sure, a per request decision seems reasonable but a micro device hase more trouble compressing than sending 1k bytes. The more I think about it the more I think it should be very flexible...

**Comment by ritchieGitHub** [comment]
On the other hand, nanohttpd will be used in 99% for a single task (correct me if I am wrong) so if there is a json request it is highly probable that all requests will be json. So it is likely the option will be allways on or off. With the exception of binary data like images where it just does not make sense to gzip them at all. So I think we should have two options, one general on/off with the default off (and on in the simple-webserver). and one option depending on the mine type of the response? or we give the mime type as a parameter to the method (or even the response itself)?

**Comment by ritchieGitHub** [comment]
great, thanks!

**Comment by dagnelies** [comment]
Hi,

My 2 cents: I'd compress everything by default.

Usually, the smartphone's bottleneck is more the low bandwidth, rather than the CPU. *By not compressing the stream, I think you'd be doing more harm than good.* Also, the CPU consumption for decompressing the stream is probably rather negligible compared to the time it requires for layouting the page.

**Comment by ritchieGitHub** [comment]
Not really true for jpeg/videos and other already compressed stuff. There is can cost a lot of cpu with no (or even negative) result.

**Comment by hypersoft** [comment]
And a few years later, somebody came along and said: Shouldn't there be a mime-type-list for files to auto-compress? And for extra-good-measure, only compress over-the-internet streams... You can even get really smart, and have a compressed-file-cache that auto-updates when the source is modified. Every cached file should have a last-access-timestamp. There should be an auto-trim (post-request) function to dequeue files that are not being requested during the latency period.

[just-a-comment for your thinking of a suitable-solution]
