### ISSUE TITLE
unit test's for ssl support

### ISSUE THREAD

**Issue by ritchieGitHub** [NanoHttpd/nanohttpd#197]
Unit tests for the ssl support are still missing. @eighthave how about those unit tests you made yourself?

**Comment by eighthave** [comment]
I only have some raw sketches, nothing worth sharing yet

**Comment by ritchieGitHub** [comment]
sorry to hear that ...

**Comment by elonen** [comment]
Could you perhaps push the drafts to a branch? I might have some time to
work on the tests in the near future if there's something to start from.

**Comment by ritchieGitHub** [comment]
because nothing was provided :-( I have implemented the tests myself.
