### ISSUE TITLE
NanoHTTPD is shutdown

### ISSUE THREAD

**Issue by pepibumur** [NanoHttpd/nanohttpd#198]
### What?
I'm using NanoHTTPD to launch a web server on an Android device. It works well but sometimes I receive an exception message `NanoHttpd Shutdown` in the line `fi.iki.elonen.NanoHTTPD$HTTPSession in execute at line 714 `.

I've been looking for that exception bug I haven't found any useful information. Is that a bug of the server? How could it be fixed?

**Comment by elonen** [comment]
It's probably not a sign of an error. The `ClientHandler` receiving a `SocketException` just means the TCP connection was closed by a client (browser) or the server (in case HTTP 1.1 keepalive is not supported).

**Comment by pepibumur** [comment]
@elonen but is it needed to restart the server in that case. I have to keep it alive during the app lifecycle. Otherwise the webview will fail in the content load. 
Thanks for you response :)

**Comment by elonen** [comment]
You mean an exception closes the whole server process? `ServerRunnable.run()` should keep on accepting new connections when a single one is closed. Does it exit on your implementation and if so, by what kind of exception?
