### ISSUE TITLE
"java.lang.IncompatibleClassChangeError: interface not implemented" in Android versions prior 19

### ISSUE THREAD

**Issue by Aggelos88** [NanoHttpd/nanohttpd#199]
Hello,

First of all, this is a great library and thanks for providing it. I get this error when i compile the application with > 19 Android version and the application runs on Android < 19. This happens because Socket (and probably ServerSocket) is implenting Closeable in apis > 19 but for lower apis, it does not implement it. This results in java.lang.IncompatibleClassChangeError when safeClose is called with input a Socket object. Can you please check this?

Link for this issue in AOSP: https://code.google.com/p/android/issues/detail?id=62909

Thanks

**Comment by ritchieGitHub** [comment]
it is intended that you compile the class using max java 1.7 then the program will run on all versions.
Best use the pre build version of nanohttpd (currently from sonatype snapshot repository), a release of the current version will come soon.

**Comment by ritchieGitHub** [comment]
as I read the code this is fixed
