### ISSUE TITLE
Implement an easy way to add custom mime types to Webserver?

### ISSUE THREAD

**Issue by elonen** [NanoHttpd/nanohttpd#204]
WebServer module users often need to declare custom mime types for their application. There seems to be need for a solution that doesn't involve editing the source code.

Related: #200 #203

**Comment by ritchieGitHub** [comment]
what about a file in the root directory that is being served called additional.minetypes? I know normally we should not do any config in files, but maybe this is a special case?

**Comment by elonen** [comment]
Or perhaps just a repeatable command line option? With a config file you'd realistically have to provide a cli option to tell where it is anyway.

**Comment by ritchieGitHub** [comment]
I think we should not use a cli option. The simplest thing would be a file in the classpath that way the same method can be used for the embeded case.

**Comment by darkbasic** [comment]
+1

**Comment by synapticloop** [comment]
I like the pattern that we first check for a file in the classpath/root directory of the jar called 'mimetypes.properties' which will be loaded first if it exists, else just load the default mimetypes from the source... (this is what I implemented in routemaster

**Comment by elonen** [comment]
Ok, let's properties file then. @synapticloop , do you have an implementation we could merge?
