### ISSUE TITLE
sendto failed: ECONNRESET (Connection reset by peer)

### ISSUE THREAD

**Issue by almasif** [NanoHttpd/nanohttpd#205]
Hi
I found this strange working on Android 4.4
When I would like to serve a video file I get an exception:
 
webserver.NanoHTTPD﹕ Could not send response to the client
    java.net.SocketException: sendto failed: ECONNRESET (Connection reset by peer)

in NanoHTTPD.Response sendBody function. It can't write to outputstream because client closes the socket.  Can it be fixed in NanoHttpd?

**Comment by jan4984** [comment]
I am facing the same problem, how to fix it.
