### ISSUE TITLE
Add support for PATCH HTTP Verb

### ISSUE THREAD

**Issue by marcote** [NanoHttpd/nanohttpd#208]
Hi there,

I was doing some small tests using the library, and while I was doing some PATCH requests, I realized there is no support for them. 
Could you consider adding support for PATCH ?

Thanks!

**Comment by elonen** [comment]
You can use any method you like with NanoHTTPD by implementing a suitable serve() - even nonstandard verbs if you really want. There's just no built-in code for that as it can't really know what you'd like to patch and how.

**Comment by elonen** [comment]
Oh! Actually there now seems to be a validation with `Method.lookup()`. I don't think that't really useful, probably better to just remove the whole check...

**Comment by elonen** [comment]
Ok, left the check in place, might have broken someone's code otherwise.

**Comment by marcote** [comment]
Thank you man!!!
