### ISSUE TITLE
ssl connection fail  for safari and android browser

### ISSUE THREAD

**Issue by stereo720712** [NanoHttpd/nanohttpd#209]
try establish a https server in android for other phones to connect,but only iphone6 sometimes can connected , ipod ,android browser all failed to get the webserver content. (the browser message is fail to establish safe connect) I use nanohttpd's simpleServer Class to establish it.

my CA is here

http://www.mediafire.com/download/53f6e9uveb47kqv/ca.cer // for client to download

http://www.mediafire.com/download/v9i58n38yb85co5/server.p12 //for server to load keystore

CA password both are singuler

Here is my sslServerSocket Code

    char[]kspass = KEYSTOREPASS.toCharArray();
    char[]ctpass = KEYSTOREPASS.toCharArray();
    try {

        KeyStore ks = KeyStore.getInstance("PKCS12");
        //ks.load(new FileInputStream("file:///android_asset/singuler.keystore"),kspass);
        ks.load(getResources().getAssets().open("server.p12"),kspass);

        KeyManagerFactory kmf = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
        kmf.init(ks, ctpass);
        TrustManagerFactory tmFactory = TrustManagerFactory.getInstance("X509");
        SSLContext sc = SSLContext.getInstance("TLS");
        sc.init(kmf.getKeyManagers(), null, null);

        //webServer.makeSecure(NanoHTTPD.makeSSLSocketFactory(ks, kmf.getKeyManagers()));
        webServerSSL.makeSecure(sc.getServerSocketFactory());

    } catch (Exception e) {
        // TODO: handle exceptionser
        Log.i("test", e.toString());
    }

    try {
        webServer.start(15);
        webServerSSL.start(15);
    } catch (IOException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
        webServer = null;
        webServerSSL=null;
        Log.i("test", e.toString());

**Comment by rbrtwng** [comment]
I'm not an android developer.... :( Just try to see if 2 cents can be added. 
I run your sslServerSocket code on CentOS (don't have an android) with java 1.7.0_75 and then accessed the server from my iPad and it worked fine (you need to confirm the exception that self-signed certificate is being used).

I think if applicable, you may try to enable SSL debug to track down the issue. Just start your JVM with -Djavax.net.debug=all argument. Then, try both the non-working (most mobile browsers) and the working (sometimes iPhone6) cases to see the actual SSL error reported behind scene. 

The SSL debug goes to stdOut and looks like:

####
NanoHttpd Request Processor (#1), READ: TLSv1 Handshake, length = 211
*** ClientHello, TLSv1.2
RandomCookie:  GMT: 1420323002 bytes = { 5, 56, 188, 103, 206, 82, 181, 233, 241, 7, 188, 110, 119, 58, 41, 238, 127, 103, 172, 216, 177, 242, 243, 20, 159, 21, 157, 121 }
Session ID:  {85, 168, 104, 28, 225, 163, 224, 209, 205, 237, 25, 41, 155, 255, 64, 7, 70, 204, 36, 10, 196, 198, 157, 102, 155, 106, 249, 37, 171, 132, 11, 122}
Cipher Suites: [TLS_EMPTY_RENEGOTIATION_INFO_SCSV, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_ECDSA_WITH_RC4_128_SHA, TLS_ECDHE_RSA_WITH_RC4_128_SHA, TLS_ECDH_ECDSA_WITH_RC4_128_SHA, TLS_ECDH_RSA_WITH_RC4_128_SHA, SSL_RSA_WITH_RC4_128_SHA, SSL_RSA_WITH_RC4_128_MD5]
Compression Methods:  { 0 }
Extension server_name, server_name: [host_name: 192.168.1.204]
Extension elliptic_curves, curve names: {secp256r1, secp384r1, secp521r1}
Extension ec_point_formats, formats: [uncompressed]
Extension signature_algorithms, signature_algorithms: SHA384withRSA, SHA256withRSA, SHA1withRSA, SHA256withECDSA, SHA1withECDSA
Unsupported extension type_13172, data: 
***
[read] MD5 and SHA1 hashes:  len = 211
####

A wild guess is the variety of your browser may not have logarithm or cipher overlap with the server side. 

Thanks.

**Comment by stereo720712** [comment]
thank you ,rbrtwng , i have re created the ca file , but still the same , chrome can view the webserver in pc , safari can not .
the above is the error message
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): Could not send response to the client
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): java.net.SocketException: Socket closed
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at libcore.io.Posix.sendtoBytes(Native Method)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at libcore.io.Posix.sendto(Posix.java:147)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:177)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at libcore.io.IoBridge.sendto(IoBridge.java:466)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at java.net.PlainSocketImpl.write(PlainSocketImpl.java:507)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:269)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at nandhttpd.NanoHTTPD$Response.sendBody(NanoHTTPD.java:1387)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at nandhttpd.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1360)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at nandhttpd.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1351)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at nandhttpd.NanoHTTPD$Response.send(NanoHTTPD.java:1336)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at nandhttpd.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:789)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at nandhttpd.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:187)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at java.lang.Thread.run(Thread.java:856)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): Could not send response to the client
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): java.net.SocketException: Socket closed
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at libcore.io.Posix.sendtoBytes(Native Method)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at libcore.io.Posix.sendto(Posix.java:147)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:177)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at libcore.io.IoBridge.sendto(IoBridge.java:466)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at java.net.PlainSocketImpl.write(PlainSocketImpl.java:507)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:269)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at nandhttpd.NanoHTTPD$Response.sendBody(NanoHTTPD.java:1387)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at nandhttpd.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1360)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at nandhttpd.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1351)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at nandhttpd.NanoHTTPD$Response.send(NanoHTTPD.java:1336)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at nandhttpd.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:789)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at nandhttpd.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:187)
07-17 11:08:22.068: E/nandhttpd.NanoHTTPD(7753): 	at java.lang.Thread.run(Thread.java:856)

**Comment by stereo720712** [comment]
in nanohttpd core ,start function i add this,
 if (this.sslServerSocketFactory != null) {
            SSLServerSocket ss = (SSLServerSocket) this.sslServerSocketFactory.createServerSocket();
            ss.setEnabledProtocols(new String [] { "TLSv1", "TLSv1.1","SSLv3"});
            ss.setUseClientMode(false);
            ss.setWantClientAuth(false);
            ss.setNeedClientAuth(false);
            ss.setSoTimeout(timeout*1000);

**Comment by rbrtwng** [comment]
Will you please capture the javax.net.debug=all log? I'll also make the
same change to nanohttpd core to see how it behaves.

**Comment by stereo720712** [comment]
I found the answer , because of the https timeout need to set up,and I got wrong unit for timeout variable.
	try {
			webServer.start(6000);
			webServerSSL.start(10000);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			webServer = null;
			webServerSSL=null;
			Log.i("test", e.toString());
		}
		
it can work now , thanks.

**Comment by ritchieGitHub** [comment]
ok, this is the first real confirmation for us that the ssl works as is on Andoid. We where waiting for that ;-) 

Just to be sure! Did it work as is or did you have to change some code in nanohttpd to get it working?

**Comment by ritchieGitHub** [comment]
@stereo720712 could you please elaborate what you did to get it to work, or did it work out of the box with just the wrong time-out?

**Comment by ritchieGitHub** [comment]
@elonen when we get the confirmation that the ssl works on android I think we could cut a release? What do you think?

**Comment by elonen** [comment]
Yes, definitely!
*puts the champagne in the ice*

A concrete walkthrough of how to setup ssl in the readme would be nice btw.
I suspect HTTP backed REST server is going to be pretty popular use case.

Anyone willing to document all the necessary shell commands required to get
from git clone to a running https server?

**Comment by stereo720712** [comment]
Dear ritchie :
    
                 For start when I use it , I did not set timeout, for http, it's ok. but https fail at iphone and android,success at PC. 
                 Finally , I  Found the timeout in this code:
                      try {
                    final Socket finalAccept = NanoHTTPD.this.myServerSocket.accept();
                    if (this.timeout > 0) {
                        finalAccept.setSoTimeout(this.timeout);
                    }
                    in serverRunnable, and it's initial at start function,
                    I set 10 seconds to https and work well.
                    tested : android 4.4 , android 4.1.2 , android 4.2 and I use server to distribute ios app
                   success (https server)

**Comment by stereo720712** [comment]
about key manager i use p12
KeyStore ks = KeyStore.getInstance("PKCS12");
			//ks.load(new FileInputStream("file:///android_asset/singuler.keystore"),kspass);
			ks.load(getResources().getAssets().open("server.p12"),kspass);
		
			KeyManagerFactory kmf = KeyManagerFactory.getInstance("X509");
			kmf.init(ks, ctpass);
			TrustManagerFactory tmFactory = TrustManagerFactory.getInstance("X509");
			tmFactory.init(ks); //add trustFactory
			SSLContext sc = SSLContext.getInstance("TLS");
			
			sc.init(kmf.getKeyManagers(), tmFactory.getTrustManagers(), null);

in start functon
     public void start(final int timeout) throws IOException {
        if (this.sslServerSocketFactory != null) {
            SSLServerSocket ss = (SSLServerSocket) this.sslServerSocketFactory.createServerSocket();
            ss.setEnabledProtocols(new String [] { "TLSv1", "TLSv1.1","SSLv3"}); //add
            ss.setUseClientMode(false);//add
            ss.setWantClientAuth(false);//add
            ss.setNeedClientAuth(false);//add

**Comment by stereo720712** [comment]
@ritchieGitHub
I found for timeout problem for some event :
1. when use iphone6 sometimes safari will success, but almost all failed to connect,and android all fail
(i don't know why adnroid all fail).
2. When i try to connet the https server, socket event not established,finally(no interrupt for debugger), i find my timeout only set 0.15 seconds ,when i changed it , it succeed.

**Comment by thanthos** [comment]
For test purpose, I used this 3 methods to create the self sign cert for a new keystore. It should work regardless of it being run on a PC or Android. I tested it on the Android API 15 and API 21. You may have to modify it at a few key areas for customization. PS: There is dependency on the bouncy castle library so download that when you used it. I also discovered that if you leave the CN to the default when you create the cert or the keypair using keytool, SSL cannot be established. Anyone with mastery over the OPENSSL managed to dig the answer out? 


        private void initSSLConfig() throws NoSuchProviderException, NoSuchAlgorithmException, KeyStoreException, IOException, CertificateException, SignatureException, InvalidKeyException, UnrecoverableKeyException {
        String defaultKSType = KeyStore.getDefaultType();
        KeyStore ks = KeyStore.getInstance(defaultKSType);

        File defaultFile = "/tmp/.keystore"; //<---------------- Change here
        File keyStoreFile = new File(defaultFile, "nano.keystore");

        KeyManagerFactory kmf = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());

        //If Keystore Exist
        if ( keyStoreFile.exists()){
            ks.load(new FileInputStream(keyStoreFile), DEFAULT_PASSWORD.toCharArray());
            kmf.init(ks, DEFAULT_PASSWORD.toCharArray());
            KeyManager[] managers = kmf.getKeyManagers();
            SSLServerSocketFactory sslsf = makeSSLSocketFactory(ks, kmf.getKeyManagers());
            makeSecure(sslsf);
        }else{
        //Initialized it again and insert a cert.
            ks.load(null);
            KeyPair keypair = generateRSAKeyPair(null);
            Certificate c = generateV3Certificate(keypair);
            ks.setKeyEntry("nanoKey", keypair.getPrivate(), DEFAULT_PASSWORD.toCharArray(), new Certificate[]{c});
            ks.setCertificateEntry("nano", c);
            ks.store(new FileOutputStream(keyStoreFile), DEFAULT_PASSWORD.toCharArray());
            kmf.init(ks, DEFAULT_PASSWORD.toCharArray());
            KeyManager[] managers = kmf.getKeyManagers();
            SSLServerSocketFactory sslsf = makeSSLSocketFactory(ks, kmf.getKeyManagers());
            makeSecure(sslsf);
        }
    }

    public static X509Certificate generateV3Certificate(KeyPair pair) throws InvalidKeyException, NoSuchProviderException, SignatureException {
        Security.addProvider(new org.bouncycastle.jce.provider.BouncyCastleProvider());
        X509V3CertificateGenerator certGen = new X509V3CertificateGenerator();
        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.YEAR, 1);
        certGen.setSerialNumber(BigInteger.valueOf(System.currentTimeMillis()));
        certGen.setIssuerDN(new X500Principal("CN=nano"));
        certGen.setNotBefore(new Date(System.currentTimeMillis() - 10000));
        certGen.setNotAfter(cal.getTime());
        certGen.setSubjectDN(new X500Principal("CN=nano"));
        certGen.setPublicKey(pair.getPublic());
        certGen.setSignatureAlgorithm("SHA256WithRSAEncryption");
        //certGen.addExtension(X509Extensions.BasicConstraints, true, new BasicConstraints(false));
        //certGen.addExtension(X509Extensions.KeyUsage, true, new KeyUsage(KeyUsage.digitalSignature | KeyUsage.keyEncipherment));
        //certGen.addExtension(X509Extensions.ExtendedKeyUsage, true, new ExtendedKeyUsage(
        //        KeyPurposeId.id_kp_serverAuth));

        //certGen.addExtension(X509Extensions.SubjectAlternativeName, false, new GeneralNames(
        // new GeneralName(GeneralName.rfc822Name, "test@test.test")));
        return certGen.generateX509Certificate(pair.getPrivate(), "BC");
    }

    public static KeyPair generateRSAKeyPair(String provider) throws NoSuchProviderException, NoSuchAlgorithmException {
        if ( provider != null ){
            KeyPairGenerator kpGen = KeyPairGenerator.getInstance("RSA", provider);
            kpGen.initialize(2048);
            return kpGen.generateKeyPair();
        }else{
            KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance("RSA");
            keyPairGenerator.initialize(2048);
            return keyPairGenerator.generateKeyPair();
        }
    }

**Comment by ravenchild** [comment]
Android blocks self signed certs by default. Are you trusting all certs for your socket?

**Comment by ritchieGitHub** [comment]
ok, I have included tests and the requested option in the sources. could you all please test it and reopen this issue if there is still something missing. (Would be great in a pull request with unit test, by just extend the existing tests)
