### ISSUE TITLE
Unnecessary dependencies

### ISSUE THREAD

**Issue by shumy** [NanoHttpd/nanohttpd#210]
Please remove org.mockito dependency from nanohttpd-websocket. This is not needed and adds unnecessary 1.5MB.
Also move samples.echo package to a test project.
NanoWebSocketServer is also not needed, normally the Web Server is reused, if not this is easily implemented.
Please make it NANO.

**Comment by ritchieGitHub** [comment]
the dependency should have been test scope that's done. the rest I would keep they are much used to test the infrastructure (the question is it my error or is it something else) 
@elonen what do you think

**Comment by shumy** [comment]
In my personal developments I put tests in a separate maven project, so that this wouldn't happen.
I think in this particular project it's important, because the main target is to keep it small. So you should always try to remove redundant code and unnecessary dependencies from the main packages.

**Comment by ritchieGitHub** [comment]
that we could do, make a websocket echo module @elonen  ok with you?

**Comment by elonen** [comment]
As long as it doesn't compromise unit testing for project developers, I'm
all for anything that reduces dependencies and file count for the users.

(Still don't know much about Maven and stuff so I'm not 100% sure what
you're talking about, but I know I've often cursed the amount of mostly
development related fluff and wrappings that come with many libraries
nowadays, regardless of language used.)

**Comment by ritchieGitHub** [comment]
I think I know a good solution, I will attach an extra (startable) jar to this artefact that contains the echoserver. and move the echo server to the test sources. That way the unit test's/ and code coverage do not suffer, and the echo server can be used as a separate jar. Hope to do that tomorrow.

**Comment by ritchieGitHub** [comment]
done, the normal jar doe not include the echo server anymore  the classifier jar (echo) includes the echo server.
