### ISSUE TITLE
NanoHTTPD newXXXLengthResponse methods

### ISSUE THREAD

**Issue by OldNavi** [NanoHttpd/nanohttpd#213]
Is is possbile to make methods such as

public Response newFixedLengthResponse(IStatus status,
                                                  String mimeType, InputStream data, long totalBytes) {
        return new Response(status, mimeType, data, totalBytes);
    }

class static ? Is it a specific requirement to have them class instance wide only as having them only instance wide - limits it's usability in custom written class not inherited from NanoHTTPD class.

**Comment by elonen** [comment]
If NanoHTTPD compiles with the `static` keywords added, I don't see why not.
Are you currently having a concrete use case where this is a problem and
have you tried changing the factory functions to static?

**Comment by OldNavi** [comment]
yes, i made them static for my case and it's working fine... The usage scenario in my case is the following - i'm using separate java classes which behaves like a servlets (the have a methods which take IHTTPSession params and returns Response object). They are instantiated at startup time and checked for concrete URL in overridden serve() method. They are a bit lightweighted and i didn't want to inherit them from NanoHTTPD class just for getting ability to create a response class.

**Comment by elonen** [comment]
Interesting. Changing them to static might make someone's code break, but on the other hand, it's very easy to fix and the factory functions have only been in *master* for a short time. What do you think @ritchieGitHub ?

**Comment by ritchieGitHub** [comment]
static methods are signs for bad design. In this case I would subclass nanohttpd and provided it behind an interface to the 'servlets'

**Comment by OldNavi** [comment]
Well, i was using a bit old version of nanohttpd when  Response class was public one. As your project evolved - you made a big refactoring and made it protected and that of course broke my code. Tried to move to the latest master i got an  issue that i can't fix my code without deep refactoring. Surely I won't mark all static methods as bad design, if we aren't expecting any exceptions in a static method, why not. Actually i don't understand what is a point to have a methods of the class which doesn't actually work with any instance vars (just instantiating yet another decoupled class)  to be just instance wide. Of course this is a matter of taste.

**Comment by ritchieGitHub** [comment]
Don't forget that we included ~50 pull requests and some major features like ssl, that is why the api changed so much. This method was intended to be overwritten by subclasses, to adapt it to the needs of the subclass. We could provide an extra mehod that is static and call that from the protected instance method. That would provide both req.

**Comment by OldNavi** [comment]
I understand and want to say a big thank you for all your efforts guys. A wrapper static method could be a solution for myself, that's for sure.  Perhaps as an idea - would it be possible for example to go with a way when iHTTPSession can have a method to instantiate a Response class ? In that case we might avoid static methods at all.

**Comment by elonen** [comment]
I think the main question is: if they currently don't use any instantiated variables, are there any foreseeable advantages from keeping the factory functions non-static, or disadvantages from making them static? After all, static factory functions are a well-known design pattern (and in our case, definitely better than standard constructors with new booleans).

**Comment by ritchieGitHub** [comment]
static factory is used to hide implementation from interfaces, not the reason here. here is just an easy entry for the subclass to change the behavior if needed. So better to provide both, just my 2 cent ;-)

**Comment by elonen** [comment]
That's true of course. Do you have some scenarios in mind where overriding them would be very useful? I have to admit I actually never thought of them as likely candidates for overriding, since implementation hiding (or in this case rather, keeping the main constructors lean) seems to be their main point at the moment. I mean, skimming through the code, only SimpleWebrver.java in our repository currently appears to override `newFixedLengthResponse()`, and it only adds a `Accept-Ranges` header, which I believe could as well be added in `serve()`.

**Comment by ritchieGitHub** [comment]
it was done in context of a user request to get more control of the reponse class and it's behavior, I do not remember the concrete issue :-( but as far as I remember the user wanted to use a subclass of the response.
