### ISSUE TITLE
NanoHTTPD uri router

### ISSUE THREAD

**Issue by vnnv** [NanoHttpd/nanohttpd#214]
Hi guys, 
Is there any plan to add simple routing mechanism in NanoHTTPD. 
Something as server.add("/user/:id", SomeClass.class); 
SomeClass can have methods get(), post, put, etc. and these methods can get Map<String, String> urlParams with all other things coming from IHTTPSession. 

I can try to implement such functionality.

**Comment by elonen** [comment]
No plans for now. Since NanoHTTPD is a generic HTTP server library instead of an application server, routing would be difficult to make generic enough. That said, it should be quite easy to implement a custom one by subclassing and overriding `serve()`. If you manage to write a small but functional implementation, we'd be happy to include one to samples/.

**Comment by vnnv** [comment]
Ok, anyway I have to write it so I can use this cute project to serve some rest services in Android. Let's see what will emerge from that :) for the samples/ folder.

**Comment by vnnv** [comment]
What will be the best approach for this sample? Should I make a fork, put the new java files in samples/ and make push request?

**Comment by ritchieGitHub** [comment]
that would be great!

**Comment by vnnv** [comment]
Pull request created :)

**Comment by ritchieGitHub** [comment]
ok, I will take a look this weekend. maybe this is worth a own module when we reduce it to one class ;-)

**Comment by vnnv** [comment]
Yes it can be reduced to a single class, but because is in samples I kept the classes separate to be more readable.Of course if a new modules is created... a single class is better :)

**Comment by thanthos** [comment]
I had an idea and I gave some thoughts about it and came out with the below. By extending the NanoHTTP and providing these 2 methods. This approach will adopt the nodejs and express approach on handling incoming request. The first "Router" that has a match URI (AKA url path) and return a response will have its results served. This should effectively decoupled the serving of content and server itself. Further more we can create specialized router class to handle the request uniquely. For example respond in JSON rather than text/html, serve up static content, perform accesslogs functionality etc

    void loadRouters() {
        String[] routerArrayClasses = applicationContext.getResources().getStringArray(R.array.router);
        for (String inst : routerArrayClasses) {
            try {
                Routers r = (Routers) Class.forName(inst).newInstance();
                r.setContext(this.applicationContext);
                this.routerArray.add(r);
            } catch (ClassNotFoundException cnfe) {
                Log.w(TAG, "Unable to Instantiate " + inst);
            } catch (InstantiationException ie) {
                Log.w(TAG, "Unable to Instantiate " + inst);
            } catch (IllegalAccessException iae) {
                Log.w(TAG, "Unable to Instantiate " + inst);
            }
        }
        Log.i(TAG, "Router Count: " + this.routerArray.size());
    }

    @Override
    /**
     * Adopt the NODE Express Routing approach to handling request.
     * Default behavior is to return a not found.
     */
    public Response serve(IHTTPSession session) {
        Method method = session.getMethod();
        Response res = null;
        try {
            for (Routers r : routerArray) {
                Log.v(TAG, "Class " + r.getClass().getName());
                switch (method) {
                    case GET:
                        res = r.doGet(session);
                        break;
                    case PUT:
                        res = r.doPut(session);
                        break;
                    case POST:
                        res = r.doPost(session);
                        break;
                    case DELETE:
                        res = r.doDelete(session);
                        break;
                    case HEAD:
                        res = r.doHead(session);
                        break;
                    case OPTIONS:
                        res = r.doOptions(session);
                        break;
                    case TRACE:
                        res = r.doTrace(session);
                        break;
                    case CONNECT:
                        res = r.doConnect(session);
                        break;
                    case PATCH:
                        res = r.doPatch(session);
                        break;
                    default:
                        res = r.doGet(session);
                }
                if (res != null) return res;
            }
        } catch (Exception e) {
            Log.e(TAG, "", e);
            return new ServerError().doGet(session);
        }
        return new NotFound().doGet(session);
    }

**Comment by vnnv** [comment]
The pull request I submitted is inspired of Node.js too. It is slightly different but the idea is the same. You can check the code.

**Comment by ritchieGitHub** [comment]
sorry that it takes that long, I have some "urgent" other projects ... @elonen  I think the sample is worth making a module and maybe name them "nanolets" ?

**Comment by thanthos** [comment]
@Vnnv also mentioned he/she was inspired by the Nodejs, Express approach. I was similarly inspired. So I feel it might be appropriate to pay tribute to it somehow. Once it is incorporated I hope all that is required to provide a more comprehsive server solution is to configure the mapping and implement the handler. 

 ===================================
To live is to grow. To grow is to Learn. 
===================================

**Comment by synapticloop** [comment]
I have created a routable nanohttpd: https://github.com/synapticloop/routemaster

**Comment by ritchieGitHub** [comment]
pull requests included and adapted to one class with a more compact logic.
