### ISSUE TITLE
latest maven version?

### ISSUE THREAD

**Issue by dahliamalkhi** [NanoHttpd/nanohttpd#221]
visiting 'http://search.maven.org/#artifactdetails|com.nanohttpd|nanohttpd-project|2.1.1|pom' gives an empty download list, hence maven auto-download fails. querying http://nanohttpd.org for latest version seems down. any ideas for automatic downloading ?

**Comment by spyhunter99** [comment]
strange, it worked a few weeks ago. looks like it's removed from central.

**Comment by ritchieGitHub** [comment]
no everything ok, seems central had a hickup ;-)

**Comment by ritchieGitHub** [comment]
so and  http://nanohttpd.org  is also online again, my provider restarted it a bit harsh..
