### ISSUE TITLE
Gradle support

### ISSUE THREAD

**Issue by erf** [NanoHttpd/nanohttpd#222]
Is it possible to add nanohttpd as a gradle dependency to Android Studio?

**Comment by spyhunter99** [comment]
of course it is. Just add it as a compile dependency. As per the gradle docs
https://docs.gradle.org/current/userguide/artifact_dependencies_tutorial.html


dependencies {
    compile 'com.nanohttpd:nanohttpd-webserver:2.1.1'

}

more info is here https://github.com/NanoHttpd/nanohttpd/issues/44

group id's will change on the next version

**Comment by erf** [comment]
Ah, nice. Thanks. I'm quite new to gradle, but maybe you should add the gradle dependency information to README.md ?

**Comment by elonen** [comment]
Related to #34

**Comment by ritchieGitHub** [comment]
Lets keep this one open till "someone" writes the  gradle dependency variants into the README ;-) 

If someone with gradle know-how reads this, please take your time and make a pull request with an appropriate addition to the README

**Comment by ritchieGitHub** [comment]
added a description to the site

**Comment by BjoernAkAManf** [comment]
While gradle can use maven central, it does not do so without prior specification: 
````
repositories {
    mavenCentral()
}
````

**Comment by spyhunter99** [comment]
jCenter is suppose to be a superset of mavenCentral. Not sure why this is even an issue.

**Comment by ritchieGitHub** [comment]
could you try if
    repositories {
       mavenCentral()
    }
is nessesary?

**Comment by brnunes** [comment]
```
repositories {
    mavenCentral()
}
```

is not necessary.

**Comment by ritchieGitHub** [comment]
good, than I close this issue!
