### ISSUE TITLE
documentation error: non-daemon required 

### ISSUE THREAD

**Issue by kritzikratzi** [NanoHttpd/nanohttpd#224]
the example on the main github page doesn't work for me, because nanohttpd will start in daemon mode. there are no further threads, and the vm will exit as quick as it started. 

        start();

should be replaced with 

        start(NanoHTTPD.SOCKET_READ_TIMEOUT, false);

**Comment by kritzikratzi** [comment]
mac os x 10.9.

**Comment by elonen** [comment]
O, that's pretty odd. I'm running OSX myself. Just to clarify: the server
starts but immediately exists if you run the example commands??

**Comment by rgcosma** [comment]
Similar for me, Centos7, Oracle JDK8. 
The sample mvn exec:java waits for a single request, answers then exists
After building with mvn assembly:simple, java -jar exists immediately without waiting for a request.
With kritzikratzi's suggestion it works as expected.

**Comment by kritzikratzi** [comment]
this behavior is basically the definiton of a daemon thread (a daemon thread that doesn't stop the jvm from exiting). 

i made a minimal example: 

	public class Test implements Runnable{
	
		public static void main( String args[] ){
			Thread t = new Thread(new Test()); 
			//enable this line, and the jvm will exit again immediately 
			//t.setDaemon(true); 
			t.start(); 
		}
	
		public void run(){
			int seconds = 0; 
			while( true ){
				try{
					seconds ++; 
					System.out.println( "Running since " + seconds + " seconds" ); 
					Thread.sleep( 1000 ); 
				}
				catch( InterruptedException e ){
					e.printStackTrace(); 
				}
			}
		}
	}


when i run with `setDaemon(false)` it keeps running forever, 
when i run with `setDaemon(true)` it exits immediately, never printing a single line.
