### ISSUE TITLE
NanoHTTPD.serve() called multiple times in the same session

### ISSUE THREAD

**Issue by matthieu-labas** [NanoHttpd/nanohttpd#225]
In `ClientHandler.run()` (line 167), the `session.execute()` is run while the `acceptSocket` is opened (`while (!this.acceptSocket.isClosed())`), which calls `serve()` twice on my computer with Firefox 40.0.3 or Internet Explorer 11.

What is the need for this `while()` loop? The request processing can be something which should not be executed several times (e.g. database inserts, heavy server computation, ...). Moreover, the `acceptSocket` being closed by the client, we cannot know for sure *when* it will decide to close it. It might as well keep it open (clumsy implementation) which would lead to infinite looping.

It seems calling `Response.addHeader("connection", "close")` before returning the `Response` should trigger a `SocketException("NanoHttpd Shutdown")` which would break out of the `while()` loop.
In that case however, Firefox seems to restart a new connection right after (`accept()` returns a new socket in `ServerRunnable.run()` (line 1475)), while Internet Explorer doesn't ... usually.

**Comment by elonen** [comment]
The while loop is there to implement HTTP keep-alive. I.e. a client can issue multiple HTTP requests over the same TCP connection. As you point out, if the client sets header "connection: close" (or doesn't support HTTP 1.1 for example), the server closes the socket right after serving the request.

**Comment by matthieu-labas** [comment]
Thank you for the clarification :+1: After re-reading the code there is nothing in the read loop that would pass several times the same request. It seems to only happen when testing with NanoHttpd and browser running on the same computer.

**Comment by richthofen911** [comment]
Hi, I start the server on my phone and use a desktop chrome to access the server with one parameter, the serve(IHTTPSession session) method is called twice while the second time is not wanted. Can I get any help? thanx

**Comment by matthieu-labas** [comment]
@richthofen911 i you're "lucky" to witness this problem on two separate machines, can you check the network traffic going out of your Chrome to your phone with a tool like Wireshark or tcpdump? I wanted to do that but it cannot capture traffic on localhost interface.

**Comment by richthofen911** [comment]
@matthieu-labas Hi, after a little bit more diving in the code, I found this appears beacuse the browser keep the connection alive. like elonen mentioned, " if the client sets header "connection: close" (or doesn't support HTTP 1.1 for example), the server closes the socket right after serving the request.", he tells the truth. So technically is not a bug and has nothing to do with network traffic issue. But the fact is, I should not mannually let my browser set the header "connection" as close, so there should be something handle the situation, such as adding a timer or something.

**Comment by matthieu-labas** [comment]
@richthofen911, @elonen still I don't understand why we read twice the same request...

The socket can stay open but once data have been read (the first request), another read would block or timeout until a new request is sent *by the browser*. It should not be getting the same data unless the browser has sent the same request a second time.

I wanted to check if the browser would actually send several times the same request (we would see it in tcpdump) or only one (and then the problem is in Java or NanoHTTPD).

**Comment by matthieu-labas** [comment]
I have tested NanoHTTPD running on my Windows 7 x64 with the following clients:
* Local Firefox => two
* Local IE11 => one (+ socket write exception sometimes, see #249?)
* Virtual Machine Windows XP Firefox or IE7 => one
* Remote Windows 7 x64 Firefox => two (**confirmed by Wireshark**)
* Remote IE11 => one

So it seems related to the browser.

Note that it happens only on some URL, when I'm sending back `image/jpeg` content.

**Comment by ritchieGitHub** [comment]
Can it be that we land in a situation where the browser thinks the request failed and tries the request again? could you check if the jpeg you use has a legal ending and the ending is visible in Wireshark .

I get the suspicion here that the reason for this and #249 is that we do something wrong, that lets the browser retry the request.

**Comment by LordFokas** [comment]
#249 wasn't related to this. There was iffy JS code on the client and the server was silently discarding exceptions in onOpen(). No multiple requests were being sent, the only real problem with Nano there was the exceptions being discarded.

**Comment by ritchieGitHub** [comment]
Good, that exception is now logged on level SEVERE

**Comment by Kshitij-Banerjee** [comment]
I can still see this behavior happening as of the latest build.  (2.3.1). 
Is there a fix that closes this?

**Comment by matthieu-labas** [comment]
@Kshitij-Banerjee the problem comes from the browser; not the server.
