### ISSUE TITLE
Simplify request handling code

### ISSUE THREAD

**Issue by psh** [NanoHttpd/nanohttpd#23]
The change to write the incoming request to file, and map that into memory (using ```ByteBuffer```) introduces a new opportunity - continue the refactoring to remove the ```BufferedReader``` that we attach back on  that file, and switch to reading from the ``ByteBuffer``` directly.  Currently the code looks a little odd as it drops between both schemes.

Note: The profiling the application it was obvious that there's a speedup to be had as multipart boundaries are traversed.  Instead of reading line by line and throwing the data away, try skipping a number of bytes in a single ```seek()``` call!

**Comment by elonen** [comment]
Also, the `in.readLine()` calls in `decodeMultipartData` could conceivably lead to memory exhaustion if a multipart post request is malformed.
