### ISSUE TITLE
websocket "onOpen" 

### ISSUE THREAD

**Issue by PathikDevani** [NanoHttpd/nanohttpd#231]
in websocket where is "onOpen" method? callback when connection establish.

**Comment by LordFokas** [comment]
Well, since my last PR ( #246 ) was accepted, WebSockets now have an `onOpen()` method.
Also notice how event methods are now on the WebSocket class and not on the server :)

@ritchieGitHub you can close this now :p

**Comment by ritchieGitHub** [comment]
thanks!
