### ISSUE TITLE
Multiple identical param-keys: Not possible due to Java-Map for params ...

### ISSUE THREAD

**Issue by tuxedo0801** [NanoHttpd/nanohttpd#235]
Hi there,

really great tool. but I'm facing the following issue:

I have to process requests like this:

GET /kad/r?s=ce240dbd-0990-45c5-922c-e9cd3c63becf&a=3/1/100&a=3/1/110&a=3/1/130&t=0

Problem is: I have multiple params with name "a" ... The current nanohttpd implementation makes use of Java Hashmap to store the params. But this does not allow multiple params with same name... *argh*

I'm currently investigating how to solve this easily and without big code overhead.
Any ideas?

**Comment by tuxedo0801** [comment]
Ah, I see.. this was alsready fixed in latest snapshot. Latest version in maven central does not have this fix.
Is there somewhere a public maven repo containing the latest (snapshot) version or do i really have to build on my own?

**Comment by tuxedo0801** [comment]
*Argh* Seems I see ghost-code ... There is no multi-identical param support yet, or?

**Comment by tuxedo0801** [comment]
Looks like NanoHTTPD#protected static Map<String, List<String>> decodeParameters(Map<String, String> parms) is what I'm looking for...

**Comment by ritchieGitHub** [comment]
public snapshots at: https://oss.sonatype.org/content/repositories/snapshots
thanks for solving the problem yourself
