### ISSUE TITLE
safeClose() in NanoHTTPD: unnecessary?

### ISSUE THREAD

**Issue by Hoeze** [NanoHttpd/nanohttpd#237]
if (closeable instanceof Closeable) {
                    ((Closeable) closeable).close();
} else if (closeable instanceof Socket) {
                    ((Socket) closeable).close();
} else if (closeable instanceof ServerSocket) {
                    ((ServerSocket) closeable).close();
}

Since Socket and ServerSocket implement Closeable, won't they always get caught with the first if statement?

**Comment by justparking** [comment]
I think I can answer this. In some older versions of Android, `java.net.Socket` and `java.net.ServerSocket` turned out not to be `Closable` even though their documentation said otherwise.

See https://code.google.com/p/android/issues/detail?id=62909

**Comment by Hoeze** [comment]
Aah, ok. Thats not nice ^^
