### ISSUE TITLE
report an important bug

### ISSUE THREAD

**Issue by onexuan** [NanoHttpd/nanohttpd#240]
I am testing nanohttpd, when I upload a png, upload successfully.
My png pic is 3,204 byte, but the save file is only 3181 byte. missing byte
Please fix it. this is a important bug.

**Comment by ritchieGitHub** [comment]
could you please provide a unit test (in a pull request)? that will help a lot.

**Comment by onexuan** [comment]
Here is my some code

Map<String, String> files = new HashMap<String, String>();
				try {
					session.parseBody(files);
					String filename, tmpFilePath;
					File src = null;
					File dst = null;
					for (Entry<String, String> entry : parms.entrySet()) {
						if (entry.getKey().toString().substring(0, 7)
								.contains("apkfile")) {
							filename = entry.getValue().toString();
							tmpFilePath = files.get(entry.getKey().toString());
							Log.e("filename", "filename="+filename);
							Log.e("tmpFilePath", "tmpFilePath="+tmpFilePath);
							if(StorageUtil.isSupportSDCard()){
								dst = new File(rootFile, "temp.apk");
							}else{
								dst = new File(context.getCacheDir(), "temp.apk");
							}
							
							src = new File(tmpFilePath);
							if (copyFile(src, dst)) {
								Log.e("dst", "dst="+dst.getPath());
								
							}
							//dst.delete();
						}
					}
					
					
				} catch (Exception re) {
					return newFixedLengthResponse(Status.OK, NanoHTTPD.MIME_PLAINTEXT, context.getString(R.string.failure));
				}
				return newFixedLengthResponse(Status.OK, NanoHTTPD.MIME_PLAINTEXT, context.getString(R.string.success));

Upload file

<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta content="IE=edge" http-equiv="X-UA-Compatible">
	<meta content="initial-scale=1.0, width=device-width" name="viewport">
	<title>%s</title>
	<script type="text/javascript" src="js/jquery.min.js"></script>
	<link href="css/style.css" rel="stylesheet">
</head>

<body class="noninitial-chapter">
<header>
<div class="header-wrapper">
    <div class="header-title">      <span class="section-title">%s</span>
    </div>
  </div>
</header>

<div class="container">
<div class="card-wrap">
<div class="row">
<div class="card col"><div class="card-main"><div class="card-inner" id="drop_area"><p class="card-heading">Test</p><div id="preview">Test</div></div><div class="card-action"><div class="card-action-btn pull-left"></div></div></div></div>
</div>
</div>
</div>

<script type="text/javascript">
$(function(){
	//阻止浏览器默认行。
	$(document).on({
		dragleave:function(e){		//拖离
			e.preventDefault();
		},
		drop:function(e){			//拖后放
			e.preventDefault();
		},
		dragenter:function(e){		//拖进
			e.preventDefault();
		},
		dragover:function(e){		//拖来拖去
			e.preventDefault();
		}
	});
	
	//================上传的实现
	var box = document.getElementById('drop_area'); //拖拽区域
		
	box.addEventListener("drop",function(e){
		e.preventDefault(); //取消默认浏览器拖拽效果
		var fileList =e.dataTransfer.files; // File list
		//检测是否是拖拽文件到页面的操作
		if(fileList.length == 0){
			return false;
		}
		//检测文件是不是图片
		if(fileList[0].name.toLowerCase().indexOf('apk') === -1){
			alert("This is not an apk!"+fileList[0].type);
			return false;
		}
		
		//拖拉图片到浏览器，可以实现预览功能
		var img = window.webkitURL.createObjectURL(fileList[0]);
		var filename = fileList[0].name; //图片名称
		var filesize = Math.floor((fileList[0].size)/1024); 
		var str = "Name："+filename+" Size："+filesize+"KB";
		$("#preview").html(str);
		
		//上传
		xhr = new XMLHttpRequest();
		xhr.open("post", "/appinstall", true);		
		xhr.onreadystatechange=function()
  {
  if(xhr.readyState === 4 && xhr.status === 200){
  document.getElementById("preview").innerHTML = xhr.responseText;
  }else{
  document.getElementById("preview").innerHTML = xhr.responseText;
  }
  };

		var fd = new FormData();
		fd.append('apkfile', fileList[0]);
			
		xhr.send(fd);
		
			
	},false);
});
</script>
</body>
</html>

Not only png miss byte, txt, apk also missing

**Comment by onexuan** [comment]
Hi
I tried to find the problem. I found a problem with the getBoundaryPositions function. 

Can It be fixed as soon as possible?

**Comment by ritchieGitHub** [comment]
this Friday I have time to fix that.

**Comment by elonen** [comment]
@onexuan : Can you provide more information on your findings (or perhaps a patch) to illustrate what the bug was exactly?

**Comment by onexuan** [comment]
I try to fix bug in my way today. the code is not standard but It work well now.
I add "headLength" to get the correct "part_data_start", 

```sh
private void decodeMultipartFormData(String boundary, ByteBuffer fbuf, Map<String, String> parms, Map<String, String> files) throws ResponseException {
            try {
                int[] boundary_idxs = getBoundaryPositions(fbuf, boundary.getBytes());
                if (boundary_idxs.length < 2) {
                    throw new ResponseException(Response.Status.BAD_REQUEST, "BAD REQUEST: Content type is multipart/form-data but contains less than two boundary strings.");
                }

                final int MAX_HEADER_SIZE = 1024;
                byte[] part_header_buff = new byte[MAX_HEADER_SIZE];
                for (int bi = 0; bi < boundary_idxs.length - 1; bi++) {
                    fbuf.position(boundary_idxs[bi]);
                    int len = (fbuf.remaining() < MAX_HEADER_SIZE) ? fbuf.remaining() : MAX_HEADER_SIZE;
                    fbuf.get(part_header_buff, 0, len);
                    ByteArrayInputStream bais = new ByteArrayInputStream(part_header_buff, 0, len);
                    BufferedReader in = new BufferedReader(new InputStreamReader(bais));

                    // First line is boundary string
                    int headLength = 0;
                    String mpline = in.readLine();
                    if(mpline!=null){
                    	headLength = headLength+mpline.length();
                    }
                    if (!mpline.contains(boundary)) {
                        throw new ResponseException(Response.Status.BAD_REQUEST, "BAD REQUEST: Content type is multipart/form-data but chunk does not start with boundary.");
                    }

                    String part_name = null, file_name = null, content_type = null;
                    // Parse the reset of the header lines
                    mpline = in.readLine();
                    if(mpline!=null){
                    	headLength = headLength+mpline.length();
                    }
                    while (!StringUtil.isEmpty(mpline) && mpline.trim().length() > 0) {
                        Matcher matcher = CONTENT_DISPOSITION_PATTERN.matcher(mpline);
                        if (matcher.matches()) {
                            String attributeString = matcher.group(2);
                            matcher = CONTENT_DISPOSITION_ATTRIBUTE_PATTERN.matcher(attributeString);
                            while (matcher.find()) {
                                String key = matcher.group(1);
                                if (key.equalsIgnoreCase("name")) {
                                    part_name = matcher.group(2);
                                } else if (key.equalsIgnoreCase("filename")) {
                                    file_name = matcher.group(2);
                                }
                            }
                        }
                        matcher = CONTENT_TYPE_PATTERN.matcher(mpline);
                        if (matcher.matches()) {
                            content_type = matcher.group(2).trim();
                        }
                        mpline = in.readLine();
                        if(mpline!=null){
                        	headLength = headLength+mpline.length();
                        }
                    }
                    // Read the part data
                    
                    int part_header_len = headLength;
                    
                    if (part_header_len <= 4) {
                        throw new ResponseException(Response.Status.INTERNAL_ERROR, "Multipart header size exceeds MAX_HEADER_SIZE.");
                    }
                    
                    int part_data_start = boundary_idxs[bi] + part_header_len+8;
                    int part_data_end = boundary_idxs[bi + 1] - 4;
                    fbuf.position(part_data_start);
                    if (content_type == null) {
                        // Read the part into a string
                        byte[] data_bytes = new byte[part_data_end - part_data_start];
                        fbuf.get(data_bytes);
                        parms.put(part_name, new String(data_bytes));
                    } else {
                        // Read it into a file
                        String path = saveTmpFile(fbuf, part_data_start, part_data_end - part_data_start, file_name);
                        if (!files.containsKey(part_name)) {
                            files.put(part_name, path);
                        } else {
                            int count = 2;
                            while (files.containsKey(part_name + count)) {
                                count++;
                            }
                            part_name = part_name + count;
                            files.put(part_name, path);
                        }
                        parms.put(part_name, file_name);
                    }
                }
            } catch (ResponseException re) {
                throw re;
            } catch (Exception e) {
                throw new ResponseException(Response.Status.INTERNAL_ERROR, e.toString());
            }
        }
```

**Comment by ritchieGitHub** [comment]
So the problem is the encoding of the request and using us-ascii the boundaries are read wrong? 
Yes, that's it. It will take a little longer to fix this in a general way. I hope I can fix this today but I am not sure.

**Comment by ritchieGitHub** [comment]
please test the current state, it will work better if not yet completely correct yet.

**Comment by onexuan** [comment]
@ritchieGitHub I have tested the latest code. I uploaded a png pic, but the saved png file is corrupted, I think it is not only encode problem I tested. You may have to test payload, "part_data_start" is error.

**Comment by onexuan** [comment]
```sh
------WebKitFormBoundaryMdWYsSskDQMVyYQm
Content-Disposition: form-data; name="apkfile"; filename="avatarcache.png"
Content-Type: image/png


------WebKitFormBoundaryMdWYsSskDQMVyYQm
Content-Disposition: form-data; name="uploadSubmit"

Upload
------WebKitFormBoundaryMdWYsSskDQMVyYQm--

```

for example:

part_data_start length is from

```sh
------WebKitFormBoundaryMdWYsSskDQMVyYQm
Content-Disposition: form-data; name="apkfile"; filename="avatarcache.png"
Content-Type: image/png
```

**Comment by ritchieGitHub** [comment]
Yes, I know the code that searches the end of the header is buggy ( not present...) I have to find a nice compact implementation for that. The unit test for reproduction is ready 😄

**Comment by ritchieGitHub** [comment]
please reopen when the fix did not work!

**Comment by onexuan** [comment]
Hi. it is fixed. it work well

**Comment by onexuan** [comment]
Please fix another bug when uploaded Multi-files, this is my code.
```sh
int count = 2;
while (files.containsKey(part_name + count)) {
         count++;
}
part_name = part_name + count;
files.put(part_name, path);
```

Add new line:

part_name = part_name + count;

**Comment by ritchieGitHub** [comment]
Please open a new issue for that. Again with a little more derails ;-)
