### ISSUE TITLE
Fullhttprequest and FullhttpResponse?

### ISSUE THREAD

**Issue by Frankzxliu** [NanoHttpd/nanohttpd#247]
How to implement fullhttprequest and fullhttpResponse in NanoHttpd?

Could anyone give me an example to do this?

Thank you in advance.

**Comment by ritchieGitHub** [comment]
What do you mean by fullhttprequest/response? The only reference I could find is a netty implementation detail for a http-request/response.

**Comment by Frankzxliu** [comment]
@ritchieGitHub Yes, can Nanohttp do something like that?

**Comment by ritchieGitHub** [comment]
Could you geive a small explanation what is special about them?

**Comment by Frankzxliu** [comment]
@ritchieGitHub Instead of only parse http body, it also parses http header and body. In other words, it combines the header and body, so it takes cares of a complete http request.

**Comment by ritchieGitHub** [comment]
These is more or less the default behavior in nanohttpd. Did you look through the examples? Especially the ones that user the newResponce methods?

**Comment by ritchieGitHub** [comment]
closed, due to end of question
