### ISSUE TITLE
WebSocket onOpen() error

### ISSUE THREAD

**Issue by LordFokas** [NanoHttpd/nanohttpd#249]
Calling a send() method in a websocket's onOpen() callback causes an error on the socket.
I shall come back later with more details or a fix if possible, but right now I'm in a hurry so I'm just making sure this doesn't go unchecked ;)

**Comment by LordFokas** [comment]
A bit more detail: it gives me the following exception:
![Exception](http://puu.sh/ldf6P/223c77fafa.png)

The send() method is being called inside the onOpen() callback.
There's an abstraction layer in the middle (between my code and NanoWSD) but it mostly maps methods directly. I'll try to post it here shortly.

**Comment by LordFokas** [comment]
Further testing revealed this may be related to external issues which I'm not currently being able to track, but so far it seems most likely not to be an actual NanoWSD issue. I'll keep you updated.

**Comment by ritchieGitHub** [comment]
ok, then I move it to the next release.

**Comment by LordFokas** [comment]
I think the issue is actually worse than it seemed. I don't even know what to do next.
I was running a full server (http+ws) on a single port, and websocket requests were hitting the http side, thus causing errors on the client, which disconnected the socket and on the server which was alreay writing to the socket in the onOpen() callback -- a socket that was no longer valid.

As soon as I split it into 2 servers on 2 ports it stopped misbehaving. Is it possible that not all WebSocket HTTP packets were being caught by NanoWSD and being let into the serveHttp() call?

**Comment by ritchieGitHub** [comment]
that remembers me of some of the other issues where they say serve is called multiple times for one request. The users reporting that wrote that is only happened when the server and the client are on the same machine. Can you try to find out if this is the same problem?

**Comment by LordFokas** [comment]
I don't have much free time right now but I'll give it a look when I can.

**Comment by matthieu-labas** [comment]
Note that the problem #225 seems to appear on the same computer but the other user noticed it as well with two different equipment. And I didn't see it happening when I was "forcing" the connection break by a `Response.addHeader("connection", "close")`. If I didn't do that, I still witnessed the two calls to `serve()`, even on different machines...

**Comment by LordFokas** [comment]
Further investigation revealed that exceptions thrown in `onOpen()` are being silently eaten.
I do believe this is on NanoHTTPD's side as I don't recall doing it on my thin abstraction layer. I will obviously check to make sure :)

Just to make it clear: a silently eaten NPE was causing the socket to be dumped (and garbage collected, I think?) which was causing the socket to close with an unknown error and no "cause" argument on the client side.

This is, again, the problem with treating symptoms. Just because your code doesn't explode in your face it doesn't mean it shouldn't. Most times it even makes sorting things out easier. :)

**Comment by LordFokas** [comment]
Ok this was just a branch of the main problem. The abort error discovered almost a month ago persists.

**Comment by LordFokas** [comment]
Alright. The socket error has been successfully traced back to to browsers being utterly ridiculous, which means there is no actual bug.

However, I highly recommend investigating and fixing exceptions being silently discarded: it's a serious problem in development even though it may be annoying in production.

**Comment by ritchieGitHub** [comment]
I went to the code but I can't find the path where the exception is not in some way handled? could you include a stack trace?

**Comment by LordFokas** [comment]
As you can see here exceptions in onOpen() propagate through the stack where handshakeResponse.send() is called: https://github.com/NanoHttpd/nanohttpd/blob/master/websocket/src/main/java/fi/iki/elonen/NanoWSD.java#L87

Which is returned into "regular" NanoHTTPD here: https://github.com/NanoHttpd/nanohttpd/blob/master/websocket/src/main/java/fi/iki/elonen/NanoWSD.java#L859

Which is called here, inside this try-catch in execute(), that doesn't catch it: https://github.com/NanoHttpd/nanohttpd/blob/master/core/src/main/java/fi/iki/elonen/NanoHTTPD.java#L857

Which is called here: https://github.com/NanoHttpd/nanohttpd/blob/master/core/src/main/java/fi/iki/elonen/NanoHTTPD.java#L190

Which just dismisses it as a "connection broken", even though it was a server-side error (a NPE, in my case).

I think we should wrap calls to some websocket methods (onOpen and any other we deem necessary) to avoid this kind of situation, because server side errors should be reported to the dev and not silently dismissed like the client or the connection suddenly went down. What do you think?

**Comment by ritchieGitHub** [comment]
Ok, that's why I could not find it ;-) It is logged but the level was incorrect set as FINE I will change that to SEVERE. 
wrapping a try catch around all "serve" methods with try/catch costs a lot of code lines.... I think the nano user should do that himself.

**Comment by ritchieGitHub** [comment]
@LordFokas  can you close this, if the log level issue is enough?

**Comment by LordFokas** [comment]
Yeah this can be closed. I'd be more comfortable with exceptions in serve being handed to the developer instead of logged but it doesn't make such a big difference that this should remain open.
