### ISSUE TITLE
prepare for release

### ISSUE THREAD

**Issue by ritchieGitHub** [NanoHttpd/nanohttpd#252]
We need a release soon so lets reference the issues that must be fixed before releasing

**Comment by LordFokas** [comment]
Isn't that exactly what the Milestone is? Just saying :p
Once the 2.2.0 Milestone is fullfilled, you got yourself a release :)
If there's anything there that isn't needed for the next release, those issues are on the wrong milestone.

**Comment by ritchieGitHub** [comment]
That true but we need a place to discuss the importance of the issues, and if they can wait till the next. That was the reason we lost the last window of opportunity. Now I try it this way..

**Comment by ritchieGitHub** [comment]
we had some not assinged issues:
#232  java.net.SocketException: sendto failed: EPIPE (Broken pipe) 
#211  read post body in chunked mode 
#217  HTTP Keep-Alive is not working

**Comment by LordFokas** [comment]
Well, so far #249 seems it may be caused by a source external to the server. I have to test a bit more and then I'll report appropriately.

As for #150 it didn't get me anywhere...

Also, from my point of view, Questions have no place in milestones until they're turned into actual issues.

**Comment by elonen** [comment]
Here are my opinions on these.

Wait a bit:
#249 Good to hear LordFokas is working on it.

Postpone to 2.3.0 / close:
#247 Definitely postpone, or close if no further clarification given.
#234 To 2.3.0 as not a showstopper for most users, it seems 
#222 Postpone, or if no further replies/contributions, close at some point.
#159 Close, with comment requesting people to reopen if it reappears.

Discuss further:
#150 Someone says "still an issue", but I couldn't reproduce. Dunno..?

**Comment by ritchieGitHub** [comment]
done, so now there the leftover is reduced to:
 
#232  java.net.SocketException: sendto failed: EPIPE (Broken pipe) bug
#217 HTTP Keep-Alive is not working bug
#211 read post body in chunked mode bug

I would say all these have waited so long, that they can move to 2.3.0.

@elonen  and @LordFokas  if you concur this I will release this weekend.

**Comment by LordFokas** [comment]
I have no problems with that :)

**Comment by ritchieGitHub** [comment]
@elonen  I will assume that you have the same opinion tomorrow, because after that I have to wait until next week.

**Comment by elonen** [comment]
Yes, no point delaying a release because of those. #217 is pretty important IMO, but it should be rare enough to be postponed.

**Comment by ritchieGitHub** [comment]
great than we have a release

**Comment by ritchieGitHub** [comment]
done, the release is under way to central and 
http://nanohttpd.org/ 
https://github.com/NanoHttpd/nanohttpd/releases
are updated. 

@elonen if you have a little time than a nice text describing the release would be great.

as soon as the release is landed in central I will report here (will take a few hours syncing time)

**Comment by ritchieGitHub** [comment]
release entered central and batches updated
