### ISSUE TITLE
SimpleWebServer crashes on static initializer

### ISSUE THREAD

**Issue by Alviere** [NanoHttpd/nanohttpd#265]
Hi everyone!
I faced an issue while trying to use nanohttpd-webserver in my android app:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.read(byte[])' on a null object reference
        at fi.iki.elonen.SimpleWebServer.<clinit>(SimpleWebServer.java:83)
```

This is actually happens because `InputStream` of LICENSE.txt is null and static initializer catches only `IOException`

```
    static {
        mimeTypes();
        InputStream stream = SimpleWebServer.class.getResourceAsStream("/LICENSE.txt");
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        byte[] buffer = new byte[1024];
        int count;
        String text;
        try {
            while ((count = stream.read(buffer)) >= 0) {
                bytes.write(buffer, 0, count);
            }
            text = bytes.toString("UTF-8");
        } catch (IOException e) {
            text = "unknown";
        }
        LICENCE = text;
    }
```

Does anybody know what can be done about it? I simply can't start web server because of that.
Thanks in advance!

**Comment by LordFokas** [comment]
How about NOT deleting LICENSE.TXT, so that the stream isn't null? ;)
You're not supposed to edit or remove the license of something you don't own.

**Comment by Alviere** [comment]
Who said that I'm deleting it? I can't modify dependency library included via gradle compile function. So the library is not modified in any ways.

(Included via `compile 'org.nanohttpd:nanohttpd-webserver:2.2.0'`)

**Comment by LordFokas** [comment]
Then the file should be there. And if the file is there, it shouldn't have a null stream.
I shouldn't have assumed you deleted it though...

**Comment by ritchieGitHub** [comment]
Ok, I kant imagine what the reason is that the license text is not found but I just extended the try a little to cover anything with the licence going wrong. Please try the SNAPSHOT and report back here.

**Comment by Alviere** [comment]
Apparently, Android Studio excludes all unnecessary files when it packs .apk file and I don't know how to make it include this license. But I made a small pull request that solves this issue.

**Comment by ritchieGitHub** [comment]
Thanks.
