### ISSUE TITLE
example starts and terminates directly

### ISSUE THREAD

**Issue by dagnelies** [NanoHttpd/nanohttpd#266]
Hi,

I just picked the example provided on the front page, and it correctly shows:
`Running! Point your browers to http://localhost:8080/`
But it terminates right after.

Anything I'm doing wrong?

**Comment by jpeyper** [comment]
I had this same issue, I changed the start command to 
```
server.start(NanoHTTPD.SOCKET_READ_TIMEOUT, false);
```
so it is not running in a daemon thread and it now stays running.

**Comment by dagnelies** [comment]
ok, thanks. It'd be nice to make this the default.

I'll leave the ticket open for now if you don't mind, it might help others.

**Comment by jpeyper** [comment]
Yes, or update the docs on the main page. 

If you get to it, the ssl example is also out of date. The `makeSecure` method takes a second parameters (use `null` if you want the default `sslProtocols`).

**Comment by ritchieGitHub** [comment]
documentation ist updated, thanks for pointing this out!
