### ISSUE TITLE
safeClose(Object closeable) have no sence.

### ISSUE THREAD

**Issue by isabsent** [NanoHttpd/nanohttpd#267]
This part of code looks strange:

    private static final void safeClose(Object closeable) {
        try {
            if (closeable != null) {
                if (closeable instanceof Closeable) {
                    ((Closeable) closeable).close();
                } else if (closeable instanceof Socket) {
                    ((Socket) closeable).close();
                } else if (closeable instanceof ServerSocket) {
                    ((ServerSocket) closeable).close();
                } else {
                    throw new IllegalArgumentException("Unknown object to close");
                }
            }
        } catch (IOException e) {
            NanoHTTPD.LOG.log(Level.SEVERE, "Could not close", e);
        }
    }

I suppose you mean:

    private static void safeClose(Object closeable) {
        try {
            if (closeable != null) {
                 if (closeable instanceof Socket) {
                    ((Socket) closeable).close();
                } else if (closeable instanceof ServerSocket) {
                    ((ServerSocket) closeable).close();
                 } else if (closeable instanceof Closeable) {
                     ((Closeable) closeable).close();
                } else {
                    throw new IllegalArgumentException("Unknown object to close");
                }
            }
        } catch (IOException e) {
            NanoHTTPD.LOG.log(Level.SEVERE, "Could not close", e);
        }
    }

Order of if-else was changed and **final** removed because it is after **private**.

**Comment by ritchieGitHub** [comment]
why should the order matter? the instanceof's are just for older jre's  where the Socket stuff was not a closeable.

**Comment by isabsent** [comment]
The reason of my proposal is that Socket and ServerSocket classes implement Closeable, therefore

    if (closeable instanceof Socket) 
and 

    if (closeable instanceof ServerSocket) 
are achieved never -  they were will be  closed at the condition

    if (closeable instanceof Closeable)

**Comment by ritchieGitHub** [comment]
Yes, that is why the closeable  condition is the first one. So in a newer jdk olny one check is nessesary.
