### ISSUE TITLE
How to use NanoHttpd to test android web client under different network conditions

### ISSUE THREAD

**Issue by spark85** [NanoHttpd/nanohttpd#280]
Hello, 

I'm new to NanoHttpd.  It was recommended to me as a replacement to a reverse proxy like Charles or Fiddler for testing how your application will behave under different network conditions and responses.  Is there a way to control NanoHttpd responses on the fly while your program is running, or would you have to program conditions. 

David

**Comment by LordFokas** [comment]
NanoHttpd is an open-source web server. There's a way to do **anything** with it, as long as it respects the protocol. How easy it can be done is another matter though.

I'm guessing what you want to do can easily be done with the webserver running in a console program... you can then program it to change the way it responds based on the commands you feed it.

**Comment by roloreaper** [comment]
@spark85 I wrote a mocking framework wrapping NanoHttpD
What do you mean by different Networking Senarios.
It might be a usefull addition to the HttpMock Project I have

**Comment by LordFokas** [comment]
I'm closing this. If you still have questions about this topic you can keep replying.
