### ISSUE TITLE
Get Json file from android app on request from PC browser

### ISSUE THREAD

**Issue by bhaveshpatel640** [NanoHttpd/nanohttpd#281]
@snostorm @luctrudeau @ajma @eighthave @AlbinTheander 
Hey, I'm totally new to this,
I want to implement web server on android.
On GET request from PC web browser,a Json file should created dynamically from android app and should sent to PC browser, so that i can display it on webpage hosted from that app
How can I do it??
Please help..

**Comment by AlbinTheander** [comment]
I don't think should be an issue, so anyone with the proper access should probably close it. :-1: )

But anyway... I put together a minimal Android project with a web server here: https://github.com/AlbinTheander/AndroidWebServer.

It is by no means an example of how you should write your Android application, but it shows how to add a NanoHttpd server that sends back a json file.

I hope it helps!

**Comment by ritchieGitHub** [comment]
thanks for the example
