### ISSUE TITLE
RouterNanoHTTPD constructor with hostname missing

### ISSUE THREAD

**Issue by eseidinger** [NanoHttpd/nanohttpd#284]
A constructor for RouterNanoHTTPD where one can specify the hostname would be helpful to restrict access to localhost. Something like.

```
    public RouterNanoHTTPD(String hostname, int port) {
        super(hostname, port);
        router = new UriRouter();
    } 
```

**Comment by LordFokas** [comment]
Feel free to do it and send us a Pull Request. I'd accept it the moment I laid eyes on it.
