### ISSUE TITLE
Post parameters are empty for Content-Type: application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by lordspace** [NanoHttpd/nanohttpd#288]
I am using the server in an android app. I am making calls from php and from Java code and the post params are still empty. This really a crucial thing.

I've tried this: http://stackoverflow.com/questions/22349772/retrieve-http-body-in-nanohttpd
and it didn't work.

GET request won't work for me because the data will become larger than 4K at some point.

```
<?php

$url = 'http://localhost/echo/';

$req_params = array(
    'cmd' => 'ping',
    'data' => array(
        'test' => 1,
    ),
);

$ch = curl_init();

//$dataEncoded = is_string($jsonData) ? $jsonData : json_encode($jsonData);
$get = 0;

$final_url = $url;

if ( $get ) {    
    $final_url .= '?' . http_build_query( $req_params );
} else {
    curl_setopt($ch, CURLOPT_POSTFIELDS, $req_params);
    //curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query( $req_params ) );
    curl_setopt($ch, CURLOPT_POST, 1);
    //curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));
}

curl_setopt($ch, CURLOPT_URL, $final_url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

$result = curl_exec($ch);

var_dump( $result );

curl_close($ch);
```

**Comment by LordFokas** [comment]
Can you show us your Java code to weed out the chance that you might be missing something?

**Comment by lordspace** [comment]
I am accessing the parameters just like it's shown in different examples nothing custom
Here's a video to reproduce it.
https://youtu.be/_3hbnP6nov0

**Comment by LordFokas** [comment]
Debug. Put a breakpoint on the serve method. Look at the request object, inspect its elements, especially the parameter map. That should give us some insight on the nature of the problem.

**Comment by roloreaper** [comment]
@lordspace 
Are you sure the contentType is correct. I did a code walk through on the parseBody method 
it check for multipart and if not then parses the payload if the contentType header is correct. Just verify that in the debug

**Comment by LordFokas** [comment]
I'm closing this. If you still have questions about this topic you can keep replying.

**Comment by lordspace** [comment]
Ok. Sounds good. I think I've solved in May by encoding the body in JSON or something. Can't 100% remember
