### ISSUE TITLE
Did it support HTTP 206？

### ISSUE THREAD

**Issue by CoderEic** [NanoHttpd/nanohttpd#295]
Image on the server, I can get it, but when I want to get the video on server, it didn't support.Why did it happen, how can I solve this problem?

**Comment by elonen** [comment]
Please provide more details. What didn't support what, and what exactly
happened?

**Comment by CoderEic** [comment]
First I put a image and a video on sdcard, then I start the server in order to client can visit them.
Then, when I visit image, it works.
However, I choose to visit that video, it didn't work.(I used the native VideoPlayer to play this mp4 video)
Can you give me some suggestion to solve this problems? Thank you.

**Comment by elonen** [comment]
Did you investigate this further? I suspect the client requested a partial
range from the file (streaming, hence status 206 from the server), but
either the player couldn't handle it or SimpleWebServer sent incorrect data.

**Comment by CoderEic** [comment]
Sorry, I have solve this problem.

**Comment by wu19910708** [comment]
朋友，，能告诉我一下你是怎么解决的吗
