### ISSUE TITLE
Run on Windows update 5 min guide

### ISSUE THREAD

**Issue by limeblack** [NanoHttpd/nanohttpd#297]
Does this run on Windows, if so could the guide be updated?

https://github.com/NanoHttpd/nanohttpd/wiki/5-minute-Tutorial

**Comment by LordFokas** [comment]
Did you try it recently?
Did it not work?
If so, why?

**Comment by LordFokas** [comment]
I'm closing this. If you still have questions about this topic you can keep replying.

**Comment by limeblack** [comment]
@LordFokas I'm not on windows but if it does work it would be nice to update the guide that is all.
