### ISSUE TITLE
Using a VPN to connect device running NanoHttpd(s) not working

### ISSUE THREAD

**Issue by BillSpahn** [NanoHttpd/nanohttpd#302]
I've had no problems using version 2.3 of NanoHttpd on my android device as an https server on my local network connected via wifi. However, when there's no wifi available and I use a VPN connection via cell service to put the server on the local network, I can no longer connect to the server. The browser hangs after "Connected to 192.168.1.198..." is displayed in the status bar. 

If I switch back to http, I have no trouble making the connection to the server over VPN. Also, passing the IP Address of the active network interface to the constructor did not fix the problem. 

My code is as follows:

	server = new MyHttpd(SERVER_PORT);
        KeyStore ks = KeyStore.getInstance("PKCS12");
        ks.load(this.getClass().getResourceAsStream("/server.p12"), "password".toCharArray());
        KeyManagerFactory kmf = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
        kmf.init(ks, "password".toCharArray());
        SSLContext sc = SSLContext.getInstance("TLS");
        sc.init(kmf.getKeyManagers(), null, null);
        server.makeSecure(sc.getServerSocketFactory(), null);
        server.start(15);

My guess is that it has something to do with which network interface the certificate is associated with but I'm not sure how to control the assignment.

Thanks very much for any help.

**Comment by LordFokas** [comment]
can you replicate this using HTTPS outside of a VPN?

**Comment by BillSpahn** [comment]
When I am on my local network via WiFi, server (NanoHTTP(s) android server) and client (Windows Firefox) on the same subnet, HTTPS connects without a problem. The issue arises when I am away from my local network and need to connect my android https server to my local network using the cell service. The simplest/only way I could think of to handle this was to connect the android server to my local network via a VPN tunnel. 

I did try using a separate wifi network and vpn in, without using a cell connection and had the same results. This gave me both a "WiFi IP address" (192.168.0.45) and a "local network address" (192.168.1.118) for the android server, with the client on the local network (192.168.1.11) and http worked and https did not. Not sure how else to test the HTTPS connection.

The code I use to determine the "WiFi IP address" is basically:
        WifiManager wifiManager = (WifiManager) context.getSystemService(WIFI_SERVICE);
        int ipAddress = wifiManager.getConnectionInfo().getIpAddress();

And the code to determine the "local network address" is basically: 
         List<NetworkInterface> interfaces = Collections.list(NetworkInterface.getNetworkInterfaces());
            for (NetworkInterface intf : interfaces) {
                List<InetAddress> addrs = Collections.list(intf.getInetAddresses());
                for (InetAddress addr : addrs) {
                    if (!addr.isLoopbackAddress()) {
                                return sAddr;
                    }
                }
            }
 
Not sure if it is relevant but I noticed that AirDroid only uses the WiFi IP address and disregards the IP address provided by the VPN.

**Comment by LordFokas** [comment]
I'm not very knowledgeable in Android, but the VPN was the prime suspect for me here (and still is).
Although it doesn't make a lot of sense for HTTPS to not work over VPN, from a diagnosis point of view it's the first logical step.

Do you have the NanoHTTPD server bound to any address?

**Comment by BillSpahn** [comment]
Ok, using "server = new MyHttpd(ipWifi, SERVER_PORT);" to bind to an ipAddress and using:
     Client running chrome on: 192.168.1.11
     Server using VPN: WiFi on: 192.168.0.108 and local IP Address on 192.168.1.77

HTTP - trying to access192.168.1.77:SERVER_PORT:
    Using WiFi ipAddress for NanoHTTPS to be bound to:     No connection
    Using local ipAddress:                                                       Connection
    Only specify Port:                                                              Connection   

HTTPS - trying to access192.168.1.77:SERVER_PORT:
    Using WiFi ipAddress for NanoHTTPS to be bound to:     No connection
         Error: 192.168.1.77 took too long to respond.
    Using local ipAddress:                                                       No Connection
         Error: 192.168.1.77 unexpectedly closed the connection.
    Only specify Port:                                                              No Connection   
       Error: 192.168.1.77 unexpectedly closed the connection.

Another test I ran: I have an https site running on a web server at 192.168.1.3 and with the same VPN as described above, I had no problem connecting to it with the android device as the client.

**Comment by BillSpahn** [comment]
Dug in a little deeper and found that I was getting a :

> java.net.SocketTimeoutException: SSL handshake timed out

It looks like the connection timeout I had set `server.start(15);` was fine for non-VPN connections but too short for VPN. Taking it out and using the default timeout seems to have fixed the problem. It also works without binding to an IP Address so the https and http are now working the same. 

Thanks for your help.
