### ISSUE TITLE
Embed jersey in it

### ISSUE THREAD

**Issue by daniel-dlds** [NanoHttpd/nanohttpd#312]
Have you ever thought about supporting jersey ?

**Comment by matthieu-labas** [comment]
If you can support it by extending `NanoHTTPD` then it should not be embedded but extended. WebDAV implementation was a good embedding to NanoHTTPD because it needed to support new verbs, and was part of the HTTP specs. I'm not sure Jersey fits in.

**Comment by LordFokas** [comment]
We aren't embedding anything, for now it doesn't make sense and after 3.0.0 those things can be added as plugin.
