### ISSUE TITLE
Allow thread name configuration

### ISSUE THREAD

**Issue by fedotxxl** [NanoHttpd/nanohttpd#316]
`NanoHttpd Request Processor (#1)` is too long thread name. Is it possible to configure it?

**Comment by LordFokas** [comment]
It is when you create the Thread... but why does it matter?

**Comment by fedotxxl** [comment]
I log thread name by logback and it consumes too much space

**Comment by LordFokas** [comment]
As of now you can override `DefaultAsyncRunner#createThread(ClientHandler)` to manually create your thread.
