### ISSUE TITLE
Yet another project using NanoHttpd

### ISSUE THREAD

**Issue by renaudpawlak** [NanoHttpd/nanohttpd#321]
All, I am pleased to point out that the [JSweet](https://github.com/cincheo/jsweet) (a Java to JavaScript transpiler) uses NanoHttpd to run its Web API... see the open source code at: https://github.com/cincheo/jsweet-http-server.

The implementation went smoothly and I would like to thank you for your excellent work!

I am sorry if this message is not really an "issue", but I did not find any other place where to talk about this.

**Comment by LordFokas** [comment]
Well, thanks for letting us know.
As a team member this really makes me proud :)
