### ISSUE TITLE
Support multiple values for a single parameter

### ISSUE THREAD

**Issue by dwatling** [NanoHttpd/nanohttpd#329]
There is currently an issue where the IHTTPSession.getParms() only stores a single String for a parameter even if the parameter has multiple values on the URL query string.

The API should be changed to return a List of Strings for the parameter.

An example of an incoming URL:

http://127.0.0.1:8990/?files=abc.txt&files=def.txt&files=ghi.txt

The only workaround at the moment is to parse the IHTTPSession.getQueryParameterString() yourself.

**Comment by LordFokas** [comment]
Linked to #286
