### ISSUE TITLE
Why is the value of a private var different from the value of a local var in NanoHTTPD?

### ISSUE THREAD

**Issue by mycwcgr** [NanoHttpd/nanohttpd#331]
Why is the value of a private var different from the value of a local var in NanoHTTPD?

Would you please have a look at http://stackoverflow.com/questions/37997060/why-is-the-value-of-a-private-var-different-from-the-value-of-a-local-var-in-nan

**Comment by LordFokas** [comment]
This has been answered in the StackOverflow thread, but it's essentially an error in dealing with the multithreaded nature of NanoHTTPD (user's fault).
