### ISSUE TITLE
New Constructor for newFixedLengthResponse(byte[] message)

### ISSUE THREAD

**Issue by ThreaT** [NanoHttpd/nanohttpd#332]
Can this constructor be added?

This would be particularly useful if the user wants to build the response themselves with all the headers and everything.

There are currently 3 constructors. One which accepts a single `String msg` - this would not accommodate for files to be transferred as `byte[]`. The other two require a status and mimetype which the user may prefer to assign themselves rather than passing it on to be assigned outside their control.

**Comment by LordFokas** [comment]
I seriously can't understand what you're trying to ask.
Why would you need to create a response from a byte[ ] ?

**Comment by mbazouz** [comment]
In my case, I added this constructor to download binary files.

**Comment by LordFokas** [comment]
You have a constructor that accepts an InputStream, which means you can use a ByteArrayInputStream to wrap your byte[] into a stream.

**Comment by LordFokas** [comment]
Next PR from me will include a `Response#newFixedLengthResponse(IStatus, String, byte[])`
It will be a shortcut to the stream method.
