### ISSUE TITLE
Add a Gradle build

### ISSUE THREAD

**Issue by psh** [NanoHttpd/nanohttpd#34]
As a developer without *Maven* installed on my machine, I would like to be able to build and use NanoHttpd.  Investigate and write a build for the software that uses Gradle, and whether important properties (version, name, etc) can be held in common property files across both builds.

**Comment by ritchieGitHub** [comment]
Usage over the central repo, that is available to gradle. But the development is maven based, resources are to thin spread to support both.

**Comment by spyhunter99** [comment]
There's a gradle wrapper equivalent for maven if that will make someone life easier
