### ISSUE TITLE
Unable to connect to on same network

### ISSUE THREAD

**Issue by xtreameprogram** [NanoHttpd/nanohttpd#341]
I am running an HTTPD server form an android device and can successfully connect to it from that device. However, when it try to connect to it by its local ip address and its port (putting in: http://192.168.4.30:8080), nothing. I ran into this problem when using node, but to fix that issue I had to listen for the whole network (0.0.0.0). How do achieve this with nanoHTTPD?

**Comment by LordFokas** [comment]
This seems more like a network or configuration rather than code problem.
I'm closing this. If you still have questions about this topic you can keep replying.
