### ISSUE TITLE
Make default port 8080 configurable

### ISSUE THREAD

**Issue by elgalu** [NanoHttpd/nanohttpd#344]
Make default port `8080` configurable through environment variables and/or `java -cp ... -D` command line parameters.

**Comment by fermin-silva** [comment]
Can't you just do:
```
public class App extends NanoHTTPD {

        public App() throws IOException {
            super(Integer.parseInt(System.env("nano_port")));
            start(NanoHTTPD.SOCKET_READ_TIMEOUT, false);
        }
...
```
Albeit with a more robust error handling and default chains (try `env`, try `System.getProperty,` etc)

**Comment by matthieu-labas** [comment]
In fact, I think the default port should be `80`, because it *is* the default HTTP port. Otherwise, the 3 lines proposed by @fermin-silva really is what you should do...

**Comment by fermin-silva** [comment]
Careful with port 80 being the default. Ports under 1024 require root privileges in Linux, not sure about Windows.
It would be weird to start the server on your IDE and get a cryptic `Permission denied` message.

**Comment by LordFokas** [comment]
Unless there is a really strong reason to change the way port configurations are done, which are fairly flexible, this won't be considered.

As far as I am aware of, every server here can be easily configured, but prove me wrong and I'll give it a shot.
