### ISSUE TITLE
Any chance we could get a new release?

### ISSUE THREAD

**Issue by dwatling** [NanoHttpd/nanohttpd#349]
There are a few changes on master that I'd like to use in my projects. 

If we can't get a release now, what needs to be done before it can happen?

**Comment by ritchieGitHub** [comment]
@LordFokas what do you think, shall I make one or are you on to something?

**Comment by LordFokas** [comment]
Keep releasing minors until 3.0.0 happens

**Comment by ritchieGitHub** [comment]
OK will release a version in the next week (maybe earlier)

**Comment by ritchieGitHub** [comment]
new release done 2.3.1
