### ISSUE TITLE
Is HTTP Pipelining supported in nanohttpd? 

### ISSUE THREAD

**Issue by praserocking** [NanoHttpd/nanohttpd#350]
I am using nanohttpd for a project and I want to support HTTP Pipelining. Is it possible in Nanohttpd? I could not find anything when I looked at the source. If it is not possible, is there any other embeddable server which can do it?

**Comment by LordFokas** [comment]
I don't think it can because there's some synchronization going on there, namely with the socket reading loop, but even if it can't support it you're always welcome to implement it and send us a Pull Request :)

**Comment by praserocking** [comment]
Thank you @LordFokas also one more question, does it support gzipped content encoding? Whenever I set gzipped content flag as true and send as chunkedresponse I get only "Transfer Encoding" flag set on the response and there isn't any Content Encoding flag.

**Comment by praserocking** [comment]
I found the answer for my last question, thanks!

**Comment by LordFokas** [comment]
Looks like you already fixed it :)
