### ISSUE TITLE
getParms is deprecated

### ISSUE THREAD

**Issue by Khoosham** [NanoHttpd/nanohttpd#360]
String s1 = session.getParms().get("value1");
String s2 = session.getParms().get("value2");

getParms is deprecated....
what should i use instead in the above example ??
Thanks

**Comment by LordFokas** [comment]
You have another getter, I think it's getParameters, that uses an index as well in case you have multiple values in the same parameter, which is possible.

getParms() only gets you the first value and will most likely be removed soon. There's also a getter for the number of possible indices for a given parameter somewhere.

**Comment by Khoosham** [comment]
String s1 = session.getParameters().get("value1").toString();

i got the above code working but
the output is as follows [something] i need it without the square brackets...
i tried replaceall replace etc.. could not got it to work on android textview

**Comment by beiBe1991** [comment]
just use 
String s1 = session.getParameters().get("value1").get(0).toString();
