### ISSUE TITLE
IHTTPSession getQueryParameterString returns form parameters on POST

### ISSUE THREAD

**Issue by johanhaleby** [NanoHttpd/nanohttpd#363]
When sending a request like this (copied from Wireshark):

```
POST /something HTTP/1.1
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Accept-Encoding: gzip, deflate
User-Agent: Java/1.8.0_60
Host: localhost:51351
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive
Content-Length: 28

parameter=value&also=another
```

then the `getQueryParameterString` of `IHTTPSession` will return `parameter=value&also=another` but that is not a query string afaik. If it's a query string it ought to be sent in the URI: 

`/something?parameter=value&also=another`

In my example `parameter=value&also=another` or form parameters.

**Comment by LordFokas** [comment]
Yes, that is the POST body, not a Query String.

**Comment by LordFokas** [comment]
The issue above explains everything better, I'll be closing this one.
