### ISSUE TITLE
ServerRunnable can not be extended because its constructor is private

### ISSUE THREAD

**Issue by felipeerias** [NanoHttpd/nanohttpd#368]
In NanoHTTPD, the documentation for the method createServerRunnable() states that it can be overwritten by subclasses to provide their own subclass of the ServerRunnable.

However, the only constructor for ServerRunnable has private access, which makes it impossible to extend it.

Simply making this constructor "protected" would fix the issue.

**Comment by LordFokas** [comment]
I'll see that taken care of.

**Comment by LordFokas** [comment]
Actually since the files were split the constructor is already public, so it's done.
