### ISSUE TITLE
Encodage problems

### ISSUE THREAD

**Issue by natinusala** [NanoHttpd/nanohttpd#37]
Hello,

When I do something like this on serve(...) :

return new Response("Désolé, cette adresse email est déjà utilisée.");

I have this on the page : DÃ©solÃ©, ce nom est dÃ©jÃ  utilisÃ©.

Could you fix this ?

Thanks !

**Comment by ritchieGitHub** [comment]
don't forget you are sending a html page! (and the response is default send as UTF-8) Wenn you want to controll the encoding yourself use
```
new Response(IStatus status, String mimeType, InputStream data)
```
there you can send whatever you want ;-)
