### ISSUE TITLE
Ajax BAD REQUEST

### ISSUE THREAD

**Issue by aleksandrmozgovoi** [NanoHttpd/nanohttpd#373]
Hello.
I get every second ajax request BAD REQUEST if there is POST data.
You can set an example for working AJAX how get all the POST data?
Thank you.

**Comment by aleksandrmozgovoi** [comment]
`@Override
    public Response serve(IHTTPSession session) {
        debugLog("response " + session.getQueryParameterString() + " " + session.getRemoteHostName() + " " + session.getRemoteIpAddress() + " " + session.getUri());
 
        InputStream mbuffer = null;
        switch (session.getUri()){
            case "/":
                return newFixedLengthResponse("" +
                        "<html>" +
                        "<script type="text/javascript" src="jquery-3.1.0.min.js"></script>" +
                        "<body>" +
                        "<input type="button" value="Button" style="width:150px;height:30px" onclick="getJS()"/>" +
                        "<script>" +
                        "function getJS(){" +
                            "$.ajax({" +
                                "type: "POST"," +
                                "url: "Data.php"," +
                                "data: {" +
                                "'prm1':'Params'" +
                                "}," +
                                "success: function(data) {" +
                                    "alert('ajax EXEC!!! ' + data)" +
                                "}," +
                                "error:function(){" +
                                    "alert('ERROR AJAX');" +
                                "}" +
                            "});" +
                        "}" +
                        "</script>" +
                        "</body></html>");
            case "/jquery-3.1.0.min.js":
                try {
                    mbuffer = mb.getAssets().open("web/jquery-3.1.0.min.js");
                } catch (IOException e) {
                    debugLog("ERROR. get myScript.js from assets " + e.getMessage());
                }
                try {
                    return newFixedLengthResponse(Response.Status.OK, MIME_JS, mbuffer, mbuffer.available());
                } catch (IOException e) {
                    debugLog(e.getMessage());
                }
            case "/Data.php":
                debugLog("запрос /Data.php ");
                String msg = "OK AJAX";
                return newFixedLengthResponse(NanoHTTPD.Response.Status.OK, MIME_PLAINTEXT, msg);
            default:
                return newFixedLengthResponse(Response.Status.NOT_FOUND,"","");
        }
    }`

**Comment by LordFokas** [comment]
Possible connection to #314 ??

**Comment by peter4k** [comment]
run these two lines at the end of each "serve"
```
    InputStream is = session.getInputStream();
    is.skip(is.available());
```

**Comment by LordFokas** [comment]
@peter4k if you already have a new request in the buffer, won't that discard that request?

**Comment by peter4k** [comment]
@LordFokas hmm I ran an 30 concurrency and 150 total request test using ab, did not see any error.

**Comment by LordFokas** [comment]
@peter4k being careful doesn't hurt.
The way session streams are read (right now) is fishy to say the least. I intend to make it so that as soon as the header is read the whole body is read as a single chunk right afterwards, by default. That should encapsulate the whole request data in a single object, making everything a lot easier to manage.

**Comment by peter4k** [comment]
@LordFokas that would be great. Will it be a feature in v3?

**Comment by LordFokas** [comment]
I want it to be... but I want to deliver before Feb 2, and I don't have much time with a full time job and studying engineering at night. Might be pushed to 3.1, if I can't fit it there.

**Comment by aleksandrmozgovoi** [comment]
Create a new project in intellij idea, everything works, no errors.
Apparently the problem was only with the android, I did not expect that from a bad request exception class, my mistake.
closed for Me
