### ISSUE TITLE
The old package name fi.iki.elonen in documents

### ISSUE THREAD

**Issue by wing9405** [NanoHttpd/nanohttpd#377]
It seems that there is no so named package in the source tree.

**Comment by LordFokas** [comment]
We are currently working on v3.0.0, which moves everything still on `fi.iki.elonen.*` to `org.nanohttpd.*`

**Comment by wing9405** [comment]
Aha~! I see. Thank you.

**Comment by Bendanzigumass** [comment]
This is still an issue for me. When I try and run the "5 min tutorial" from the Wiki page, and specifically I get to the part where it says to run java -cp webserver/target/nanohttpd-webserver-2.1.0-jar-with-dependencies.jar fi.iki.elonen.SimpleWebServer

I still get errors saying Error: Could not find or load main class fi.iki.elonen.SimpleWebServer
Even when I change it from fi.iki.elonen to org.nanohttpd it doesn't work. ANy suggestions?

**Comment by LordFokas** [comment]
That change only applies to version 3.

Try using 2.3.1 instead, might be something that was fixed later. As far as releases are concerned, 2.3.1 is latest-and-greatest code.

**Comment by LordFokas** [comment]
I'm closing this. If you still have questions about this topic you can keep replying.
