### ISSUE TITLE
GET response Aborted

### ISSUE THREAD

**Issue by aleksandrmozgovoi** [NanoHttpd/nanohttpd#378]
Hello.
I get GET requests from the browser to the image.
I need to ability to make some time to process the request (~ 2s), but nanohttpd connection resets after 10 ms.

```
    @Override
    public Response serve(IHTTPSession session) {
        switch (session.getUri()){
		 case "/capture.jpg":
                debugLog("case /capture.jpg:");
				// ---- Here, I need a little time
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                mbCanvas.mainLayout.setDrawingCacheEnabled(true);
                mbCanvas.mainLayout.getDrawingCache().compress(Bitmap.CompressFormat.PNG, 0, bos);
                mbCanvas.mainLayout.setDrawingCacheEnabled(false);
                byte[] bitmapData = bos.toByteArray();
                ByteArrayInputStream bs = new ByteArrayInputStream(bitmapData);
                return newFixedLengthResponse(Response.Status.OK, "image/jpeg", bs, bs.available());
            case "/capture2.jpg":
                debugLog("case /capture2.jpg:");
				// ---- Here, I need a little time
                ByteArrayOutputStream bos2 = new ByteArrayOutputStream();
                mbCanvas.testLayout.setDrawingCacheEnabled(true);
                mbCanvas.testLayout.getDrawingCache().compress(Bitmap.CompressFormat.PNG, 0, bos2);
                mbCanvas.testLayout.setDrawingCacheEnabled(false);
                byte[] bitmapData2 = bos2.toByteArray();
                ByteArrayInputStream bs2 = new ByteArrayInputStream(bitmapData2);
                return newFixedLengthResponse(Response.Status.OK, "image/jpeg", bs2, bs2.available());
		}
	}
```
These 2 response are absolutely identical, BUT / capture 2.jpg always Aborted.
I can not get an answer to /capture2.jpg request.
Why?
How to extend the time?

**Comment by LordFokas** [comment]
The protocol specs allow you to respond withing 60 seconds, which should be enough.
To work around that problem you need to know what is timing out, and then extend that to, say, 10 seconds.

**Comment by aleksandrmozgovoi** [comment]
Ok, but how?
This params in nanohttpd?

**Comment by LordFokas** [comment]
It's probably a standard java socket configuration.
You need to go step by step.

- Which socket is timing out?
- Why is it timing out?
- Where can that timeout be prevented?
- Fix it.

Don't try to skip any steps, it won't take you anywhere.

**Comment by aleksandrmozgovoi** [comment]
```
public WebServer(int port, Context context) {
        super(port);
        this.context = context;
        try {
            start(8000,true);//this timeout = 8 sec. You mean this?
            debugLog("nanoHttpd START");
        } catch (IOException e) {
            debugLog(e.getMessage());
        }
    }
```

**Comment by LordFokas** [comment]
You're still trying to jump right into the third step. If you don't go through steps 1 & 2 first you can't fix it properly.

**Comment by aleksandrmozgovoi** [comment]
1) I'd had enough for 2 seconds timeout
2) Image generated programmatically. Makes screen screenshot. it takes time.
3) that's the problem, I have to generate on-demand, in advance I can not generate it.
4) ...

` case "/capture2.jpg":
                debugLog("case /capture2.jpg:");
                // ---- Here, I need a little time
                ByteArrayOutputStream bos2 = new ByteArrayOutputStream();
                mbCanvas.testLayout.setDrawingCacheEnabled(true);
                mbCanvas.testLayout.getDrawingCache().compress(Bitmap.CompressFormat.PNG, 0, bos2);
                mbCanvas.testLayout.setDrawingCacheEnabled(false);
                byte[] bitmapData2 = bos2.toByteArray();
                ByteArrayInputStream bs2 = new ByteArrayInputStream(bitmapData2);
debugLog("case /capture2.jpg: End");// ##### THIS LOG NEVER WORKS, WHY ? ####
                return newFixedLengthResponse(Response.Status.OK, "image/jpeg", bs2, bs2.available());`

**Comment by aleksandrmozgovoi** [comment]
Can you help me?

**Comment by aleksandrmozgovoi** [comment]
Sorry, an error was when processing a request.
In compress(Bitmap.CompressFormat...

**Comment by LordFokas** [comment]
If your problem has been solved, close the issue.
