### ISSUE TITLE
NullPointerException when get InputStream of "LICENSE.txt"

### ISSUE THREAD

**Issue by zysidea** [NanoHttpd/nanohttpd#379]
i have watched the same issue opend last year, i upgrade the version to 2.2.0,but still not work.

**Comment by zysidea** [comment]
the version 2.3.1 works, but the newest version is 2.2.0 in the [http://nanohttpd.org/](url)

**Comment by LordFokas** [comment]
Then use 2.3.1, despite what the site says.
You should always upgrade to newer versions.

@elonen @ritchieGitHub is there something going on with the site?

**Comment by ritchieGitHub** [comment]
yes, it is down. I have already a request running. But because it is a "cheap" machine, that takes a little.

**Comment by LordFokas** [comment]
I didn't mean technically, but in terms of data and accurate information, since apparently the site reports 2.2.0 as the latest version...

**Comment by ritchieGitHub** [comment]
It should be automatically updated, but I can not check it, because offline ;)
