### ISSUE TITLE
Maven runs tests with JDK 7 but compiles with JDK 6

### ISSUE THREAD

**Issue by LordFokas** [NanoHttpd/nanohttpd#383]
This causes inconsistencies with things like diamond operators breaking stuff.

@ritchieGitHub since this is a project configuration issue I'm assigning you so you remember to take a look into it when you have the time ;)

**Comment by ritchieGitHub** [comment]
I remember the reason was that android used the jdk-6 api at the time. And to ensure the functioning of nanohttpd under android we set the test version to 1.6. I think that this is not relevant for 3.0, there you should go for 8.0 as a minimum version. Or should we hold at 7.0 ?

**Comment by LordFokas** [comment]
We can hold at 7.0 for compat.
It's just bad that we're doing things with 2 different versions, because it compiles on the IDE, then it starts compiling on maven, some tests run, and then maven starts spewing out compilation errors which is a really inconsistent behavior...

**Comment by ritchieGitHub** [comment]
correct, I did not like it either. but there was no other way (test machine limitations). Just change all java versions in the pom to 1.7 then everything will be ok ;-)
