### ISSUE TITLE
SocketTimeoutException on websocket

### ISSUE THREAD

**Issue by publicocean0** [NanoHttpd/nanohttpd#386]
version 2.3.1 and 2.3.2-SNAPSHOT

11:28:12,450 DEBUG NanoWSD$WebSocket:23 - opened
11:28:13,655 DEBUG NanoWSD$WebSocket:59 - Received Frame WS[Text, fin, masked, [2b] bb]
11:28:13,663 DEBUG NanoWSD$WebSocket:66 - Sent Frame WS[Text, fin, unmasked, [2b] bb]
11:28:13,811 DEBUG NanoWSD$WebSocket:59 - Received Frame WS[Text, fin, masked, [2b] bb]
11:28:13,812 DEBUG NanoWSD$WebSocket:66 - Sent Frame WS[Text, fin, unmasked, [2b] bb]
11:28:13,962 DEBUG NanoWSD$WebSocket:59 - Received Frame WS[Text, fin, masked, [2b] bb]
11:28:13,962 DEBUG NanoWSD$WebSocket:66 - Sent Frame WS[Text, fin, unmasked, [2b] bb]
11:28:14,107 DEBUG NanoWSD$WebSocket:59 - Received Frame WS[Text, fin, masked, [2b] bb]
11:28:14,107 DEBUG NanoWSD$WebSocket:66 - Sent Frame WS[Text, fin, unmasked, [2b] bb]
11:28:19,116 DEBUG NanoWSD$WebSocket:53 - exception occured
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at fi.iki.elonen.NanoWSD$WebSocketFrame.read(NanoWSD.java:435)
	at fi.iki.elonen.NanoWSD$WebSocket.readWebsocket(NanoWSD.java:248)
	at fi.iki.elonen.NanoWSD$WebSocket.access$200(NanoWSD.java:65)
	at fi.iki.elonen.NanoWSD$WebSocket$1.send(NanoWSD.java:88)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:957)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:745)
11:28:19,125 DEBUG NanoWSD$WebSocket:29 - Closed [Self] InternalServerError: Handler terminated without closing the connection.

**Comment by publicocean0** [comment]
observing a bit code i thing there is a error in websocket management

when i send a message then it call receive in a loop. It sounds a error. If i send 2 consecutive messages?
i think it might be handled in a separated thread.

**Comment by publicocean0** [comment]
public class WebSocketWorker extends Thread {

		private BlockingQueue<WebSocketImpl> iqueue;

		public WebSocketWorker() {
			iqueue = new LinkedBlockingQueue<WebSocketImpl>();
			setName( "WebSocketWorker-" + getId() );
			setUncaughtExceptionHandler( new UncaughtExceptionHandler() {
				@Override
				public void uncaughtException( Thread t, Throwable e ) {
					getDefaultUncaughtExceptionHandler().uncaughtException( t, e );
				}
			} );
		}

		public void put( WebSocketImpl ws ) throws InterruptedException {
			iqueue.put( ws );
		}

		@Override
		public void run() {
			WebSocketImpl ws = null;
			try {
				while ( true ) {
					ByteBuffer buf = null;
					ws = iqueue.take();
					buf = ws.inQueue.poll();
					assert ( buf != null );
					try {
						ws.decode( buf );
					} catch(Exception e){
						System.err.println("Error while reading from remote connection: " + e);
					}
					
					finally {
						pushBuffer( buf );
					}
				}
			} catch ( InterruptedException e ) {
			} catch ( RuntimeException e ) {
				handleFatal( ws, e );
			}
		}
	}

**Comment by publicocean0** [comment]
error seams be here  

@Override
        public void send(OutputStream out) {
            WebSocket.this.out = out;
            WebSocket.this.state = State.CONNECTING;
            super.send(out);
            WebSocket.this.state = State.OPEN;
            WebSocket.this.onOpen();
            readWebsocket();
        }

**Comment by LordFokas** [comment]
There's only one loop there and it spends most of its time locked by a blocking input method.
That loop is necessary, it's what makes it possible to read more than one packet on each tcp socket.

Your websocket is timing out because you're not pinging the socket, thus whenever you spend more than 10 seconds (default socket timeout) without sending packets to the server, the server socket blocking read method unblocks and times out.

**Comment by LordFokas** [comment]
it may be pinging behind your back.

As for closed connections, if you don't use the proper closing mechanisms it's only natural that the other side of the socket throws an hissy fit. You must send a close packet, the same way you terminate a TCP connection with a FIN signal.

**Comment by publicocean0** [comment]
I fixed bug with onClose event. 
The lifecicle is correct now but timeout error is present also using javascript. 
i tried also in javascript
var i=0;
	var echo_service = new WebSocket('ws://localhost:90/aa');
	
	
	echo_service.onmessage = function(event){ 
	console.log("ricevuto :"+event.data) ;
 
      
    }
    var sender=function(){
      i++;
      if (i<10) {
      echo_service.send('test '+i);
      setTimeout(sender,1000);
      }
      
      };
    echo_service.onopen = function(){
      console.log("connessione effettuata") ;
      sender();
    } 
    echo_service.onclose = function(){
      console.log("connessione chiusa");
    } 
    echo_service.onerror = function(){
      console.log("errore nella connessione");
    }

**Comment by publicocean0** [comment]
in tomcat i found 

"When using the WebSocket client to connect to server endpoints, the timeout for IO operations while establishing the connection is controlled by the userProperties of the provided javax.websocket.ClientEndpointConfig. The property is org.apache.tomcat.websocket.IO_TIMEOUT_MS and is the timeout as a String in milliseconds. The default is 5000 (5 seconds)."

This timeout is just in handshake phase. Then timeout=0.

**Comment by publicocean0** [comment]
i m thinking to modify serve function in 

serve(Socket socket, IHTTPSession session) 

so NanoWSD can reset socket timeout when handshake phase is completed

**Comment by LordFokas** [comment]
If you're using tomcat's websockets, then that's not a NanoWSD issue.
But it seems to me like you're simply getting into stuff that are way over your head, so I'm going to mark this as a question until we got you headed in a good direction or figure there's an actual issue with our code...

**Comment by publicocean0** [comment]
No i used nanowsd. I read tomcat specification for understanding better the websocket behaviour.

**Comment by LordFokas** [comment]
You still have to ping sockets, or they die. At least in our implementation, I'm not sure if we can turn off that timeout, but if we do it's probably a bad idea anyways.

The correct way to handle that is to ping. When a side stops receiving pings or pongs, it should assume the other side of the socket died and terminate.

**Comment by publicocean0** [comment]
no browsers can ping. Who can use your implementation?  Anyway i already
changed a lot of thing, fixed these problems and others. You can continue
to leave so. Thanks anyway

2016-10-02 4:27 GMT+02:00 LordFokas <notifications@github.com>:

**Comment by LordFokas** [comment]
You can ping from browsers, but it's easier to ping from the server and have the browser automatically pong.

**Comment by wizapp** [comment]
Hi,
Websocket clients does not have to respond to servers' pings.
Standard WebSocket client libraries (like ws or socket.io does not do that).
After years of using WebSockets with several implementations, it's the first time I'm facing this issue, just trying to use NanoWSD server.
Is there a fork of nanohttpd with WebSocket that does not do this unneeded ping check from server side or any other reliable Android WebSocket server component ?

**Comment by NoahAndrews** [comment]
https://github.com/TooTallNate/Java-WebSocket has worked well for me. I think its concurrency model could use some improvement, but I've found it to be good enough in practice. And it's actively maintained. 

NanoWSD is full of bugs. I started trying to fix them, and ultimately gave up and switched. The implementation is just bad. Stick to using NanoHTTPD as a basic web server, use something else for a WS server, and you'll be happier.

**Comment by NoahAndrews** [comment]
Also, I'm confused by your question. Are you saying it's a case idea to send the pings from the server because clients aren't obligated to respond?

**Comment by wizapp** [comment]
Thank you @NoahAndrews for your response.
I have found & tested Java-WebSocket last hours. I'm glad you advise me this component. It consolidate my choice. thank you.
About ping from server, yes I think it's a bad idea since that would mean that all WebSocket clients (applications) would have to do this extra job. If it is needed, it is responsibility of WebSocket client libraries to do that, but it's not the case.

**Comment by NoahAndrews** [comment]
If your WebSocket client is a browser, it responds to pings automatically. It's part of the spec. The web application doesn't even get notified that a ping was received, because the web browser handles it for you.

Any non-browser WebSocket client should respond to pings automatically as well. Sending pings from the server is the intended way.

**Comment by LordFokas** [comment]
At least Chrome and Firefox automatically pong the sockets when you ping from the server. I've tested it in the past, when I changed some of the WebSocket code.

You have 2 choices:
- Ping from the server
- Set the socket timeout to infinite

The first option is just plain better, because otherwise if a socket hangs the server will keep it alive even though there hasn't been anything on the other side for a long time. When it comes to code, I do not support and/or condone using sub-par methods to achieve certain goals due to lazyness. Just ping the damn socket, you can thank me later when you don't have mysterious bugs.

**Comment by spartacusrex99** [comment]
Same thing here.. Simple FIX.

If you follow the class trail you end up at Line 165 of NanoHTTPD.. 

public static final int SOCKET_READ_TIMEOUT = 5000;

..Just change that.

OR.. better.. If you dig a little deeper you'll notice

public void start(final int timeout) throws IOException {
   start(timeout, true);
}

And just the plain start() is called in the echosocket.. just switch it for the one where you specify a timeout.

It works.

Big Up LordFokas for sharing this great little project with all of us.. :)
