### ISSUE TITLE
nanohttpd.org is down?

### ISSUE THREAD

**Issue by lazerwalker** [NanoHttpd/nanohttpd#387]
Hi!

I don't know the best place to report this, but http://nanohttpd.org appears to be down / non-functioning. 

Is this a known problem?

**Comment by ritchieGitHub** [comment]
yes, it is known. the provider is making troubles....

**Comment by LordFokas** [comment]
This seems to now be pointing back here.
If this gets reopened @ritchieGitHub should be getting notifications for it.
I'm closing this, as the domain responds, even though by pointing me back to the repository.
