### ISSUE TITLE
delay of 10 seconds when receiving POST-method packet

### ISSUE THREAD

**Issue by minibeep** [NanoHttpd/nanohttpd#389]
I encounter a strange issue when using nanohttpd.
When a client  issue a data packet to nanohttpds server using POST method, the following happens:
1. The client is thrown an sockettimeout exception.
2. The server doesn't receive the POST-method packet until 10 seconds latter.

Note that the time span between sending POST packet and receiving sockettimeout exception  at the receiver is always equal to the number x set in setsockettimeout(in x). The client we use is PoolingHttpClient by Apache.

Does anyone know how to solve the issue? Thanks in advance!

**Comment by LordFokas** [comment]
That seems like a client issue, and not on the server side. I haven't even heard of that client before.
I'm closing this. If you still have questions about this topic you can keep replying.
