### ISSUE TITLE
How To Get Upload Progress

### ISSUE THREAD

**Issue by chengxinwen-vinci** [NanoHttpd/nanohttpd#390]
Hi admins,

Is there any possible way to get progress of uploading? Current parseBody method doesn't include any callback to let user know its upload & copy progress, would you please concern?

Thanks!

**Comment by alexruskovski** [comment]
I had the same problem. I solve it with implementing ajax xhr upload from where you can keep track of upload progres. 

$( "#uploadForm" ).submit(function( event ) {

    if(document.getElementById('uploadFile').files.length > 0){
		
		event.preventDefault();
		
		var selectedFilesCount = document.getElementById('uploadFile').files.length;
		
		var currentFile = document.getElementById('uploadFile').files[0];
		
		uplaodFil(currentFile,$('form')[0]);
	
	}else{// no file selected
		document.getElementById("submitBtn").style.display = "none";
		alert('Please choose a file to be uploaded!');
		event.preventDefault();
	}

});







function progress(e){
    if(e.lengthComputable){
        var max = e.total;
        var current = e.loaded;

        var Percentage = (current * 100)/max;
		
        bar.width(Percentage);
		percent.html(Percentage.toFixed(1)+"%");
		
		if(Percentage >= 100)
        {
           percent.html('Saving file..');
        }
    }  
}


function beforeSendHandler(e){
	document.getElementById('progress').style.display = "block";
	var percentVal = '0%';
    bar.width(percentVal)
    percent.html(percentVal);
}

function completeHandler(e){
	alert('File is being uploaded!');
	document.getElementById("submitBtn").style.display = "none";
	document.getElementById("progress").style.display = "none";
}

function errorHandler(e){
	console.log(e.message);
}

function chooseFile() {
    document.getElementById("uploadFile").click();
	document.getElementById("submitBtn").style.display = "block";
	document.getElementById("submitBtn").style.marginTop = "5px";
}



function uplaodFil(currentFile,data){
	
		fileName = currentFile.name;
		fileSize = currentFile.size;
		fileType = currentFile.type;
		
		var formData = new FormData(data);
		$.ajax({
			//url: '#',  //Server script to process data
			type: 'POST',
			xhr: function() {  // Custom XMLHttpRequest
				var myXhr = $.ajaxSettings.xhr();
					if(myXhr.upload){ // Check if upload property exists
					myXhr.upload.addEventListener('progress',progress, false);
				}			
				return myXhr;
			},
			beforeSend: beforeSendHandler,
			success: completeHandler,
			error: errorHandler,
			data: formData,
			
			cache: false,
			contentType: false,
			processData: false
		});
	
}

```

**Comment by LordFokas** [comment]
@alexruskovski doing it on the client side actually makes much more sense... Thank you :)

**Comment by LordFokas** [comment]
This has been resolved.
I'm closing this. If you still have questions about this topic you can keep replying.
