### ISSUE TITLE
SimpleWebServer: Content-Length appears twice in the response

### ISSUE THREAD

**Issue by jtn-d** [NanoHttpd/nanohttpd#395]
curl -I http://x.x.x.x/x/test.jpg

HTTP/1.1 200 OK
Content-Type: image/jpeg
Date: Thu, 24 Nov 2016 08:25:04 GMT
Access-Control-Max-Age: 151200
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
ETag: 51d86932
Content-Length: 496305
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: origin,accept,content-type
Access-Control-Allow-Origin: *
Accept-Ranges: bytes
Connection: keep-alive
Content-Length: 496305

Some http clients doesn't work at all, when the response has two Content-Length headers.

**Comment by LordFokas** [comment]
This is happening both here: https://github.com/NanoHttpd/nanohttpd/blob/master/core/src/main/java/org/nanohttpd/protocols/http/response/Response.java#L240

and here: https://github.com/NanoHttpd/nanohttpd/blob/master/core/src/main/java/org/nanohttpd/protocols/http/response/Response.java#L259

Looks like someone was coding drunk, either in our team or even yourself. Will investigate and fix when possible.

**Comment by LordFokas** [comment]
@jtn-d please check if this still happens, should be fixed now.
