### ISSUE TITLE
Timeout in Nanohttpd Server Android

### ISSUE THREAD

**Issue by abdymalikmulky** [NanoHttpd/nanohttpd#399]
How to set a timeout in NanoHttpd Server, and retrieve callback from timeout ?

**Comment by LordFokas** [comment]
You have to be more specific. We're more than glad to help our users, but we need details.

**Comment by abdymalikmulky** [comment]
ok, i want to set timeout for nanohttpd server, let say timeout is 10 second , when no more interaction to server untill 10 second i want to stop() the server and got callback when the timeout is up. @LordFokas

**Comment by LordFokas** [comment]
That's not really in NanoHTTPD's global use case... the correct way to do it is exactly what you did -- create your own solution. We are in a very fierce struggle between code minimization and feature implementation, and cannot afford to ship a feature that only a few users will ever use...

**Comment by LordFokas** [comment]
I'm closing this. If you still have questions about this topic you can keep replying.
