### ISSUE TITLE
The NanoHTTPD cached file path open failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by suntabu** [NanoHttpd/nanohttpd#402]
When I post a file to NanoHTTPD, I got a file path where the file cached.
But failed to open the file with this path.

/data/data/com.XXXXX.webserver/cache/NanoHTTPD--46961158: open failed: ENOENT (No such file or directory)

**Comment by LordFokas** [comment]
We need more detail in order to help.
This seems to depend on the current working dir, filesystem dir structure, path construction (that data/data/ seems fishy), case sensitivity, etc.

Please provide more details if you're still interested in obtaining help for this issue, or close it otherwise.

**Comment by suntabu** [comment]
@LordFokas  Thanks for replying.
I'm making a file server on Android phone by nanohttpd. Sorry about missing running on Android phone information.

1.  when I upload a file to phone.  At debug mode I get this file's cache path as  

>   /data/data/com.XXXXX.webserver/cache/NanoHTTPD--46961158。


Where I get this path:
 
![image](https://cloud.githubusercontent.com/assets/7839044/21413386/cffd8b74-c831-11e6-8269-da9c38ee8dcc.png)

2. Then I use this path to download this file, but get a **open failed: ENOENT (No such file or directory)** exception.

3. On Android phone, the NanoHttpd's cache directory is same to app's directory like **/data/data/com.XXXXX.webserver/cache**

4. The current working direcotry of NanoHttpd on android phone is not sure .

5.  the code for downloading response:
``` java
    @NonNull
    public static NanoHTTPD.Response getDownloadFileResponse(String filePath) {
        File file = new File(filePath);
        try {
            ConsoleContent.append("download... " + filePath);
            FileInputStream fin = new FileInputStream(file);
            NanoHTTPD.Response response = NanoHTTPD.newFixedLengthResponse(NanoHTTPD.Response.Status.OK, "application/octet-stream", fin, file.length());
            response.addHeader("Content-disposition", String.format("attachment; filename=%s", file.getName()));
            return response;
        } catch (FileNotFoundException e) {
            e.printStackTrace();
            ConsoleContent.append("download error: " + e.getMessage());
            return NanoHTTPD.newFixedLengthResponse(NanoHTTPD.Response.Status.INTERNAL_ERROR, NanoHTTPD.mimeTypes().get("md"), e.getMessage());
        }
    }
```

**Comment by LordFokas** [comment]
Did you check that the directory and the file do exist?

**Comment by suntabu** [comment]
@LordFokas 
Yes, because my phone is not rooted, so I can not check it by file explorer. 
I used the method below to print the file infos of app's cache directory and the nanohttpd temp file was there.
![image](https://cloud.githubusercontent.com/assets/7839044/21427440/9d0c1902-c88f-11e6-8802-dfb7fecbebe4.png)

And in the debug mode, the nanohttpd received file's byte length was equal to the uploaded file's length, so I think the file was actually there. 

I've also tested the **getDownloadFileResponse** method and downloaded the log file in the cache dir successfully.

**Comment by LordFokas** [comment]
print that info in the catch, so that you check the file is there **WHEN** the error occurs.

**Comment by suntabu** [comment]
I found out why this happened.
I misunderstood the usage of temp file and sorry for misused of temp file.
![image](https://cloud.githubusercontent.com/assets/7839044/21446347/f5b491a4-c8ff-11e6-8982-72868c3863e3.png)

![image](https://cloud.githubusercontent.com/assets/7839044/21446463/515a21bc-c901-11e6-9710-8160cd6ae0e7.png)

![image](https://cloud.githubusercontent.com/assets/7839044/21446472/6a7c5994-c901-11e6-89b0-96a7c9d761ff.png)


So when I received a file, I should save it by myself instead of by using temp file.

**Comment by suntabu** [comment]
I found out why this happened.
I misunderstood the usage of temp file and sorry for misused of temp file.
![image](https://cloud.githubusercontent.com/assets/7839044/21446347/f5b491a4-c8ff-11e6-8982-72868c3863e3.png)

![image](https://cloud.githubusercontent.com/assets/7839044/21446463/515a21bc-c901-11e6-9710-8160cd6ae0e7.png)

![image](https://cloud.githubusercontent.com/assets/7839044/21446472/6a7c5994-c901-11e6-89b0-96a7c9d761ff.png)


So when I received a file, I should save it by myself instead of by using temp file.
