### ISSUE TITLE
while I tried to upload a very large file via NanoHttpd, it lost in getBoundaryPositions().

### ISSUE THREAD

**Issue by codejie** [NanoHttpd/nanohttpd#41]
I uploaded a file (>6 MB) onto the server (nanohttpd), after all data transmitted, the process lost in getBoundaryPositions() that it tried to find the boundary.
I just wanna upload one file, is there a quick way by nanohttpd?

**Comment by ritchieGitHub** [comment]
Has to be tested

**Comment by elonen** [comment]
The whole getBoundaryPositions() function needs an overhaul: it is apparently very slow for big uploads due to get() for every byte. See #112 .
