### ISSUE TITLE
Nanolets

### ISSUE THREAD

**Issue by ShrikantBadwaik-007** [NanoHttpd/nanohttpd#418]
Unable to pass argument to addRoute class field.
addRoute("/test", new Handler(container));
like this.
addRoute is allowing only following implementation. 
addRoute("/test", Handler.class);

Any help?

**Comment by LordFokas** [comment]
I think the point is that you pass a handler class and not an instance, and it will create an instance for you for every request.

**Comment by ShrikantBadwaik-007** [comment]
I got that. But I think this implementation **does not gives call to constructor(parameterized)**.
addRoute("/test", Handler.class);

But I am performing below operation in my parameterized constructor.
**public Handler(Container contain, String endPoint) {
        this.contain = contain;
        this.endPoint = endPoint;
        parser = new Parser(contain);
        pub = parser.parse();
    }**

And putting above code in parameterless constructor does not solve the problem which later gives me NULLPOINTEREXCEPTION in this method **Response get(UriResource uriResource, Map<String, String> urlParams, IHTTPSession session)** if I try to use any of the fields. Further more if I remove parameterless constructor it throws exception that Handler does not contain zero argument constructor.

So I can't remove parameterless constructor and I want to perform above operation.

**Comment by ShrikantBadwaik-007** [comment]
never mind. I solved the issue. 
Thank you.

**Comment by CreaRo** [comment]
How was this solved? Stuck at exactly this.

**Comment by CreaRo** [comment]
Was able to do so by cloning and changing the part where object instantiation is happening. The is the re-written part : 

                    Constructor<?> constructor = handler.getDeclaredConstructors()[0];
                    constructor.setAccessible(true);
                    Object object = constructor.newInstance(initParameter);

This now calls the paramaterized constructor. Can be closed for now - but not sure if this is the way it was meant to be or if I've done this in a hacky way.
