### ISSUE TITLE
Some enhancement propositions

### ISSUE THREAD

**Issue by LordFokas** [NanoHttpd/nanohttpd#42]
I have some enhancements to propose, in order to provide the user with more power and flexibility.

I was going to propose sending the HTTPSession object instead of all those args in NanoHTTPD.serve(), but I see you already did that.

Since I'm using NanoHTTPD to make the server side of a browser game, I need the serve() method to receive the client IP address. This is something I implemented myself easily, but other users may find useful as well.

Finally, adding Cookie-handling methods to the HTTP session object would be really useful.

**Comment by elonen** [comment]
Looks like remote-addr and cookies, as described here, are supported in current version. Closing this now. Feel free to reopen if necessary.
