### ISSUE TITLE
Android nanohttp server, not able to play large video

### ISSUE THREAD

**Issue by DeepsUttekar** [NanoHttpd/nanohttpd#425]
Hi All,

I am using nano http in android for local video streaming. But it fails to receive range and as vide file is large it tries to send complete file and it timeouts.

can some one please help me

**Comment by LordFokas** [comment]
There have been several similar questions here before. Please browse the existing issues, you might find solutions there.

I'm closing this unless this proves to be completely unrelated to those issues.

**Comment by DeepsUttekar** [comment]
I have searched a lot and seems that ppl have removed nanohttp and moved to Android async or nodejs. So wanted to check if nanohttp has solution for this issue

**Comment by ShrikantBadwaik-007** [comment]
@DeepsUttekar did you solved the issue?

**Comment by DeepsUttekar** [comment]
no im not able to solve this issue... planning to switch to android async

**Comment by Marx-Hong** [comment]
@DeepsUttekar have you solved it?thanks
