### ISSUE TITLE
impossible to get post data

### ISSUE THREAD

**Issue by openmotion** [NanoHttpd/nanohttpd#427]
hello

i want to send data with php in post but i can't receive the value in android

PHP CODE
```
$url = 'http://192.168.0.42/api';
 

// set post fields
$post = [
    'username' => 'user1'
];

$ch = curl_init($url);
curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-Type: application/json; charset=utf-8","Accept:application/json, text/javascript, */*; q=0.01")); 
curl_setopt($ch, CURLOPT_VERBOSE, true);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_PORT, '5000');
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
curl_setopt($ch, CURLOPT_POSTFIELDS, array('json'=>json_encode($post)));
curl_setopt($ch, CURLOPT_POST, true);
$response = curl_exec($ch);
curl_close($ch);
var_dump($response);
curl_close ($ch);
```

ANDROID CODE

```
` @Override
        public Response serve(IHTTPSession session) {
            String answer = "hello boy";

            System.out.println( session.getMethod() + " " + session.getParms() );

            Map<String, String> files = new HashMap<String, String>();
            Method method = session.getMethod();
            if (Method.PUT.equals(method) || Method.POST.equals(method)) {
                try {
                    session.parseBody(files);
                } catch (IOException ioe) {
                    return new Response(Response.Status.INTERNAL_ERROR, MIME_PLAINTEXT, "SERVER INTERNAL ERROR: IOException: " + ioe.getMessage());
                } catch (ResponseException re) {
                    return new Response(re.getStatus(), MIME_PLAINTEXT, re.getMessage());
                }
            }
            // get the POST body
            String postBody = session.getQueryParameterString();
            // or you can access the POST request's parameters
            String postParameter = session.getParms().get("parameter");
            Log.w("Httpd", "postBody "+postBody);
            Log.w("Httpd", "postParameter "+postParameter);

            final HashMap<String, String> map = new HashMap<String, String>();

            final String json = files.get("postData");

            Log.w("Httpd", "json "+json);

            return new NanoHTTPD.Response(answer);
        }
```

**Comment by turok1997** [comment]
The same issue. I have already found bug in the code and corrected it. But I don't know how to make contribution, as I am new at git and this Version Control Systems.
Can someone please help me to make my first contribution? What should I do after correcting bug? I have created patch, but I am not sure that I made it right.

**Comment by LordFokas** [comment]
@turok1997 you have to commit to your own repository, and then send us a Pull Request. One of us (likely me) will then review the code and either merge it into our code base or close the PR / ask for modifications if we don't approve it.

@openmotion I have no clue what's going on, but your code seems a bit fishy. Investigation is required.

**Comment by turok1997** [comment]
Looking through the code and debugging I came to thought that before calling getParms() or getParameters(), we need to call parseBody(). Just don't understant is this bug or feature? 😄 
I tried to call parseBody(getParams()), and this worked.

**Comment by LordFokas** [comment]
Ah yes, that's just plain bad code that we have in 2.3, I'm fixing that on 3.0 but it isn't ready yet...

**Comment by LordFokas** [comment]
Just so it's terribly explicit:

For versions prior to 3.0.0 you *HAVE* to manually invoke `parseBody( ... )` for `PUT`, `POST` and `PATCH` requests, no matter if you want to read the body data or not. (if you don't it will corrupt the next request from the same client).

**Comment by crearo** [comment]
Hope 3.0.0 is coming!
