### ISSUE TITLE
android: could nanohttpd serve only be accessible on the same wifi network

### ISSUE THREAD

**Issue by veetowner** [NanoHttpd/nanohttpd#430]
I am trying to use nanohttp in android. is the server instance only accessible from the same wifi network? could it be accessible outside of my wifi if I can give him a static IP?

**Comment by LordFokas** [comment]
It can be accessible outside your local network if you configure your router to forward those ports to your android's address (which you may have to make static, yes). By default none of that is configured, obviously, so your NanoHTTPD server is only accessible in whatever local networks your device is.

I'm going to close this but feel free to continue the discussion if you have any more questions on the topic :)
