### ISSUE TITLE
Problems to load fonts

### ISSUE THREAD

**Issue by ivandiazmolina** [NanoHttpd/nanohttpd#439]
I have problems when I try to load fonts. I have this error message.

"Failed to decode downloaded font: http://localhost:9080/fonts/Karla-Bold.woff", source: http://localhost:9080/index.html#/ (0)

"OTS parsing error: incorrect file size in WOFF header", source: http://localhost:9080/index.html#/ (0)

I have this line in serve method 

return newFixedLengthResponse(NanoHTTPD.Response.Status.OK, "application/font-woff", answer);

var answer is a String with file content

Anyone have any solutions?. Thanks in advance

**Comment by F-Medeiros** [comment]
Qual foi a solução?
