### ISSUE TITLE
Make artifacts available on Maven Central

### ISSUE THREAD

**Issue by admackin** [NanoHttpd/nanohttpd#44]
Since this is an embeddable server, it would be very handy to make it available on Maven Central (or somewhere - please let me know if it is on another public maven repo which I haven't been able to find)

**Comment by jsumners** [comment]
I'll chime in with another +1

**Comment by jsumners** [comment]
I'll do even better than a +1...

Review this commit -- https://github.com/jsumners/nanohttpd/commit/ad2bcfaaf6455c876ac7315010c0a1e1c1ce97cc

It add support for deploying the nanohttpd modules to a Maven repository that is itself a Git repository. In particular, it is deployed to my Maven repository -- https://github.com/jsumners/mvn-repo

You can test it out by adding the following to a project's pom.xml:

```xml
  <dependencies>
    <dependency>
      <groupId>fi.iki.elonen</groupId>
      <artifactId>nanohttpd</artifactId>
      <version>2.1.0</version>
    </dependency>
  </dependencies>

<repositories>
    <repository>
      <id>jsumners-github-releases</id>
      <url>https://github.com/jsumners/mvn-repo/raw/master/releases/</url>
    </repository>
    <repository>
      <id>jsumners-github-snapshots</id>
      <url>https://github.com/jsumners/mvn-repo/raw/master/snapshots/</url>
    </repository>
  </repositories>
```

Note: I had to use `mvn deploy -Dmaven.test.skip=true` to get the packages to compile and deploy. The integration tests were failing because the port was already open (though 8192 is not a port in use by anything other than those tests on my system).

**Comment by nullEuro** [comment]
+1

**Comment by swengconsultant** [comment]
Hi jsumners,

Do you know how I can use your repo in gradle. I have setup the build.gradle as shown below however I continue to get the error: Failed to find:'fi.iki.elonen:nanohttpd:2.1.0' ?

repositories {
    maven {
        url "https://github.com/jsumners/mvn-repo/tree/master/releases"
    }
}

dependencies {
      compile 'fi.iki.elonen:nanohttpd:2.1.0'
}

**Comment by jsumners** [comment]
Sorry, I don't use Gradle.

On Tuesday, February 10, 2015, swengconsultant <notifications@github.com>
wrote:

> Hi jsumners,
>
> Do you know how I can use your repo in gradle. I have setup the
> build.gradle as shown below however I continue to get the error: Failed to
> find:'fi.iki.elonen:nanohttpd:2.1.0' ?
>
> repositories {
> maven {
> url "https://github.com/jsumners/mvn-repo/tree/master/releases"
> }
> }
>
> dependencies {
> compile 'fi.iki.elonen:nanohttpd:2.1.0'
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NanoHttpd/nanohttpd/issues/44#issuecomment-73817869>.
>


-- 
James Sumners
http://james.sumners.info/ (technical profile)
http://jrfom.com/ (personal site)
http://haplo.bandcamp.com/ (band page)

**Comment by peterjanes** [comment]
@swengconsultant Use the `.../raw/...` version of the URL, as [shown in this comment](https://github.com/NanoHttpd/nanohttpd/issues/44#issuecomment-68505667).

**Comment by swengconsultant** [comment]
@peterjanes That worked a treat, many thanks.

**Comment by arndtjenssen** [comment]
@jsumners Thanks, works fine !!

**Comment by ritchieGitHub** [comment]
just came over this project and i also would like to see it in central, thats not so difficult. 
I have done it for many projects, so i will do the work nessesary.

The biggest change nessesary will be that the groupId must change! The groupId must be a reverse website where the project is visible and the names of the developers are also visible.

io.github.nanohttpd or com.github.nanohttpd would be ok or any other website where you can place a html with the project description and the developer list.

So let me know the groupId you want, and i will create a pull request with the required changes to deploy to central.

**Comment by jitpack** [comment]
Btw, you can also get NanoHttpd as a maven/gradle dependency using JitPack:  https://jitpack.io/#NanoHttpd/nanohttpd/Release-2.1.0 

Tried and it works:)

**Comment by ritchieGitHub** [comment]
all good and well, but you can't (and may not) deploy something to central that has a link to another repository.  I will start this weekend, and use the groupId "com.nanohttpd".

**Comment by ritchieGitHub** [comment]
ok, done made a pull request for the needed changes in the future, made a release of the current state
		<groupId>com.nanohttpd</groupId>
		<artifactId>nanohttpd-project</artifactId>
		<version>2.1.1</version>
so this issue can be closed
@psh please take this pull request and register at oss.sonatype.org and create yourself a public gpg key. When you have these you can do releases yourself. Contact me if you need help!

**Comment by sean0728** [comment]
For those asking about Gradle:

    compile group: 'com.nanohttpd', name: 'nanohttpd', version: '2.1.0'

or

    compile 'com.nanohttpd:nanohttpd:2.1.0'

Where `2.1.0` is the desired version number.

**Comment by sean0728** [comment]
To include the `webserver`, `websocket`, or `markdown-plugin`, use the following:

    compile 'com.nanohttpd:nanohttpd-webserver:2.1.0'

Where `webserver` is the desired extra, and `2.1.0` is the desired version.

**Comment by ritchieGitHub** [comment]
Attention all coming versions will use an other groupId (org.nanohttpd) see #174

**Comment by Muxagen** [comment]
Hey guys. Thank you for your effort on this. I spent quite a lot of time looking for the latest dependencies: http://nanohttpd.org/nanohttpd-webserver-markdown-plugin/dependencies.html
Can you make this availible on github readme/wiki to make life easier for others?)

**Comment by ritchieGitHub** [comment]
Yes, planning to write it in the readme this weekend

**Comment by Muxagen** [comment]
@ritchieGitHub 
`compile 'com.nanohttpd:nanohttpd-webserver:2.1.0'` worked fine
`compile 'org.nanohttpd:nanohttpd-webserver:2.2.0'` (tried 2.2.0-SNAPSHOT, 2.2.+, etc) 
- could not be resolved by gradle. Am i doing something wrong?

**Comment by ritchieGitHub** [comment]
you probably have to add the
