### ISSUE TITLE
Version 3 on mavenCentral?

### ISSUE THREAD

**Issue by Gillardo** [NanoHttpd/nanohttpd#440]
On the readme page it says

> import org.nanohttpd.NanoHTTPD;
>     // NOTE: If you're using NanoHTTPD < 3.0.0 the namespace is different,
>     //       instead of the above import use the following:
>     // import fi.iki.elonen.NanoHTTPD;

But version 3 doesnt seem to be available on mavenCentral?  I am using this in an android application and this works

`compile "org.nanohttpd:nanohttpd:2.3.1"`

but this doesn't (because i dont think it is there)

`compile "org.nanohttpd:nanohttpd:3.0.0"`

Any news when version 3 is going to be on mavenCentral?  I would like to use the NanoWSD class

**Comment by LordFokas** [comment]
You can use NanoWSD with 2.3.1
3.0.0 isn't ready yet, and I haven't been working on it lately.
