### ISSUE TITLE
Is webscoket multithreaded

### ISSUE THREAD

**Issue by HussainYousuf** [NanoHttpd/nanohttpd#446]
I am sorry if the answer is obvious but I am really new to this.
I want to know the behaviour of onMessage function. if multiple clients sends message simultaneously will each client spawn a new websocket thread?
Thank You

**Comment by HussainYousuf** [comment]
Yup multithreaded

**Comment by LordFokas** [comment]
To put this more formally, each client is connected on a different thread **as of now (but this may be subject to change)**, be it plain HTTP or more advanced sub-protocols like websockets (currently the only sub-protocol we're shipping, but there were people with their eyes set on SSE here). This means care must be taken when accessing centralized data and code.
