### ISSUE TITLE
How to parse a "gzipped" request body in IHTTPSession session?

### ISSUE THREAD

**Issue by divyam** [NanoHttpd/nanohttpd#450]

**Comment by bingghost** [comment]
InputStream inputStream = session.getInputStream();

public static String uncompress(InputStream in) {
    ByteArrayOutputStream out = new ByteArrayOutputStream();
    try {
        GZIPInputStream ungzip = null;
        try {
            ungzip = new GZIPInputStream(in);
        } catch (IOException e) {
            e.printStackTrace();
        }

        byte[] buffer = new byte[256];
        int n;
        while ((n = ungzip.read(buffer)) >= 0) {
            out.write(buffer, 0, n);
        }
    } catch (IOException e) {

    }

    String result = new String(out.toByteArray());
    return result;
}

**Comment by bingghost** [comment]
`public static String uncompress(InputStream in) {


    ByteArrayOutputStream out = new ByteArrayOutputStream();
    try {
        GZIPInputStream ungzip = null;
        try {
            ungzip = new GZIPInputStream(in);
        } catch (IOException e) {
            e.printStackTrace();
        }

        byte[] buffer = new byte[256];
        int n;
        while ((n = ungzip.read(buffer)) >= 0) {
            out.write(buffer, 0, n);
        }
    } catch (IOException e) {

    }

    String result = new String(out.toByteArray());

    return result;
}  `

**Comment by bingghost** [comment]
`
@Override
public Response serve(IHTTPSession session) {

    InputStream inputStream = session.getInputStream();
    uncompress(inputStream);
}

public static String uncompress(InputStream in) {
    ByteArrayOutputStream out = new ByteArrayOutputStream();
    try {
        GZIPInputStream ungzip = null;
        try {
            ungzip = new GZIPInputStream(in);
        } catch (IOException e) {
            e.printStackTrace();
        }

        byte[] buffer = new byte[256];
        int n;
        while ((n = ungzip.read(buffer)) >= 0) {
            out.write(buffer, 0, n);
        }
    } catch (IOException e) {

    }

    String result = new String(out.toByteArray());

    return result;
}  
`

**Comment by bingghost** [comment]
1. uncompress gzip data
```java
public static String uncompress(InputStream in) {
    ByteArrayOutputStream out = new ByteArrayOutputStream();
    try {
        GZIPInputStream ungzip = null;
        try {
            ungzip = new GZIPInputStream(in);
        } catch (IOException e) {
            e.printStackTrace();
        }

        byte[] buffer = new byte[256];
        int n;
        while ((n = ungzip.read(buffer)) >= 0) {
            out.write(buffer, 0, n);
        }
    } catch (IOException e) {

    }

    String result = new String(out.toByteArray());
    return result;
}
```

2. parse gzipped request body
```java
@Override
public Response serve(IHTTPSession session) {
    InputStream inputStream = session.getInputStream();
    String result = uncompress(inputStream);
}
```

**Comment by LordFokas** [comment]
Weird. I though NanoHTTPD handled that automatically?
