### ISSUE TITLE
WebSocket session is closed after 1 minute

### ISSUE THREAD

**Issue by rahmanusta** [NanoHttpd/nanohttpd#462]
I use nanohttpd with Websocket. I set timeout as 5 minutes but it closes websocket session after 1 minute. I  give 5 * 60 * 1000 to the start method. What can be the reason?

Thanks

**Comment by LordFokas** [comment]
you need to ping the sockets, either from the client side or from the server. If there isn't a heartbeat packet one of the sides will eventually declare the socket as dead and close it even though the connection is still open and functional.

**Comment by rahmanusta** [comment]
Wow cool. Thank you @LordFokas

**Comment by LordFokas** [comment]
Just to leave a bit more info here, these sockets, just like any TCP sockets, are based on a blocking input for the read function, which has a timeout, which will blow up on your face if you exceed the timeout without them having anything to read.

**Comment by rahmanusta** [comment]
I was hoping that websocket session will be available until http session's timeout.
