### ISSUE TITLE
Response transformed into 500 Internal Server Error

### ISSUE THREAD

**Issue by jmartine2** [NanoHttpd/nanohttpd#474]
If I return a response status code of 200 OK, the client receives the response fine. However, if I return any error response (such as 401 UNAUTHORIZED), the client receives a 500 INTERNAL SERVER ERROR response, with no body.

Here is an example of where I return a perfectly valid 401 response in my return statement from my overridden serve() method:

![401response](https://user-images.githubusercontent.com/19214902/34850452-c150b7ee-f6da-11e7-8b6b-20da57c69a17.PNG)

Here is the response my client receives:

> HTTP/1.1 500 Internal Server Error
> Connection: close
> Content-Length: 0

I am using nanohttpd version 2.3.1, but it also happened with 2.3.0

What could be causing this?

**Comment by LordFokas** [comment]
Something may be causing an exception, either in your code or ours, that the http server catches and then properly responds using a 500. Can you investigate if it's on your code, please?

**Comment by jmartine2** [comment]
I sincerely apologize. I had forgotten that I had a proxy service running between the client and my nanohttpd service. It was eating the 401 and returning a 500 to the client. My bad.
