### ISSUE TITLE
Response.send does not handle streaming responses correctly?

### ISSUE THREAD

**Issue by ntuckerxx** [NanoHttpd/nanohttpd#51]
I'm attempting to use NanoHTTPD for streaming responses by creating a PipedInputStream/PipedOutputStream pair, starting a thread to write to the PipedOutputStream and then constructing the NanoHTTPD.Response using the PipedInputStream.  Unfortunately, due to the following code, NanoHTTPD decides there isn't much data to be sent, writes an incorrect Content-Length header, then closes the InputStream:

                int pending = data != null ? data.available() : -1; // This is to support partial sends, see serveFile()
                if (pending > 0) {
                    pw.print("Connection: keep-alive\r\n");
                    pw.print("Content-Length: "+pending+"\r\n");
                }

The problem is that when 'data' is a PipedInputStream, data.available() is not necessarilyi indicative of the entire length of the stream, as all the data may not yet be available for reading.

I have seen comments to the effect that NanoHTTPD has been improved for streaming, but I don't see how this is possible unless I'm going about it all wrong.  I've hacked up my own Response that overrides send() and it's working, but I'm curious what NanoHTTPD maintainers have to say about the issue.

**Comment by ritchieGitHub** [comment]
Should be solved together with #94
