### ISSUE TITLE
no versions found for {org.nanohttpd:nanohttpd:[0,2.1.1]=[]}

### ISSUE THREAD

**Issue by tbradellis** [NanoHttpd/nanohttpd#512]
This gradle build fails. Caused by: org.gradle.api.GradleException: Invalid passOnly verification - no versions found for {org.nanohttpd:nanohttpd:[0,2.1.1]=[]}

This seems to have something to do with the name changes, but I can't get this to build.

I've also tried with com.nanohttpd (and com.nanohttpd-webserver, org.nanohttpd-webserver), as alluded to here;
https://github.com/NanoHttpd/nanohttpd
None of those dependencies work.

What is the actual dependency configuration?

Is there a repository for fi.iki.* somewhere?

**Comment by LordFokas** [comment]
This was that repository. We then changed the packaging to `org.nanohttpd.*`
