### ISSUE TITLE
Content-Disposition: attachment not work for txt file in Kindle

### ISSUE THREAD

**Issue by ChenZhongPu** [NanoHttpd/nanohttpd#526]
I am using `nanohttpd` in Android as a http server.

         Response response = NanoHTTPD.newChunkedResponse(Response.Status.OK, mime, fis);
         response.addHeader("Content-Disposition", "attachment; filename=\"" + WebUtil.localFileName +"\"");
         return response;

When the file `mime`  is  `application/x-mobipocket-ebook` (I have updated the mimetypes file), it can download directly in `Kindle`. But when it is `plain/txt`, it will display it inline.

**Comment by ChenZhongPu** [comment]
I would like to force it to download instead of displaying.

**Comment by LordFokas** [comment]
The mime is the `Content-Type` response header. That should be enough to force a download, since it's a mime browsers don't typically know how to display.
