### ISSUE TITLE
How to run code from a HTML function?

### ISSUE THREAD

**Issue by SirMangler** [NanoHttpd/nanohttpd#539]
Example HTML: `<button onclick="myFunction()">Click me</button>`

Javascript seems to do it like so: `object.addEventListener("click", myScript);`

My main intention is to receive input from a HTML page and execute a method, namely buttons and text input.

**Comment by NoahAndrews** [comment]
This has nothing to do with NanoHTTPD, and you're better off asking on StackOverflow.

That being said, there's no such thing as an "HTML function". What your example HTML will do is run the JavaScript function defined like so:

```
function myFunction {
    // do stuff
}
```

**Comment by SirMangler** [comment]
Thanks for your response. After some research I understand now that most websites handle that kind of action through JavaScript (which obviously isn't related to this library), which is triggered through the HTML.
