### ISSUE TITLE
Can't access the webpage on my laptop connected to my android server through mobile hotspot

### ISSUE THREAD

**Issue by Haider8** [NanoHttpd/nanohttpd#556]
I have created the android server on my mobile phone and on the same phone I have opened my hotspot. Upon connecting my laptop to my mobile hotspot I can't access that webpage by my mobile's ip address. Please help me how I can do that?

Note: Right now I can only access the webpage on my mobile's localhost.

**Comment by crearo** [comment]
Check the IP address of your mobile. 
Check the port you've started the hotspot at
In your browser go to http://ip:port/

**Comment by simple565** [comment]
I have the same problem，have you  fixed it?

**Comment by AndreasGabel** [comment]
Same here, with SimpleWebServer implementation only localhost seems to work, but no access through IP address (e.g. in browser), even on the same device. ERR_CONNECTION_REFUSED error is shown in browser and says "[IP address] refused to connect.". Is this a result of having no CORS settings set (cors = null) or should it work anyway?

Edit: cors set to "http://192.168.43.151" (host device ip address) does not make a difference.

**Comment by Haider8** [comment]
Try setting your server on 0.0.0.0 rather then localhost in your code and
check carefully that you enter your mobile's private ip in your browser.
This worked for me.

**Comment by AndreasGabel** [comment]
You are right, I just figured it out as well: setting 0.0.0.0 or null as hostname works fine. Thank you anyway.
