### ISSUE TITLE
Need version 3.0.0 for android

### ISSUE THREAD

**Issue by trnchawla** [NanoHttpd/nanohttpd#571]
Am unable to find, 3.0.0 version on maven repo, please help getting the link so that I can add dependency into my project as there are few issues seems to be fixed in 3.0.0.

Also if there is no uploaded version of 3.0.0, please let me know the latest branch which I can pull and build my self and any steps to build that.

**Comment by trnchawla** [comment]
I downloaded the master, builded it and used it.

**Comment by akanshSirohi** [comment]
@trnchawla Can you please share the built version of it with me??? 
Or tell me how can I built it by myself..?
