### ISSUE TITLE
Not able to access without port number(:8080)

### ISSUE THREAD

**Issue by kishansinghpanwar** [NanoHttpd/nanohttpd#612]
Hi,
I have searched everywhere but can't figure out how to do this.
Basically, I want to remove the **:8080** from my URLS so my portal will be ready for deployment. When I type in http://191.161.43.159/ I want to access the portal, rather than typing in http://191.161.43.159:8080

How does one do this?

Any advice would be great!

Thanks in advance,
Kishan Singh

**Comment by ItsHarper** [comment]
To do this, pass in `80` as the parameter to the `NanoHTTPD` constructor, rather than `8080`. Port 80 is the port that browsers default to for HTTP (not HTTPS).

**Comment by kishansinghpanwar** [comment]
@NoahAndrews Thanks for the suggestion, but whenever I'm trying to provide the port number different than 8080, I'm getting errors while starting the server connection and same result I got when I tested with "**80**" port.

Getting error while binding **InetSocketAddress** to **ServerSocket**,  here are the code:
```
try {
    myServerSocket.bind(hostname != null ? new InetSocketAddress(hostname, myPort) : new InetSocketAddress(myPort));
    hasBinded = true;
} catch (IOException e) {
    this.bindException = e;
    return;
}
```
And here are the error logs :
```
W/System.err: java.net.BindException: bind failed: EACCES (Permission denied)
W/System.err:     at libcore.io.IoBridge.bind(IoBridge.java:103)
W/System.err:     at java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java:157)
W/System.err:     at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:427)
W/System.err:     at java.net.ServerSocket.bind(ServerSocket.java:377)
W/System.err:     at java.net.ServerSocket.bind(ServerSocket.java:331)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
W/System.err: Caused by: android.system.ErrnoException: bind failed: EACCES (Permission denied)
W/System.err:     at libcore.io.Linux.bind(Native Method)
W/System.err:     at libcore.io.ForwardingOs.bind(ForwardingOs.java:60)
W/System.err:     at libcore.io.IoBridge.bind(IoBridge.java:99)
W/System.err: 	... 6 more
```

I have tried to find the solution for this error and found this error appears when the app don't have Internet permission(`android.permission.INTERNET`) or access network state permission(`android.permission.ACCESS_NETWORK_STATE`), but I have already defined both permissions in the AndroidManifest file.

**Comment by ItsHarper** [comment]
Oh, binding to ports below 1024 typically requires root permissions on Linux, so you'd have to root your phone for that to work on Android. If you're looking to distribute the app widely, you're going to be stuck with 8080.

I actually work for a company that sells an Android device that you [access over port 8080](https://docs.revrobotics.com/rev-control-system/control-hub-gs/connect-to-the-control-hub-robot-control-console#web-browser), and I don't think we really get any complaints about having to specify the port.

**Comment by kishansinghpanwar** [comment]
Thanks for your help.
Yes, I also think so this might be a reason, but I think instead of rooting my phone, I can bind the app with the framework as System App, and I think in that case the app have access of 80 port.
