### ISSUE TITLE
What are nanohttpd's thoughts on the following features

### ISSUE THREAD

**Issue by yaronyg** [NanoHttpd/nanohttpd#63]
I am building a HTTP server to run inside of a web browser as part of the https://peerly.codeplex.com/ peer to peer web project. I'm using NanoHTTPD because it runs both on the desktop and in Android. But there are a couple of features that are missing that I wanted to know if nanohttpd is interested in.

Chunked Transfer from Clients - The HTTP/1.1 spec allows both clients and servers to send chunked transfers whenever they want and HTTP/1.1 servers are required to support it. I see that chunked transfer for responses was just added but what about chunked transfer for requests? My use case involves pushing large pieces of parsed data like json between phones so we really don't want to have to manifest them in memory in order to get an accurate data size.

Content Coding - The same vein we would really want support for Content Coding like GZIP. Peer to peer environments are often bandwidth constrained and we move a lot of easily compressible content like JSON around.

Enum free processing for methods and response codes - Right now methods and response codes are identified by enums. But a big part of our project is to provide a generic HTTP environment that can support experimental work with new methods and response codes. So we would like versions of the interface that just provides the method as a string and accepts the response code as a number plus a description.

The last one is pretty easy and unless there are objections at some point I'll just submit a push request for it that should be compatible with the existing interfaces. But the first two are probably not implementable in a way that is compatible with the existing interfaces since they break what's in the input stream in a pretty fundamental way. There are ways to paper over this but only at the cost of buffering everything in memory (or on disk or somewhere) and that sounds like a really bad idea.

That's why I'm bringing this issue up here because I want to understand what y'all are thinking about these ideas and if you have any interest in seeing them tackled given that they probably require interface changes.

    Thanks,

      Yaron

**Comment by voltagex** [comment]
Was there ever an example of implementing GZIP?

**Comment by ritchieGitHub** [comment]
I thinkt this issue is just to big, I created an issue #177 for the compression. @yaronyg please do seperate request for every feature. It is very difficult to synchronise issues that include a whole bunch of featue/requests
