### ISSUE TITLE
Question: Websocket in nanohttpd?

### ISSUE THREAD

**Issue by ericfong** [NanoHttpd/nanohttpd#74]
Question: Is it possible or any simple solution like "one additional jar/java class" to enable websocket in nanohttpd server?

**Comment by AmitKulkarni23** [comment]
Could you please elaborate on what goes in the User class.
And what about the client-side implementation(javascript)?

**Comment by faywong** [comment]
@felipebutcher @PathikDevani Thanks for your work, i also ran into this issue today.

@AmitKulkarni23 
In my case, i use the html5 websocket in javascript which runs in my chrome browser(version 47.0.2526.106 (64-bit), on mac os).

My javascript code:
```javascript
var exampleSocket = new WebSocket("ws://10.15.101.152:9092/", "protocolOne");
                        exampleSocket.onopen = function (evt) {
                            exampleSocket.send("Here's some text that the server is urgently awaiting!");
                        };

                        exampleSocket.onclose = function (evt) {
                            console.log(evt);
                        };

                        exampleSocket.onmessage = function (evt) {
                            console.log(evt.data);
                        };

                        exampleSocket.onerror = function (evt) {
                            console.log(evt);
                        };
```

**Comment by xmanemra** [comment]
Can any one plz give me a example project.

**Comment by LordFokas** [comment]
@xmanemra you can find some samples here https://github.com/NanoHttpd/nanohttpd/tree/master/websocket/src/main/java/fi/iki/elonen/samples/echo

**Comment by xmanemra** [comment]
@LordFokas thanks. but i am little confusion about http server and websocket. 
Actually I want to send and receive messages from web client via android web socket. I already use nanohttpd in my android project. how i use nanohttpd-websocket like socket.io.

**Comment by LordFokas** [comment]
This is not exactly like socket.io, but it works on some of the same principles.
If you create a NanoWSD server you can handle WebSockets and HTTP on the same server.
There's a websocket creating method to create your own websockets (which you should override) and a method to serve HTTP requests (not `serve()`, I think it's `serveHttp()`)
You may need to manually ping the sockets.

**Comment by RoundSparrow** [comment]
instead of editing the code, you can call start(0) - the 0 timeout will disable the timeout.

**Comment by Loony04** [comment]
@pathikdevani Where to get WebSocket class?

**Comment by LordFokas** [comment]
Even though you can set the timeout to 0, pinging is a much better approach, and more powerful.
