### ISSUE TITLE
Collections.EMPTY_MAP maybe better.

### ISSUE THREAD

**Issue by gordonpro** [NanoHttpd/nanohttpd#75]
public Response serve(IHTTPSession session) {
        Map<String, String> files = new HashMap<String, String>();
        // Map<String, String> files = Collections.EMPTY_MAP; 

and IHTTPSession has an spell error. Map<String, String> getParms();

**Comment by ritchieGitHub** [comment]
spell error corrected but EMPTY map is not good here (it will be filled later)

**Comment by ritchieGitHub** [comment]
sorry, spell error also reverted! (backward compatibility)
