### ISSUE TITLE
Other Content-Types in POST

### ISSUE THREAD

**Issue by soulseekah** [NanoHttpd/nanohttpd#8]
Nano supports `multipart/form-data` and `application/x-www-form-urlencoded` with everything else ignored, unparsed. Would be good to actually be able to tap into the raw data for custom Content-Types and be able to process them in `NanoHTTPD` extensions.

Can provide patch if pull requests are actually accepted and applied.

**Comment by voltagex** [comment]
This is currently stopping me from accepting JSON posts with NanoHTTPD

**Comment by elonen** [comment]
Related to #99 .
Reading through the code, it appears to provide the raw POST body in a pseudo file called "postData" if content type is not `multipart/form-data` or `application/x-www-form-urlencoded` .

**Comment by ritchieGitHub** [comment]
@voltagex could you check if this issue can be closed?

**Comment by voltagex** [comment]
I don't think this issue adds anything to #99, it can probably be closed.
