### ISSUE TITLE
SERVER INTERNAL ERROR: 500

### ISSUE THREAD

**Issue by Worxfr** [NanoHttpd/nanohttpd#80]
I made test with NanoHTTPD, in an Android Application and a Raspberry PI.

And in each case, after receive my 200 response, after timer SOCKET_READ_TIMEOUT (5000ms), i receive an 500 Error from server...

![trace](https://f.cloud.github.com/assets/4269414/1607920/bcc2a464-54b1-11e3-8a19-c2ad0762a7eb.png)

**Comment by ritchieGitHub** [comment]
please could you test if the current version still has this "bug"?

**Comment by Worxfr** [comment]
My fix is already added ! 

https://github.com/NanoHttpd/nanohttpd/commits?author=Worxfr

**Comment by elonen** [comment]
Thanks @Worxfr !
