### ISSUE TITLE
SimpleWebServer: Content-Length response header is written twice

### ISSUE THREAD

**Issue by beckchr** [NanoHttpd/nanohttpd#87]
`SimpleWebServer.serveFile(...)` adds the `Content-Length` to the headers map, which it probably shouldn't.

The header is written first in `Response.send(...)` from the headers map and a second time in `Response.sendAsFixedLength(...)`.

**Comment by jtn-d** [comment]
This is still the issue or it has reoccured. Example below:

HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: origin,accept,content-type
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 151200
Connection: keep-alive
Content-Length: 84878
Content-Length: 84878
Content-Type: image/jpeg
Date: Fri, 7 Oct 2016 07:08:40 GMT
ETag: f00962f7

Unfortunately e.g. node http.get throws the exception for unexpected content length.
