### ISSUE TITLE
File Uploads Cause the App to crash with StackOverflowError

### ISSUE THREAD

**Issue by lordspace** [NanoHttpd/nanohttpd#91]
First, off great job with the project.
I think I found a glitch. When I try to upload a file the server crashes.

I used the following form to submit an upload to my android web server
`
<html>
<body>

	<form action="http://192.168.0.107:8181/" method="post" enctype="multipart/form-data">
		<label for="file">Filename:</label>
		<input type="file" name="file" id="file"><br>
		<input type="submit" name="submit" value="Submit">
	</form>

</body>
</html>

`12-26 06:38:07.868: E/AndroidRuntime(7292): FATAL EXCEPTION: NanoHttpd Request Processor (#2)
12-26 06:38:07.868: E/AndroidRuntime(7292): java.lang.StackOverflowError
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputStream.read(SequenceInputStream.java:201)
12-26 06:38:07.868: E/AndroidRuntime(7292): 	at java.io.SequenceInputSt
12-26 06:38:08.038: D/dalvikvm(7292): GC_FOR_MALLOC freed 393K, 39% free 4962K/8007K, external 0K/0K, paused 18ms
12-26 06:38:08.358: D/WindowManagerImpl(7292): finishRemoveViewLocked, mViews[0]: com.android.internal.policy.impl.PhoneWindow$DecorView@405224f8
`

Here is how I am using the server
`
package com.orbisius.serverapp;

import java.io.IOException;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Properties;

import android.net.wifi.WifiManager;
import android.os.Bundle;
import android.os.Handler;
import android.app.Activity;
import android.util.Log;
import android.view.Menu;
import android.widget.TextView;

public class MainActivity extends Activity {

	private static final int PORT = 8181;
	private TextView hello;
	private MyHTTPD server;
	private Handler handler = new Handler();

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);

		hello = (TextView) findViewById(R.id.hello);
	}

	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		// Inflate the menu; this adds items to the action bar if it is present.
		getMenuInflater().inflate(R.menu.main, menu);
		return true;
	}

	@Override
	protected void onResume() {
		super.onResume();

		TextView textIpaddr = (TextView) findViewById(R.id.ipaddr);
		WifiManager wifiManager = (WifiManager) getSystemService(WIFI_SERVICE);
		int ipAddress = wifiManager.getConnectionInfo().getIpAddress();
		final String formatedIpAddress = String.format("%d.%d.%d.%d",
				(ipAddress & 0xff), (ipAddress >> 8 & 0xff),
				(ipAddress >> 16 & 0xff), (ipAddress >> 24 & 0xff));
		textIpaddr.setText("Please access! http://" + formatedIpAddress 
				+ ":" + PORT + " or " + getLocalIpAddress() + ":" + PORT );

		try {
			server = new MyHTTPD();
			server.start();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	@Override
	protected void onPause() {
		super.onPause();
		if (server != null)
			server.stop();
	}

	public String getLocalIpAddress() {
		try {
			for (Enumeration<NetworkInterface> en = NetworkInterface.getNetworkInterfaces(); en.hasMoreElements();) {
				NetworkInterface intf = en.nextElement();
				
				for (Enumeration enumIpAddr = intf.getInetAddresses(); enumIpAddr
						.hasMoreElements();) {
					InetAddress inetAddress = (InetAddress) enumIpAddr.nextElement();
					
					if (!inetAddress.isLoopbackAddress()) {
						return inetAddress.getHostAddress().toString();
					}
				}
			}
		} catch (SocketException ex) {
			Log.e("Exception", ex.toString());
		}
		
		return null;
	}

	// https://github.com/NanoHttpd/nanohttpd
	private class MyHTTPD extends NanoHTTPD {
		public MyHTTPD() throws IOException {
			super(PORT);
		}

		@Override
		public Response serve(IHTTPSession session) {
			Map<String, List<String>> decodedQueryParameters = decodeParameters(session
					.getQueryParameterString());

			StringBuilder sb = new StringBuilder();
			sb.append("<html>");
			sb.append("<head><title>Debug Server</title></head>");
			sb.append("<body>");
			sb.append("<h1>Debug Server</h1>");

			sb.append("<p><blockquote><b>URI</b> = ")
					.append(String.valueOf(session.getUri())).append("<br />");

			sb.append("<b>Method</b> = ")
					.append(String.valueOf(session.getMethod()))
					.append("</blockquote></p>");

			sb.append("<h3>Headers</h3><p><blockquote>")
					.append(toString(session.getHeaders()))
					.append("</blockquote></p>");

			sb.append("<h3>Parms</h3><p><blockquote>")
					.append(toString(session.getParms()))
					.append("</blockquote></p>");

			sb.append("<h3>Parms (multi values?)</h3><p><blockquote>")
					.append(toString(decodedQueryParameters))
					.append("</blockquote></p>");

			try {
				Map<String, String> files = new HashMap<String, String>();
				session.parseBody(files);
				sb.append("<h3>Files</h3><p><blockquote>")
						.append(toString(files)).append("</blockquote></p>");
			} catch (Exception e) {
				e.printStackTrace();
			}

			sb.append("</body>");
			sb.append("</html>");
			return new Response(sb.toString());
		}

		private String toString(Map<String, ? extends Object> map) {
			if (map.size() == 0) {
				return "";
			}
			return unsortedList(map);
		}

		private String unsortedList(Map<String, ? extends Object> map) {
			StringBuilder sb = new StringBuilder();
			sb.append("<ul>");
			for (Map.Entry entry : map.entrySet()) {
				listItem(sb, entry);
			}
			sb.append("</ul>");
			return sb.toString();
		}

		private void listItem(StringBuilder sb, Map.Entry entry) {
			sb.append("<li><code><b>").append(entry.getKey()).append("</b> = ")
					.append(entry.getValue()).append("</code></li>");
		}
	}
}
`

**Comment by RoundSparrow** [comment]
I can confirm this also - any workarounds?

**Comment by elonen** [comment]
It seems da2a813333f77d6134a891cd19ad5f635c0b427b (or something very similar, i.e. switching to a PushbackInputStream) was applied at some point so this is probably fixed.

**Comment by elonen** [comment]
@RoundSparrow , do you have a way to try reliably reproduce / test this? Can you confirm that it still occurs after #96 was merged?

**Comment by elonen** [comment]
`HttpKeepAliveTest.java` contains a test for this (2000+ request with a small stack). Closing.
