### ISSUE TITLE
Don't use InputStream.available() as Content-Length

### ISSUE THREAD

**Issue by steventebrinke** [NanoHttpd/nanohttpd#94]
The documentation of InputStream.available() tells the following:
> Note that while some implementations of InputStream will return the total number of bytes in the stream, many will not.

On Android, the documentation is even more clear about this:
> Secondly, the result is a conservative estimate and may be significantly smaller than the actual number of bytes available. In particular, an implementation that always returns 0 would be correct. In general, callers should only use this method if they'd be satisfied with treating the result as a boolean yes or no answer to the question "is there definitely data ready?".

Therefore, using the result of this method as Content-Length, which is currently done, is definitely broken on Android and possibly on other platforms, since the method does not give the guarantee that Content-Length gives.

**Comment by ritchieGitHub** [comment]
Correct available should not be used for that, I will look into this problem

**Comment by elonen** [comment]
LeeKemp's fix (705ebbf63a4b4b13868a344bd13ee31baae006ea) looks ok. Another constructor without the `int contentLength` might be necessary. I propose that the one without explicit length would read until an exception is caught so that it could be used for infinite "comet" requests.

**Comment by ritchieGitHub** [comment]
I have to think about that. There is more involved to create a good backward compatibility

**Comment by elonen** [comment]
I guess the question is: will things break on the client side if the server doesn't provide `content-length`. IIRC, the clients shouldn't rely on it.

**Comment by steventebrinke** [comment]
LeeKemp's fix looks like it would be backward compatible, since it always sends a `Content-Length` header, but it is still broken when the content length is not given to the constructor, since it still uses `data.available()` then. I would propose to always use chunked transfer when the content length is unknown. As a workaround for my Android server, I did set `chunkedTransfer` to `true`, and then all works fine. I could write provide a pull request for such a fix, if desired.

**Comment by elonen** [comment]
Seconded. That should be a standard abiding way to do it. So basically automatically set `this.chunkedTransfer` if then data length is not passed to the `Response` constructor.

**Comment by ritchieGitHub** [comment]
That's (available usage) what was bothering me to, but the chunkedTransfer trick should work. Additionally the constructor without content length should be set to deprecated.

**Comment by elonen** [comment]
Wouldn't the constructor without length be natural for creating a chunked response?

**Comment by ritchieGitHub** [comment]
true, but due to the history of that method and the problems it created. I would make the change explicite. What if we make the constructors private and make a static methods like createChunkedResponse, createFixedSizeResponse ... then the name would say everything and upgrading by users would not hide "bugs".

**Comment by elonen** [comment]
Good point. Agreed.

**Comment by ritchieGitHub** [comment]
Could you do this? I have not much time till the weekend, only some issue categorizing I do between the lines.

**Comment by elonen** [comment]
I've got the same problem currently, but let's see.

**Comment by ritchieGitHub** [comment]
done, all response creation now by factory methods. and response now has only one constructor.
