### ISSUE TITLE
calculating length with ava

### ISSUE THREAD

**Issue by priand** [NanoHttpd/nanohttpd#98]
sendAsFixedLength() actually uses data.available() to guess the content length. But available() is not reliable to get the length, as it only returns the number of bytes available without any blocking IO. This should not be used but instead a content length should be set manually on the Response object.
A nice related enhancement would be a method in Response to send its content to an OutputStream. The default implementation would simply read the content from the InputStream, but it would avoid managing an in-memory copy of the content when only a method that write to an output stream is available (ex: JSON serialization)

**Comment by ritchieGitHub** [comment]
Same as #94
